// ============================================
// SIGN VISUAL DATA — Element percentages + trait scores
// for all 60 sign combinations.
//
// Element percentages derived from Wu Xing cycle logic:
//   Primary element:        75-85%
//   Element it generates:   45-55%
//   Element generated by:   40-50%
//   Element it overcomes:   25-35%
//   Element overcomed by:   15-25%
//
// Trait scores derived from animal archetype + element modifier.
// ============================================

import type { ZodiacElement, ZodiacAnimal, SignVisualData, ElementPercentages, TraitScores } from '@/types'
import { GENERATES, DESTROYS } from '@/lib/wuxing-cycles'

// ============================================
// ANIMAL BASE TRAITS (0-100)
// ============================================
// Each animal has a personality fingerprint across 6 traits.

const ANIMAL_TRAITS: Record<ZodiacAnimal, TraitScores> = {
  rat:     { strategy: 85, compassion: 50, resilience: 60, ambition: 80, sociability: 75, creativity: 65 },
  ox:      { strategy: 65, compassion: 60, resilience: 90, ambition: 70, sociability: 35, creativity: 40 },
  tiger:   { strategy: 55, compassion: 55, resilience: 80, ambition: 85, sociability: 70, creativity: 60 },
  rabbit:  { strategy: 60, compassion: 80, resilience: 45, ambition: 50, sociability: 75, creativity: 80 },
  dragon:  { strategy: 70, compassion: 45, resilience: 75, ambition: 95, sociability: 80, creativity: 70 },
  snake:   { strategy: 90, compassion: 40, resilience: 65, ambition: 75, sociability: 45, creativity: 75 },
  horse:   { strategy: 50, compassion: 55, resilience: 70, ambition: 80, sociability: 85, creativity: 55 },
  goat:    { strategy: 45, compassion: 85, resilience: 40, ambition: 40, sociability: 65, creativity: 90 },
  monkey:  { strategy: 80, compassion: 50, resilience: 55, ambition: 75, sociability: 85, creativity: 85 },
  rooster: { strategy: 70, compassion: 45, resilience: 70, ambition: 80, sociability: 60, creativity: 50 },
  dog:     { strategy: 60, compassion: 85, resilience: 75, ambition: 55, sociability: 65, creativity: 45 },
  pig:     { strategy: 45, compassion: 90, resilience: 50, ambition: 45, sociability: 80, creativity: 60 },
}

// ============================================
// ELEMENT TRAIT MODIFIERS
// ============================================
// Each element adds/subtracts from the animal base traits.

const ELEMENT_MODIFIERS: Record<ZodiacElement, Partial<TraitScores>> = {
  wood:  { compassion: 10, creativity: 8, sociability: 5, resilience: -3 },
  fire:  { ambition: 10, sociability: 8, creativity: 5, strategy: -5 },
  earth: { resilience: 12, compassion: 5, strategy: 3, sociability: -5 },
  metal: { strategy: 10, ambition: 8, resilience: 5, compassion: -8 },
  water: { creativity: 10, strategy: 8, compassion: 5, ambition: -5 },
}

// ============================================
// ELEMENT PERCENTAGE GENERATION
// ============================================

/**
 * Compute element percentages for a sign based on its primary element.
 * Uses Wu Xing cycle to determine affinity with each element.
 * Adds animal-based variation so each sign is distinct.
 */
function computeElementPercentages(element: ZodiacElement, animal: ZodiacAnimal): ElementPercentages {
  // Animal index for slight variation (0-11 mapped to -5 to +5 range)
  const animalIndex = ['rat', 'ox', 'tiger', 'rabbit', 'dragon', 'snake',
    'horse', 'goat', 'monkey', 'rooster', 'dog', 'pig'].indexOf(animal)
  const animalVariation = Math.round((animalIndex - 5.5) * 0.9)

  const elements: ZodiacElement[] = ['wood', 'fire', 'earth', 'metal', 'water']
  const result: Record<string, number> = {}

  for (const el of elements) {
    if (el === element) {
      // Primary element: 78-82
      result[el] = 80 + animalVariation
    } else if (GENERATES[element] === el) {
      // Element we generate: 48-52
      result[el] = 50 + animalVariation
    } else if (GENERATES[el] === element) {
      // Element that generates us: 43-47
      result[el] = 45 - animalVariation
    } else if (DESTROYS[element] === el) {
      // Element we overcome: 28-32
      result[el] = 30 + Math.abs(animalVariation)
    } else if (DESTROYS[el] === element) {
      // Element that overcomes us: 18-22
      result[el] = 20 + Math.abs(animalVariation)
    } else {
      result[el] = 35
    }
  }

  return {
    wood: clamp(result.wood ?? 35, 10, 95),
    fire: clamp(result.fire ?? 35, 10, 95),
    earth: clamp(result.earth ?? 35, 10, 95),
    metal: clamp(result.metal ?? 35, 10, 95),
    water: clamp(result.water ?? 35, 10, 95),
  }
}

/**
 * Compute trait scores for a sign by combining animal base + element modifier.
 */
function computeTraitScores(element: ZodiacElement, animal: ZodiacAnimal): TraitScores {
  const base = ANIMAL_TRAITS[animal]
  const mods = ELEMENT_MODIFIERS[element]

  return {
    strategy: clamp(base.strategy + (mods.strategy ?? 0), 10, 95),
    compassion: clamp(base.compassion + (mods.compassion ?? 0), 10, 95),
    resilience: clamp(base.resilience + (mods.resilience ?? 0), 10, 95),
    ambition: clamp(base.ambition + (mods.ambition ?? 0), 10, 95),
    sociability: clamp(base.sociability + (mods.sociability ?? 0), 10, 95),
    creativity: clamp(base.creativity + (mods.creativity ?? 0), 10, 95),
  }
}

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value))
}

// ============================================
// PRE-COMPUTED DATA FOR ALL 60 SIGNS
// ============================================

const ELEMENTS: ZodiacElement[] = ['wood', 'fire', 'earth', 'metal', 'water']
const ANIMALS: ZodiacAnimal[] = [
  'rat', 'ox', 'tiger', 'rabbit', 'dragon', 'snake',
  'horse', 'goat', 'monkey', 'rooster', 'dog', 'pig',
]

const visualDataMap: Record<string, SignVisualData> = {}

for (const element of ELEMENTS) {
  for (const animal of ANIMALS) {
    const slug = `${element}-${animal}`
    visualDataMap[slug] = {
      elementPercentages: computeElementPercentages(element, animal),
      traitScores: computeTraitScores(element, animal),
    }
  }
}

// ============================================
// PUBLIC API
// ============================================

/**
 * Get visual data (element percentages + trait scores) for a sign by slug.
 */
export function getVisualData(slug: string): SignVisualData | undefined {
  return visualDataMap[slug]
}

/**
 * Get all visual data entries (for directory or comparison views).
 */
export function getAllVisualData(): Record<string, SignVisualData> {
  return visualDataMap
}
