// ============================================
// EARTH RABBIT (戊卯) — The Serene Mediator
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'earth-rabbit',
  profile: getProfileBySlug('earth-rabbit')!,
  archetype: {
    name: "The Serene Mediator",
    tagline: "The Serene Mediator — Earth Rabbit",
  },
  atAGlance: {
      "element": "Earth (Stability, Nurturing)",
      "energy": "Yin",
      "archetype": "The Serene Mediator",
      "coreStrength": "Grounded diplomacy",
      "shadow": "Passive enabling",
      "bestMatch": "fire-goat",
      "worstMatch": "wood-rooster",
      "luckyColor": "Terracotta"
  },
  personality: {
    body: "You are the steadying hand in chaos, the one who listens when everyone else is shouting. Earth transforms Rabbit's nervous energy into something useful — practical empathy. Where other Rabbits flee conflict, you sit in the middle of it, patient as bedrock, waiting for temperatures to cool. You don't fix problems through force; you absorb tension until it dissipates. People mistake this for weakness. They're wrong. You're performing the hardest elemental work: holding center when everything spins.\n\nYour Earth element gives Rabbit's social intuition a foundation. You read rooms instantly, but instead of adapting chameleon-like, you create stable ground for others to land on. In meetings, you're the one who synthesizes opposing views without erasing their substance. In friendships, you're the constant — not exciting, not dramatic, but reliable as gravity. You build trust through repetition: showing up, following through, remembering details others forget. This makes you invaluable in organizations that would collapse into factional warfare without your binding presence.\n\nThe Yin-Earth combination makes you a natural nurturer, but you nurture systems as much as people. You see how pieces fit, where friction occurs, what needs padding. You'll rearrange an entire office layout because you noticed two colleagues always tense when they pass each other's desks. You'll shift meeting times because you tracked when energy drops. These small adjustments compound into major stability. You generate Metal — your steady presence creates the structure others need to refine their work. But you also control Water through absorption: you prevent emotional flooding by soaking up excess before it overwhelms the group. You're infrastructure, not decoration.",
  },
  shadow: {
    body: "Your absorption becomes a trap. You soak up so much tension, dysfunction, and other people's unprocessed chaos that you become a dumping ground. The worst part? You enable this. You pride yourself on handling it, on being the stable one, so you never push back when someone unloads their third crisis this week. You confuse boundary-setting with cruelty. You'd rather compact garbage inside yourself than make someone uncomfortable by saying no.\n\nThis passivity calcifies into resentment you'll never express directly. Instead, it leaks out as strategic unavailability — suddenly you can't make plans, your phone dies a lot, you're 'busy with family stuff.' You punish people through absence while maintaining plausible deniability. You've convinced yourself this is kindness. It's actually cowardice dressed in Earth-toned robes. Meanwhile, your refusal to let conflicts resolve naturally means problems never die — they just hibernate in your presence, waiting to erupt the moment you're gone. You're not creating stability; you're postponing necessary collapse.",
  },
  relationships: {
    body: "You need partners who mistake your steadiness for dullness and then discover the depth beneath. Superficial types bore you; dramatic types exhaust you. You want someone who values what you actually offer — not excitement, but the profound relief of being truly seen without judgment. You listen with your whole body, remembering not just words but context, mood, the small hesitations that reveal everything.\n\nYour danger is attracting chaos-addicts who use you as a dumping ground. You'll tolerate years of one-sided emotional labor because you tell yourself you're helping. You're not. You're enabling their refusal to process their own mess. The relationship that works is one where your stability is reciprocated with Fire's warmth or Metal's clarity — partners who actively generate energy rather than just consuming yours. You need someone who sees when you're full and insists you rest. Without that, you become a martyr, silently suffering while your partner remains obliviously dependent.",
  },
  elementBalance: {
    body: "Stop absorbing. Start filtering. Every request doesn't deserve a yes. Practice this sentence: 'I don't have capacity for that right now.' Notice how the world doesn't end.\n\nPhysically ground yourself through clay, gardening, or bread-making — activities where Earth transforms into something with boundaries. Walk barefoot on actual earth monthly. It reminds your body that ground can say 'this far, no further' to water without apology.\n\nCultivate Metal energy: structured time alone where you refine what you've absorbed instead of just holding it. Journaling, sorting, organizing — anything that transforms accumulated input into clarified output. Feed your Fire sparingly: one social event weekly where you're a participant, not a mediator. Remember, Earth generates Metal but needs Wood to stay loose. Stretch. Literally. Your body stores what your mouth won't say.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-goat",
              "name": "Fire Goat",
              "reason": "Fire warms your Earth without destabilizing it; Goat's creativity needs your grounding to manifest"
          },
          {
              "slug": "metal-pig",
              "name": "Metal Pig",
              "reason": "You generate Metal they embody; their structured generosity matches your nurturing without exploitation"
          },
          {
              "slug": "water-dog",
              "name": "Water Dog",
              "reason": "You control their Water emotionality through absorption; they guard what you protect"
          }
      ],
      "worst": [
          {
              "slug": "wood-rooster",
              "name": "Wood Rooster",
              "reason": "Wood depletes your Earth relentlessly; Rooster's criticism pierces your need for harmony"
          },
          {
              "slug": "fire-dragon",
              "name": "Fire Dragon",
              "reason": "Fire energy overwhelms your Yin stillness; Dragon demands spotlight you won't compete for"
          },
          {
              "slug": "wood-monkey",
              "name": "Wood Monkey",
              "reason": "Wood drains Earth; Monkey's chaos exhausts your need for predictable patterns"
          }
      ]
  },
}

export default content
