// ============================================
// EARTH DRAGON (戊辰) — The Sovereign Builder
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'earth-dragon',
  profile: getProfileBySlug('earth-dragon')!,
  archetype: {
    name: "The Sovereign Builder",
    tagline: "The Sovereign Builder — Earth Dragon",
  },
  atAGlance: {
      "element": "Earth (Stability, Substance, Accumulation)",
      "energy": "Yang",
      "archetype": "The Sovereign Builder",
      "coreStrength": "Grounded Ambition",
      "shadow": "Territorial Rigidity",
      "bestMatch": "metal-rooster",
      "worstMatch": "wood-rabbit",
      "luckyColor": "Ochre"
  },
  personality: {
    body: "The Earth Dragon is a rarity—a mythic creature who plants its claws in the ground and builds kingdoms that last. Where other Dragons soar on vision and charisma, you accumulate power through patience, methodical execution, and an unshakeable understanding that empires require foundations. You possess the Dragon's natural authority and magnetism, but Earth tempers the fire-breathing impulse with strategic restraint. You don't just dream—you architect, measuring twice and cutting once, turning ambition into assets.\n\nYour leadership style is pragmatic sovereignty. You inspire loyalty not through dazzling displays but through demonstrated competence and the tangible results you consistently deliver. People follow you because you make them feel secure, because your plans actually work, because you create structures that protect and provide. You're the executive who knows every line item in the budget, the community organizer who secures the building before launching the movement, the visionary who understands that revolution requires logistics. Earth gives your Dragon nature the gift of completion—you finish what you start.\n\nYou accumulate influence like sediment forming rock—slowly, steadily, with geological inevitability. Where Metal Dragon cuts and Fire Dragon blazes, you absorb and integrate. You're comfortable with gradual expansion, understanding that sustainable growth requires consolidation. Your wealth isn't flashy; it's farmland, real estate, infrastructure, investments that compound over decades. You think in dynasties, not quarters. This makes you formidable in negotiations—you can outwait almost anyone, and your patience is backed by genuine power reserves that others mistake for slowness until it's too late to compete.",
  },
  shadow: {
    body: "Your stability curdles into territorial possession when threatened. You confuse ownership with control, treating people, projects, and ideas as property to be hoarded rather than resources to be circulated. Earth's controlling nature over Water means you dam up emotional flow—in yourself and others—creating stagnant pools where resentment breeds. You become the boss who can't delegate, the parent who suffocates, the partner who monitors rather than trusts.\n\nYour patience becomes stubbornness weaponized. You dig trenches instead of pivoting, defending positions long after they've become indefensible simply because you invested so much in establishing them. The same methodical nature that builds empires can lock you into obsolete strategies, unable to abandon sunk costs. You hoard credit, hoard resources, hoard information, believing that scarcity equals security. Your Dragon pride combined with Earth's accumulative drive creates a paradox—you want recognition but refuse to share the spotlight, leaving you isolated at the top of pyramids you built alone.",
  },
  relationships: {
    body: "You love through provision and protection, building security around those you care for. But relationships require flow, not fortification. Your partners need to feel trusted, not managed. You excel with people who appreciate stability but challenge your rigidity—Metal signs who refine your structures without dismantling them, or Water types who teach you that power can be fluid without being weak.\n\nYou're fiercely loyal once commitment is established, but your trust develops on geological timelines that exhaust more spontaneous signs. You test people, sometimes unconsciously, waiting to see if they'll stay through the slow seasons. This creates relationships built on endurance rather than passion—sustainable, yes, but sometimes loveless. You need partners who can articulate emotional needs clearly because you interpret love as responsibility fulfilled, not feelings expressed. Learn to nurture without controlling. Build foundations under people, not walls around them. Your greatest relationships occur when you realize that letting others grow doesn't diminish your kingdom—it expands it.",
  },
  elementBalance: {
    body: "You need Metal activities to refine your accumulated mass—editing, curating, distilling essence from bulk. Practice letting go of 10% of what you own quarterly; Earth overbalanced becomes clutter. Introduce Wood energy through creative risks that force you beyond established territory: take a class in something you're bad at, fund someone else's vision without controlling it. Move your body—Earth Dragons stagnate physically when mentally fixed. Your power is real, but it needs circulation. Generate Metal (your child element) by defining clear boundaries and removing what doesn't serve. Allow Water to flow through your structures by delegating fully, trusting others' competence. Build channels, not dams.",
  },
  matches: {
      "best": [
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "You generate Metal; Rooster's precision refines your ambitions into executable systems without threatening your authority"
          },
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "You provide stability for their innovations; they prevent your stagnation with clever adaptation of your structures"
          },
          {
              "slug": "water-rat",
              "name": "Water Rat",
              "reason": "You control Water productively here; Rat's resourcefulness flows through your channels, creating sustainable wealth cycles"
          }
      ],
      "worst": [
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Wood depletes Earth; Rabbit's indirect diplomacy feels evasive to your direct authority, creating exhausting power struggles"
          },
          {
              "slug": "wood-goat",
              "name": "Wood Goat",
              "reason": "You control their creative chaos, but Wood drains your resources while Goat resents your heavy-handed structure"
          },
          {
              "slug": "water-dog",
              "name": "Water Dog",
              "reason": "You dam Dog's emotional idealism; they see your pragmatism as moral compromise, triggering mutual judgment"
          }
      ]
  },
}

export default content
