// ============================================
// EARTH HORSE (戊午) — The Enduring Trailblazer
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'earth-horse',
  profile: getProfileBySlug('earth-horse')!,
  archetype: {
    name: "The Enduring Trailblazer",
    tagline: "The Enduring Trailblazer — Earth Horse",
  },
  atAGlance: {
      "element": "Earth (Stability, Nurturing, Endurance)",
      "energy": "Yang",
      "archetype": "The Enduring Trailblazer",
      "coreStrength": "Grounded momentum",
      "shadow": "Stubborn immobility",
      "bestMatch": "metal-dog",
      "worstMatch": "water-monkey",
      "luckyColor": "Terracotta"
  },
  personality: {
    body: "The Earth Horse is the paradox that actually works—wild spirit anchored by pragmatic roots. Where other Horses bolt at the first sign of constraint, you've learned to channel that explosive energy into sustained campaigns. You're not racing toward the horizon anymore; you're building the road there. This isn't compromise. It's strategic evolution. Earth gives your Yang fire a foundation to burn from, transforming reckless galloping into purposeful stride.\n\nYou excel at taking visionary ideas and making them real. While others talk about revolution, you're calculating resources, timelines, and logistics. Your colleagues see you as the reliable maverick—the one who'll champion the bold move but won't leave bodies in your wake. You commit to projects with unusual stamina for a Horse, seeing them through the tedious middle phases that bore your elemental cousins. Earth's centering energy means you actually finish what you start, a rarity in Horse territory.\n\nYour social presence is warm but weighted. People feel steadied around you, like you're radiating low-frequency confidence that calms the room. You mentor naturally, not through lectures but by demonstrating how to balance ambition with accountability. There's a nurturing quality beneath your independent streak—you want others to succeed, but only if they're willing to do the work. You have zero patience for shortcuts or excuses.\n\nThe Earth influence makes you territorial about your methods and spaces. You need physical environments that reflect stability—a well-organized workspace, a home base that feels permanent. Nomadic freedom loses its appeal when you can't bring your accumulated foundations with you. You're building legacy, not just chasing experiences.",
  },
  shadow: {
    body: "Your greatest strength calcifies into your deepest trap. That grounded momentum becomes immovable stubbornness when Earth's consolidating nature overwhelms Horse's adaptive instinct. You dig trenches around your position and defend them past the point of reason, confusing consistency with wisdom. When challenged, you don't explode like Fire Horse—you simply refuse to budge, becoming a wall that frustrates everyone around you.\n\nYou over-attach to methods that worked once, unable to see when circumstances have shifted. Earth's need for security makes you hoard—not just objects, but outdated strategies, relationships that no longer serve, and grudges you should've released years ago. Your nurturing impulse turns controlling when anxious. You'll micromanage people you claim to trust, justifying it as guidance while actually suffocating their autonomy. The shadow Earth Horse becomes the martyr who does everything themselves, then resents others for not helping in the exact way they never asked for.",
  },
  relationships: {
    body: "You need partners who respect your need for both adventure and base camp. Clingy attachment suffocates you, but you also can't handle relationships that feel rootless. You're searching for someone who understands that commitment doesn't mean stagnation—that you can build something lasting while still exploring new terrain together.\n\nYou show love through practical support and consistent presence. Grand gestures feel hollow to you; you'd rather show up reliably for two decades than deliver one perfect romantic moment. But you must guard against assuming everyone shares your definition of loyalty. Your partners need to know you hear their emotional needs, not just their logistical ones.\n\nIn friendships, you're the anchor in the storm—until someone tries to change your plans last-minute. You value dependability because you offer it, and flakiness reads as disrespect. You'll invest deeply in people who prove themselves over time, but earning your trust requires passing the endurance test. You don't do fair-weather friendships.",
  },
  elementBalance: {
    body: "When Earth becomes excessive, you petrify. Interrupt this with deliberate movement—not frantic activity, but purposeful physical engagement. Long hikes, martial arts that emphasize flow over strength, or projects that require you to adapt in real-time. You need Metal's refining influence to keep Earth from becoming mud: audit your commitments quarterly, cutting what no longer serves your actual goals versus your fear of change.\n\nWood energy prevents stagnation—introduce new learning regularly, even if it's outside your expertise. Take the class that makes you a beginner again. Your Earth thrives when it's nurturing growth, not just maintaining what exists. Stop saying yes to stability and no to everything else.",
  },
  matches: {
      "best": [
          {
              "slug": "metal-dog",
              "name": "Metal Dog",
              "reason": "Earth generates Metal—you provide the foundation for their principled structure while they refine your vision into excellence"
          },
          {
              "slug": "fire-tiger",
              "name": "Fire Tiger",
              "reason": "Your Earth grounds their explosive creativity without dampening it, creating sustainable boldness neither achieves alone"
          },
          {
              "slug": "earth-pig",
              "name": "Earth Pig",
              "reason": "Doubled Earth creates unshakeable mutual loyalty—you both value the same practical devotion and slow-built trust"
          }
      ],
      "worst": [
          {
              "slug": "water-monkey",
              "name": "Water Monkey",
              "reason": "Earth controls Water—you try to dam their flow while they erode your foundations with constant scheming and adaptability"
          },
          {
              "slug": "wood-rat",
              "name": "Wood Rat",
              "reason": "Wood depletes Earth—their constant growth demands drain your resources while you feel exploited for your stability"
          },
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "They see your caution as cowardice; you see their impulsiveness as irresponsible—same animal, incompatible operating systems"
          }
      ]
  },
}

export default content
