// ============================================
// EARTH DOG (戊戌) — The Unwavering Sentinel
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'earth-dog',
  profile: getProfileBySlug('earth-dog')!,
  archetype: {
    name: "The Unwavering Sentinel",
    tagline: "The Unwavering Sentinel — Earth Dog",
  },
  atAGlance: {
      "element": "Earth (Stability, Endurance)",
      "energy": "Yang",
      "archetype": "The Unwavering Sentinel",
      "coreStrength": "Dependable protection",
      "shadow": "Rigid stubbornness",
      "bestMatch": "metal-monkey",
      "worstMatch": "wood-rabbit",
      "luckyColor": "Terracotta"
  },
  personality: {
    body: "You're the rock everyone leans on when chaos erupts. Earth Dog doesn't waver—your loyalty isn't conditional, your word isn't negotiable, and your sense of duty runs deeper than most people's capacity for emotion. Where other Dogs might chase every perceived threat, Earth grounds your protective instincts into something sustainable. You don't panic. You assess, position yourself strategically, and hold the line. People trust you because you've never given them reason not to.\n\nYour Earth element transforms the Dog's natural vigilance into institutional memory. You remember who showed up when it mattered, who made promises they didn't keep, who's genuinely vulnerable versus who's performing victimhood. This isn't grudge-holding—it's pattern recognition. You build relationships like you build foundations: slowly, methodically, with attention to load-bearing capacity. Casual friendships confuse you. Either someone's in your circle or they're not. Once they're in, you'll defend them past the point of reason.\n\nThe Yang energy means you don't wait to be asked. You see the need and fill it—organizing the group camping trip, mediating the family dispute, staying late to help the overwhelmed colleague. But your helping isn't soft. You tell people what they need to hear, not what makes them comfortable. Earth Dog criticism lands heavy because it comes from someone who's proven their investment. You're building something durable, and you have no patience for shortcuts that compromise structural integrity. Your standards aren't negotiable because lowering them would be betraying your own nature.",
  },
  shadow: {
    body: "Your stability calcifies into obstinacy. Once you've decided the 'right way' to do something, new information bounces off like rain off concrete. You mistake consistency for virtue and flexibility for betrayal of principles. This makes you the person still using the filing system from 2003, still insisting on the family tradition nobody enjoys, still loyal to the friend who stopped reciprocating years ago. Earth's tendency to accumulate becomes hoarding—of grudges, of outdated methods, of relationships that have expired.\n\nYour protective instincts turn controlling. You don't trust others to make their own mistakes, so you block the path, make the decision for them, become the bottleneck disguised as the guardian. People feel smothered by the weight of your care. And when they finally push back, you interpret their need for autonomy as ingratitude. Your shadow convinces you that boundary-setting equals abandonment. You'd rather exhaust yourself maintaining a crumbling structure than admit it's time to rebuild.",
  },
  relationships: {
    body: "You need people who understand that your silence isn't absence—it's attentive presence. The best partners don't mistake your steadiness for lack of feeling; they recognize the depth beneath the stable surface. You're not demonstrative, but you're utterly reliable. You show love through actions that prevent problems before they occur, through remembering details others forget, through being the person who doesn't need to be reminded.\n\nYou're drawn to those who bring adaptability without flakiness—Metal types who can structure your loyalty into effective systems, Water types who can teach you when to flow around obstacles instead of holding position. But you clash with Wood energy that wants growth for growth's sake, change for novelty's sake. You need to know why we're moving before you'll budge, and the answer 'because it's time' doesn't satisfy you. In conflict, you don't explode—you solidify. The silent treatment becomes an art form. Learning to articulate your boundaries before you've turned to stone saves relationships you actually value.",
  },
  elementBalance: {
    body: "Your Earth excess needs Wood's disruption and Metal's refinement. Practically: commit to one experimental change per quarter—new route to work, different morning routine, unfamiliar restaurant. Let others lead without your input. Take the yoga class that forces you out of rigid postures. Metal balance comes through editing—what loyalties have expired, what systems need retiring, what grudges you're carrying that serve no purpose. Write them down, acknowledge what they once protected, then physically destroy the list. Earth rebalances through literal earthwork when possible—gardening, pottery, hiking in clay-heavy soil. The element needs to touch its own nature to remember that even mountains reshape over time.",
  },
  matches: {
      "best": [
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "Earth generates Metal—your stability gives their cleverness sustainable structure and purpose"
          },
          {
              "slug": "metal-ox",
              "name": "Metal Ox",
              "reason": "Shared Earth-Metal synergy creates unshakeable foundations with precision and endurance"
          },
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Fire generates Earth—their passionate momentum feeds your protective capacity without overwhelming it"
          }
      ],
      "worst": [
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Earth controls Wood—you smother their need for gentle growth with heavy-handed stability"
          },
          {
              "slug": "wood-dragon",
              "name": "Wood Dragon",
              "reason": "Your immovable defense clashes with their expansive vision, neither willing to yield position"
          },
          {
              "slug": "water-rooster",
              "name": "Water Rooster",
              "reason": "Earth controls Water—your need for constancy blocks their fluid precision and adaptive perfectionism"
          }
      ]
  },
}

export default content
