// ============================================
// EARTH RAT (戊子) — The Grounded Strategist
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'earth-rat',
  profile: getProfileBySlug('earth-rat')!,
  archetype: {
    name: "The Grounded Strategist",
    tagline: "The Grounded Strategist — Earth Rat",
  },
  atAGlance: {
      "element": "Earth (Stability, Practicality)",
      "energy": "Yang",
      "archetype": "The Grounded Strategist",
      "coreStrength": "Pragmatic accumulation",
      "shadow": "Stagnant hoarding",
      "bestMatch": "metal-monkey",
      "worstMatch": "wood-rabbit",
      "luckyColor": "Terracotta"
  },
  personality: {
    body: "The Earth Rat is the strategist who builds empires from careful resource management and unshakeable patience. Where other Rats dart and improvise, you accumulate methodically. You see opportunities not as flashes to chase but as foundations to build upon. Your Earth element transforms the Rat's natural cleverness into something tangible—portfolios, networks, systems that compound over time. You don't just survive; you create security that lasts generations.\n\nYour Yang energy drives you to act, but Earth tempers that action with deliberation. You're not impulsive. Every move is calculated for long-term gain. You excel at reading rooms, assessing value, and positioning yourself at the center of resource flow. People underestimate you because you don't flash your hand. You let others chase the spotlight while you quietly acquire the building, the contact list, the intellectual property. You understand that real power isn't loud—it's structural.\n\nYour practicality borders on genius. You see connections others miss—not abstract patterns, but concrete pathways to advantage. That struggling startup? You see the patent buried in their pitch deck. That networking event? You identify the three people who actually matter. You're not sentimental about opportunities; you're surgical. This makes you exceptional in business, logistics, real estate—anywhere patient accumulation beats flashy risk-taking.\n\nBut your stability isn't passive. Yang Earth moves like a mountain extending its roots—slow, inevitable, transforming landscape through sheer persistent pressure. You don't adapt quickly, but you don't need to. You build systems so solid that turbulence breaks against them. When chaos comes, people discover you've been preparing for exactly this scenario for five years.",
  },
  shadow: {
    body: "Your shadow emerges when Earth's stability becomes stagnation, when accumulation becomes hoarding. You hold onto resources, relationships, and grudges long past their utility. That investment that's clearly dying? You can't let go because you put three years into it. That person who betrayed you a decade ago? You still track their failures with grim satisfaction. You confuse sunk costs with commitment, turning patience into paralysis.\n\nYour pragmatism can metastasize into joyless calculation. Everything becomes transactional. Friendships are networks. Conversations are reconnaissance. Love itself gets filed under \"strategic partnerships.\" You optimize the humanity out of your life, then wonder why success feels hollow. You're so busy building security that you forget to live in it.\n\nWorst, you develop a toxic relationship with scarcity. Even with abundance, you hoard. You understaff your business to save pennies. You won't delegate because no one else can be trusted. You turn generosity into a zero-sum game where giving anything away means losing. Earth's nurturing potential inverts into suffocating control—you'll help people, but only on your terms, only in ways that keep them dependent. You become the gatekeeper who forgets that dammed water eventually stagnates.",
  },
  relationships: {
    body: "You bond through loyalty and practical support. You won't write love poetry, but you'll research mortgage rates for a friend at 2 AM. You show care through tangible actions—fixing problems, creating stability, building shared security. You need partners who understand that your version of romance is remembering their financial goals and structuring joint accounts for optimal tax efficiency.\n\nYour challenge is vulnerability. You treat emotional intimacy like a negotiation where showing need is losing leverage. You'll support everyone else's crises while hiding your own behind competence. Partners often feel they're living with a benevolent provider rather than an equal—you've solved all their problems before they've shared how they feel about them.\n\nYou thrive with people who respect your need for control but refuse to be controlled. You need partners with enough independence that you can't make them projects, forcing you into actual emotional exchange. Your best relationships involve clear agreements, shared goals, and mutual respect for boundaries. You're devastatingly loyal once committed, but commitment means someone has proven their reliability through consistent action over years.",
  },
  elementBalance: {
    body: "Your Earth excess needs Wood to break it up—growth that disrupts your routines. Take the inefficient path occasionally. Mentor someone with no immediate ROI. Start a project with uncertain outcomes. Let controlled chaos enter your systems.\n\nYou generate Metal, so channel accumulation into refinement. Don't just gather resources—distill them into something sharp and valuable. Edit your portfolio. Quality over quantity. Practice strategic subtraction.\n\nMost critically, spend what you've saved. Not recklessly—strategically enjoy the security you've built. Take the vacation. Upgrade the thing. Give the gift without tracking reciprocity. Earth's purpose is nourishment. If you're not feeding anything with your abundance, you're just a warehouse.",
  },
  matches: {
      "best": [
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "Your Earth generates their Metal—you provide resources for their precision and innovation, creating wealth-building synergy"
          },
          {
              "slug": "metal-ox",
              "name": "Metal Ox",
              "reason": "Earth feeds Metal; both value endurance and systematic effort—you build empires together through patient execution"
          },
          {
              "slug": "fire-dragon",
              "name": "Fire Dragon",
              "reason": "Fire generates Earth in the productive cycle—their bold vision creates opportunities your pragmatism can consolidate"
          }
      ],
      "worst": [
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Wood controls Earth in the destructive cycle—their need for growth and change constantly destabilizes your foundations"
          },
          {
              "slug": "wood-tiger",
              "name": "Wood Tiger",
              "reason": "Wood breaks up Earth; their impulsive risk-taking undermines your careful accumulation strategies"
          },
          {
              "slug": "water-horse",
              "name": "Water Horse",
              "reason": "Earth controls Water but exhausts itself trying; their restless freedom clashes with your need for stable structure"
          }
      ]
  },
}

export default content
