// ============================================
// EARTH MONKEY (戊申) — The Pragmatic Innovator
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'earth-monkey',
  profile: getProfileBySlug('earth-monkey')!,
  archetype: {
    name: "The Pragmatic Innovator",
    tagline: "The Pragmatic Innovator — Earth Monkey",
  },
  atAGlance: {
      "element": "Earth (Stability, Practicality)",
      "energy": "Yang",
      "archetype": "The Pragmatic Innovator",
      "coreStrength": "Grounded creativity",
      "shadow": "Calculating manipulation",
      "bestMatch": "metal-rat",
      "worstMatch": "wood-tiger",
      "luckyColor": "Terracotta"
  },
  personality: {
    body: "Earth Monkey isn't interested in clever for clever's sake. You take the Monkey's natural inventiveness and run it through a practicality filter that most of your animal cousins lack entirely. Where Fire Monkeys explode with ideas and Metal Monkeys polish them to perfection, you build things that actually work in the real world. Your innovations aren't flashy—they're useful. You see a problem, you solve it, you move on. No drama, no need for applause, though you'll accept payment.\n\nEarth's stabilizing influence means you're the Monkey who finishes projects. Shocking, really. You have patience that other Monkeys don't possess, the ability to stick with something tedious if the outcome matters. This makes you dangerous in business—you combine strategic thinking with follow-through, a rare and profitable combination. You're not the person pitching wild schemes at networking events. You're the one quietly building an empire while everyone else is still arguing about mission statements.\n\nYour Yang energy expresses through building, not performing. You're active, ambitious, outward-focused, but in Earth's measured way. You don't need to be the smartest person in the room if you're the most effective. You accumulate resources, relationships, knowledge—slowly, steadily, with the patience of someone who understands compound interest. People underestimate you because you're not loud about your capabilities. That's their mistake. You're playing a longer game than most, and you're usually three moves ahead while appearing to barely pay attention.",
  },
  shadow: {
    body: "Earth Monkey's shadow is manipulation dressed as helpfulness. You know how to make people feel supported while steering them exactly where you want them. The Earth element's nurturing quality becomes strategic when filtered through Monkey cunning—you're generous when it serves you, helpful when it creates obligation. You're not above using someone's trust as leverage later.\n\nYour practical nature can calcify into ruthless pragmatism. If something doesn't serve your goals, it doesn't exist. People become tools, relationships become transactions. You'll maintain friendships purely for networking value, smile at people you privately dismiss as useless. Earth's hoarding tendency combines with Monkey cleverness to create someone who games every system, exploits every loophole, always looking for the angle. When stagnant, you're not building anymore—you're just accumulating for accumulation's sake, clever enough to justify any behavior as 'realistic' or 'strategic.' You become the person who knows the price of everything and the value of nothing.",
  },
  relationships: {
    body: "You need partners who can call out your schemes without drama. Someone who sees through your strategic helpfulness but appreciates the competence underneath. You're actually loyal when you've decided someone is worth keeping—Earth provides that—but you need people who don't mistake your practicality for coldness or your long-term thinking for emotional distance.\n\nYou show love through solving problems and building security. You're not bringing flowers; you're refinancing their mortgage at a better rate. You're fixing the thing they mentioned was broken three weeks ago. Your version of romance is making someone's life tangibly better, and you need partners who understand that's genuine affection, not a transaction. You struggle with people who need constant emotional processing—you'd rather fix the problem than talk about feelings about the problem.\n\nEarth Monkeys pair best with people who match your competence and share your drive for concrete results. You respect capability. Show up prepared, follow through on commitments, bring solutions instead of complaints, and you'll invest deeply. But you have little patience for emotional volatility or people who create chaos then expect you to clean it up. You're building something—join the construction or stay out of the way.",
  },
  elementBalance: {
    body: "Earth balance requires you to cycle energy, not just accumulate it. You generate Metal—refine what you've built, prune what doesn't work, create clear boundaries around your time and resources. Stop hoarding opportunities you'll never use. You control Water—direct your flow toward actual goals instead of drowning in overthinking every angle.\n\nPhysically: Move your body in ways that feel productive, not just efficient. Hike with a destination. Garden with purpose. Build something with your hands that serves no strategic function whatsoever.\n\nMentally: Journal about decisions where you chose connection over advantage. Practice generosity that costs you something. Ask yourself weekly: 'What am I building this for?' If the answer is just 'more,' that's stagnation, not growth. Earth needs to nourish, not just contain.",
  },
  matches: {
      "best": [
          {
              "slug": "metal-rat",
              "name": "Metal Rat",
              "reason": "Earth generates Metal—you provide foundation for their precision; both value competence over performance"
          },
          {
              "slug": "fire-dragon",
              "name": "Fire Dragon",
              "reason": "Fire generates Earth—their vision fuels your execution; you ground their ambition into reality"
          },
          {
              "slug": "metal-ox",
              "name": "Metal Ox",
              "reason": "You generate their Metal refinement; shared appreciation for discipline and tangible results"
          }
      ],
      "worst": [
          {
              "slug": "wood-tiger",
              "name": "Wood Tiger",
              "reason": "Wood depletes Earth—their impulsive expansion drains your stability; chaos versus strategy"
          },
          {
              "slug": "water-horse",
              "name": "Water Horse",
              "reason": "Earth controls Water but exhausts trying; their need for freedom clashes with your need for structure"
          },
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Wood extraction without appreciation—they take your nurturing as given, you resent their avoidance of practical matters"
          }
      ]
  },
}

export default content
