// ============================================
// EARTH SNAKE (戊巳) — The Silent Authority
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'earth-snake',
  profile: getProfileBySlug('earth-snake')!,
  archetype: {
    name: "The Silent Authority",
    tagline: "The Silent Authority — Earth Snake",
  },
  atAGlance: {
      "element": "Earth (Stability, Nurturing, Endurance)",
      "energy": "Yin",
      "archetype": "The Silent Authority",
      "coreStrength": "Unshakable presence",
      "shadow": "Emotional hoarding",
      "bestMatch": "metal-rooster",
      "worstMatch": "water-rabbit",
      "luckyColor": "Ochre"
  },
  personality: {
    body: "You are the strategist who doesn't need to announce their power. While other Snakes charm or seduce, you simply exist with such gravitational weight that people orbit around you. Earth's stability transforms the Snake's innate cunning into something far more dangerous: institutional memory. You remember every slight, every favor, every pattern — not from vengefulness but because you are the ground itself, recording every footstep.\n\nYour intuition operates through accumulation rather than flash. Where Fire Snake has sudden insights and Water Snake reads emotional currents, you build understanding through patient observation. You watch people repeat their patterns across months or years, then act when the moment crystallizes. This makes you terrifying in negotiations. You'll sit through ten meetings saying little, then in the eleventh, deploy a single sentence that restructures the entire agreement. Your silence isn't passive — it's agricultural. You're composting information.\n\nThe Earth element grounds Snake's natural secrecy into something productive. You don't hide for drama; you're private because you're building something that requires protection. Whether it's a business, a family legacy, or a body of knowledge, you tend your garden away from public scrutiny. People experience you as deeply reliable yet somehow unknowable. You'll show up for decades of small commitments but never fully explain your motivations.\n\nYour nurturing instinct expresses through provision rather than affection. You ensure people have what they need — resources, information, stability — but you're not effusive about it. Love, for you, is a foundation you lay, not a performance you give. This can read as coldness to those who need verbal reassurance, but to those who understand your language, you're the most loyal force they'll ever encounter.",
  },
  shadow: {
    body: "Your stability curdles into stagnation when you mistake accumulation for growth. You hoard — information, resources, grudges, even people — telling yourself it's strategic reserve when it's actually fear of loss. This turns your sanctuary into a museum where nothing can leave or change. You'll maintain relationships that stopped serving anyone years ago simply because endings feel like structural failure.\n\nThe dark side of your institutional memory is that you weaponize history. You'll bring up someone's mistake from five years ago with documentary precision, not to heal or learn but to win. Your patience becomes passive aggression. Instead of addressing conflict directly, you withdraw and let your silence function as punishment. People around you learn to navigate an invisible minefield of unspoken rules you never articulated but will absolutely enforce.\n\nWhen imbalanced, Earth's nurturing inverts into smothering control. You provide so much that others can't develop independence, ensuring they need you. Your 'helping' becomes a cage dressed as generosity.",
  },
  relationships: {
    body: "You need partners who understand that your depth isn't demonstrated through constant emotional display. You bond through shared silence, through building something tangible together, through the accumulation of small reliable actions. Grand romantic gestures leave you cold; remembering how someone takes their coffee after mentioning it once is your love language.\n\nYou're devastatingly loyal but require absolute privacy. A partner who demands full transparency or constant verbal processing will exhaust you. You reveal yourself in layers, slowly, and only when the ground feels stable. Rushing this process makes you retreat completely.\n\nIn conflict, you need someone who can tolerate your processing time. You don't think out loud — you withdraw, consider all variables, then return with a position. Partners who chase you during this withdrawal or interpret your silence as abandonment create impossible dynamics. Your ideal match respects the cave, trusts you'll emerge, and doesn't fill your quiet with anxious noise.",
  },
  elementBalance: {
    body: "Your Earth excess shows up as rumination and stuckness. Counter it by generating Metal — create frameworks that force decisions. Set arbitrary deadlines. Use financial investments that make retreat expensive. Write binding contracts even for personal projects.\n\nPhysically, you need practices that break static holding patterns. Not gentle yoga — you need weight resistance, pottery throwing, bread kneading. Activities where you push against real resistance and see definitive results. Gardening works only if you're actually transplanting and pruning, not just watering.\n\nPractice strategic disclosure. Once weekly, tell someone something you normally wouldn't share — not trauma dumping, but breaking your default privacy setting. This prevents emotional constipation. Schedule regular purges of physical and informational clutter. If you haven't used it in a year, it's not strategic reserve, it's hoarding.",
  },
  matches: {
      "best": [
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Earth generates Metal — your depth gives their precision something substantial to refine and organize into systems"
          },
          {
              "slug": "metal-ox",
              "name": "Metal Ox",
              "reason": "Shared Earth appreciation for building slowly; Metal's structure prevents your stagnation without disrupting your pace"
          },
          {
              "slug": "fire-dragon",
              "name": "Fire Dragon",
              "reason": "Fire generates Earth — their bold action creates new ground for you to stabilize and develop into lasting infrastructure"
          }
      ],
      "worst": [
          {
              "slug": "water-rabbit",
              "name": "Water Rabbit",
              "reason": "Earth controls Water — you dam their emotional flow into avoidance; their need for harmony triggers your control patterns"
          },
          {
              "slug": "wood-monkey",
              "name": "Wood Monkey",
              "reason": "Wood controls Earth — their constant innovation destabilizes your foundations; you experience their flexibility as chaos"
          },
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Your Earth absorption turns their Water generosity into enabling; neither addresses problems, just accumulates resentment"
          }
      ]
  },
}

export default content
