// ============================================
// EARTH GOAT (戊未) — The Nurturing Architect
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'earth-goat',
  profile: getProfileBySlug('earth-goat')!,
  archetype: {
    name: "The Nurturing Architect",
    tagline: "The Nurturing Architect — Earth Goat",
  },
  atAGlance: {
      "element": "Earth (Stability, Nurturing)",
      "energy": "Yin",
      "archetype": "The Nurturing Architect",
      "coreStrength": "Patient cultivation",
      "shadow": "Anxious immobility",
      "bestMatch": "fire-rabbit",
      "worstMatch": "wood-monkey",
      "luckyColor": "Terracotta"
  },
  personality: {
    body: "Earth Goat is the patient gardener of human potential—someone who builds slowly, deliberately, and with profound attention to what needs to take root. Where other Goats drift toward aesthetic fantasy, Earth element anchors this sign's creative sensitivity into tangible form. You don't just dream about beautiful spaces or harmonious communities; you roll up your sleeves and build them, brick by brick, relationship by relationship. Your nurturing isn't the dramatic Fire kind or the flowing Water kind—it's the steady provision of fertile ground where things can actually grow.\n\nYour Yin energy doubled (Goat plus Earth) creates someone who leads through receptivity rather than force. You notice what's missing before others complain about it. You sense when someone needs encouragement before they ask. This makes you an exceptional team builder, community organizer, or mentor—roles where your gift for creating psychological safety becomes infrastructure others can rely on. You're genuinely invested in collective wellbeing, not as abstract ideology but as lived daily practice. The potluck you organize, the shared garden you maintain, the study group you facilitate—these aren't hobbies, they're expressions of your core belief that abundance grows through reciprocal care.\n\nBut your Earth element also makes you stubborn in ways other Goats aren't. Once you've decided something is worth building—a relationship, a project, a routine—you commit with mountain-like endurance. You'll nurture failing enterprises long past their expiration date, believing your steady care can revive anything. This persistence is your greatest strength and your deepest trap. You generate Metal in the elemental cycle, meaning your stability eventually produces refinement and structure, but only if you're building something genuinely viable. When you're pouring energy into barren ground, you're just exhausting yourself.",
  },
  shadow: {
    body: "Your shadow is anxious immobility disguised as patience. You stay in situations that deplete you—dead-end jobs, one-sided friendships, communities that take without giving—telling yourself you're being loyal when you're actually paralyzed by fear of disruption. Earth element can become stagnant, and for you this manifests as clinging to familiarity even when it's suffocating you. You'll endure toxic workplaces because 'at least you know what to expect,' remain in relationships where you're the only one nurturing, convince yourself that your exhaustion is noble sacrifice rather than poor boundaries.\n\nYour Yin doubling makes you conflict-avoidant to a fault. You'd rather absorb mistreatment than risk the discomfort of confrontation. This isn't kindness—it's cowardice wearing a compassionate mask. Worse, your Earth stubbornness means you dig into these patterns, becoming passively immovable. You won't leave, but you'll radiate resentment. You'll martyr yourself while simultaneously guilt-tripping others for not appreciating your suffering enough. The very nurturing capacity that makes you valuable curdles into manipulative caretaking where you keep score of every kindness, building silent resentment structures as solid as the support structures you build for others.",
  },
  relationships: {
    body: "You need partners who recognize that your quiet steadiness is strength, not weakness. You're not dramatic about your needs, which means they often get ignored unless someone's actually paying attention. You thrive with people who understand reciprocity—not transactional scorekeeping, but genuine mutual care. Fire signs can energize you, pulling you out of Earth's tendency toward inertia, but only if they respect your slower rhythms rather than constantly pushing you to move faster.\n\nIn friendships and romance, you're the one who remembers birthdays, notices mood shifts, creates traditions that become the glue holding groups together. But you need people who do their share of initiating, who reach out to you rather than always waiting for your outreach. Your Goat nature craves beauty and harmony in relationships—you'll tolerate a lot to avoid conflict, but you wither in environments of constant tension or criticism. You need appreciation expressed concretely, not just assumed. Tell you specifically what your care means. Show up when you need help. Don't mistake your patience for infinite capacity.",
  },
  elementBalance: {
    body: "Balance your Earth by deliberately engaging Wood energy—movement, growth, flexibility. Take walks in actual nature rather than just thinking about it. Change your routines regularly; your element craves repetition, which calcifies into ruts. Practice saying no without elaborate justification—Earth Goats over-explain to soften boundary-setting. Limit your caretaking to people and projects that reciprocate; nurturing barren ground depletes you without generating the Metal clarity you're meant to produce. Schedule activities that pull you out of your comfort zone monthly. Your stability is valuable, but unchallenged Earth becomes stagnant soil where nothing new can grow. Move your body, change your environment, risk small discomforts—these keep your nurturing capacity fresh rather than obligatory.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-rabbit",
              "name": "Fire Rabbit",
              "reason": "Fire generates Earth—their warmth energizes your nurturing without overwhelming your need for harmony and aesthetic refuge"
          },
          {
              "slug": "fire-pig",
              "name": "Fire Pig",
              "reason": "Shared commitment to community wellbeing, Fire energizes your Earth stability, mutual generosity creates sustainable reciprocity"
          },
          {
              "slug": "metal-horse",
              "name": "Metal Horse",
              "reason": "You generate Metal they embody—your grounding balances their momentum, their drive prevents your stagnation"
          }
      ],
      "worst": [
          {
              "slug": "wood-monkey",
              "name": "Wood Monkey",
              "reason": "Wood controls Earth—their chaotic innovation destabilizes your need for steady cultivation, exhausting clash of tempos"
          },
          {
              "slug": "wood-tiger",
              "name": "Wood Tiger",
              "reason": "Wood depletes Earth—their aggressive expansion drains your resources, their impatience tramples your careful building"
          },
          {
              "slug": "water-rooster",
              "name": "Water Rooster",
              "reason": "Earth controls Water but their critical precision attacks your sensitive nature, mutual frustration over different standards"
          }
      ]
  },
}

export default content
