// ============================================
// EARTH TIGER (戊寅) — The Patient Warrior
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'earth-tiger',
  profile: getProfileBySlug('earth-tiger')!,
  archetype: {
    name: "The Patient Warrior",
    tagline: "The Patient Warrior — Earth Tiger",
  },
  atAGlance: {
      "element": "Earth (Stability, Endurance)",
      "energy": "Yang",
      "archetype": "The Patient Warrior",
      "coreStrength": "Grounded courage",
      "shadow": "Stubborn righteousness",
      "bestMatch": "fire-horse",
      "worstMatch": "water-monkey",
      "luckyColor": "Terracotta"
  },
  personality: {
    body: "The Earth Tiger is a paradox wrapped in pragmatism — a warrior who measures twice and strikes once. Where other Tigers leap without looking, you calculate the jump. Earth transforms the Tiger's raw volatility into something formidable: courage with a foundation. You don't just charge into battle; you build the fortifications first. This makes you the rarest type of leader — one who combines vision with the patience to execute it properly.\n\nYour Yang energy pushes outward, but Earth channels it through bedrock instead of wildfire. You're protective without being possessive, ambitious without being reckless. When others panic, you dig in. When chaos erupts, you become the immovable center. This isn't passivity — it's strategic endurance. You understand that true strength isn't about never falling; it's about being too heavy to stay down. People sense this. They gravitate toward your stability even when they can't articulate why.\n\nEarth grounds the Tiger's hunting instinct into something more sustainable: building. You create systems, establish territories, cultivate loyalty. Unlike Fire Tigers who burn bright and fast, you're playing a longer game. You'll spend years on a project others abandon in months. This makes you exceptional at turning visions into institutions — the entrepreneur who actually scales the business, the activist who builds the movement infrastructure, the artist who develops a lasting body of work.\n\nBut Earth's nurturing quality softens your edges just enough to make you approachable. You're fierce, yes, but you're also the one who remembers to feed people during the revolution. You fight for those weaker than yourself not out of ego but because Earth naturally supports what grows upon it. Your protection has weight behind it.",
  },
  shadow: {
    body: "Your greatest weakness is confusing stubbornness with strength. Earth's immovability becomes concrete thinking — you dig trenches and refuse to leave them even when the battlefield has shifted. You can be so committed to your way that you miss better paths entirely. This manifests as self-righteous inflexibility: you know the right way to do things, and anyone who disagrees is simply wrong.\n\nEarth's controlling relationship with Water means you instinctively suppress flow and adaptability, both in yourself and others. You can become the authoritarian who mistakes rigidity for leadership, demanding loyalty while offering no room for dissent. Your nurturing turns into smothering — you protect people from consequences until they never learn to stand on their own.\n\nWhen unbalanced, you hoard. Resources, grudges, control. Earth accumulates, but without Metal to cut through and refine, you just pile up weight. You'll stay in dead relationships, failing projects, and outdated beliefs simply because you've invested too much to walk away. Sunk cost becomes your prison. Your endurance curdles into martyrdom — look how much I've suffered, look how long I've stayed.",
  },
  relationships: {
    body: "You need partners who respect your pace without exploiting your loyalty. You're not a casual dater; you're assessing foundation material from date one. This intensity can overwhelm lighter elements, but it also means when you commit, you're all in. You show love through provision and protection — practical acts over flowery words.\n\nThe problem: you can mistake dependence for devotion. Earth's nurturing impulse makes you attractive to those seeking a parent rather than a partner. You'll carry people who should be walking on their own, then resent them for the weight. You need someone who challenges your fixed positions without triggering your defensive walls — not easy to find.\n\nIn friendship, you're the reliable one, but you keep score without admitting it. You remember every favor, every slight, every time you showed up and they didn't. This builds walls of resentment you never directly address because confrontation feels unstable. You'd rather endure than risk the relationship — until you can't anymore, and then you cut people off with shocking finality. Learn to voice discontent before it fossilizes.",
  },
  elementBalance: {
    body: "Generate Metal through your Earth: create boundaries, not just barriers. Practice pruning — relationships, commitments, beliefs that no longer serve. Schedule regular purges of physical space; the external clearing trains internal discernment.\n\nPrevent Water stagnation by building intentional flow into your routine. Weekly experiments with something new. Monthly schedule shake-ups. You need structure, but rigid structure becomes a dam. Let Earth be fertile ground, not dried clay.\n\nPhysical practice is non-negotiable: martial arts, weightlifting, rock climbing. Activities where your body learns that strength and flexibility coexist. Earth Tigers who don't move become immobile in every sense.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Fire generates Earth — their passion fuels your endurance, your stability gives their wildness a home to return to"
          },
          {
              "slug": "metal-dog",
              "name": "Metal Dog",
              "reason": "Earth generates Metal — you provide the foundation for their principles, they refine your stubbornness into integrity"
          },
          {
              "slug": "earth-pig",
              "name": "Earth Pig",
              "reason": "Shared Earth element creates mutual understanding of loyalty and patience without power struggles"
          }
      ],
      "worst": [
          {
              "slug": "water-monkey",
              "name": "Water Monkey",
              "reason": "Earth controls Water — you'll try to dam their flow, they'll erode your foundations through constant change"
          },
          {
              "slug": "wood-snake",
              "name": "Wood Snake",
              "reason": "Wood controls Earth — their flexibility undermines your need for stability, you stifle their growth with demands"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal drains Earth — their relentless criticism exhausts your patience, you feel constantly refined away to nothing"
          }
      ]
  },
}

export default content
