// ============================================
// FIRE DOG (丙戌) — The Fierce Protector
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'fire-dog',
  profile: getProfileBySlug('fire-dog')!,
  archetype: {
    name: "The Fierce Protector",
    tagline: "The Fierce Protector — Fire Dog",
  },
  atAGlance: {
      "element": "Fire (Passion, Transformation)",
      "energy": "Yang",
      "archetype": "The Fierce Protector",
      "coreStrength": "Fearless loyalty",
      "shadow": "Reactive aggression",
      "bestMatch": "earth-horse",
      "worstMatch": "water-dragon",
      "luckyColor": "Crimson"
  },
  personality: {
    body: "The Fire Dog burns with an intensity that makes passive observers uncomfortable. You don't just protect—you actively scan for threats, real or imagined, with a vigilance that never sleeps. Fire amplifies the Dog's natural loyalty into something almost militaristic: you establish perimeters around the people and principles you love, and heaven help anyone who crosses them. Where other Dogs might bark warnings, you're already moving to intercept.\n\nYour passion isn't romantic or abstract—it's tactical. You feel things as calls to action. An injustice isn't something to discuss; it's a fire to extinguish immediately. This makes you the person others want in a crisis: decisive, brave, unburdened by overthinking. You trust your gut because your gut is connected directly to your motor neurons. The Fire element transforms the Dog's cautious nature into something more assertive, even aggressive when circumstances demand it.\n\nBut this same intensity creates problems in peacetime. You struggle with stillness because Fire needs fuel, and without a clear enemy or mission, you'll manufacture conflict to feel purposeful. You pick fights over principles that others see as negotiable. Your standards are absolute, and you communicate them with a bluntness that can scorch relationships. You're not trying to be cruel—you genuinely believe that clarity is kindness, that people need to know exactly where they stand.\n\nThe transformation aspect of Fire manifests in your ability to catalyze change in others. You don't just defend your pack—you push them to be stronger, braver, better. You're the friend who refuses to enable weakness, the colleague who calls out mediocrity, the partner who demands growth. This makes you simultaneously inspiring and exhausting. People admire your conviction but can't always sustain your temperature.",
  },
  shadow: {
    body: "Your reactivity is your Achilles heel. Fire makes you respond before thinking, and Dog makes you assume the worst about people's intentions. This combination creates a hair-trigger defensiveness where you attack perceived threats that don't actually exist. You escalate minor disagreements into full-scale confrontations because you can't modulate your response—everything feels like a battle for survival.\n\nYour righteousness becomes tyranny. You're so certain of your moral compass that you stop listening to feedback. Anyone who disagrees isn't wrong—they're compromised, weak, or corrupt. This absolutism isolates you, creating the very abandonment you fear most. You push away allies by demanding they meet standards you yourself can't consistently maintain.\n\nThe Fire element's destructive cycle means you consume resources—emotional, social, relational—faster than you can replenish them. You burn through friendships by being too intense, through jobs by being too confrontational, through your own energy reserves by refusing to rest. You wear exhaustion as a badge of honor, mistaking depletion for dedication.",
  },
  relationships: {
    body: "You need partners who can handle heat without getting burned. Someone too sensitive will wilt under your intensity; someone too passive will frustrate you into contempt. You're loyal to a fault, but that loyalty comes with expectations: you demand honesty, courage, and unwavering commitment in return. Betrayal—even small breaches of trust—triggers a scorched-earth response you can't always control.\n\nIn relationships, you're the guardian at the gate. You protect your partner fiercely, sometimes too fiercely, reading threats into innocent interactions. Jealousy isn't your issue—vigilance is. You need to know your person is safe, which can translate into controlling behavior if you're not self-aware. Your ideal match understands this comes from love, not possession, and can gently redirect your protective instincts without triggering your defensiveness.\n\nYou show love through action and expect the same. Words without follow-through enrage you. You need someone who matches your intensity with stability, your fire with earth—grounded enough to absorb your heat, present enough to reassure your anxious loyalty.",
  },
  elementBalance: {
    body: "Feed Earth to contain your Fire. Engage in activities that produce tangible results: building, creating, organizing physical spaces. This channels your intensity into construction rather than destruction. Spend time in nature—literally touching earth—to ground your reactive energy.\n\nControl your Metal consumption carefully. Don't over-structure your life or you'll rebel explosively. But some routine prevents you from burning out. Schedule recovery time like you'd schedule a mission.\n\nAvoid excess Water input when you're already stressed—it creates steam, not balance. Don't numb yourself with substances or entertainment when you're overwhelmed. Instead, let your Fire burn clean through physical exertion: martial arts, competitive sports, anything that satisfies your warrior instinct without causing actual harm.",
  },
  matches: {
      "best": [
          {
              "slug": "earth-horse",
              "name": "Earth Horse",
              "reason": "Fire generates Earth—your passion fuels their stability while their groundedness contains your intensity without suppressing it"
          },
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Wood feeds Fire—their gentle diplomacy provides fuel for your protective instincts while tempering your aggression"
          },
          {
              "slug": "earth-pig",
              "name": "Earth Pig",
              "reason": "Fire generates Earth—your intensity creates security for their trusting nature while they teach you that not every situation is a threat"
          }
      ],
      "worst": [
          {
              "slug": "water-dragon",
              "name": "Water Dragon",
              "reason": "Water controls Fire—their fluid ambition directly opposes your rigid principles, creating constant power struggles over direction"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Fire controls Metal—you'll try to dominate their perfectionism while Metal's cutting criticism triggers your defensive rage"
          },
          {
              "slug": "water-snake",
              "name": "Water Snake",
              "reason": "Water controls Fire—their secretive strategy feels like deception to your demand for transparency, breeding mutual suspicion"
          }
      ]
  },
}

export default content
