// ============================================
// FIRE RAT (丙子) — The Blazing Opportunist
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'fire-rat',
  profile: getProfileBySlug('fire-rat')!,
  archetype: {
    name: "The Blazing Opportunist",
    tagline: "The Blazing Opportunist — Fire Rat",
  },
  atAGlance: {
      "element": "Fire (Passion, Transformation)",
      "energy": "Yang",
      "archetype": "The Blazing Opportunist",
      "coreStrength": "Charismatic hustle",
      "shadow": "Impulsive burnout",
      "bestMatch": "wood-dragon",
      "worstMatch": "water-pig",
      "luckyColor": "Crimson"
  },
  personality: {
    body: "You're the Rat who doesn't just spot opportunities—you set them on fire and ride the flames. Fire transforms the Rat's natural resourcefulness into explosive charisma. Where other Rats scheme quietly, you announce your brilliance to the room. You network with the intensity of someone who knows every conversation could change everything, because in your hands, it often does. Your enthusiasm is contagious to the point of epidemic. People follow you not because you've convinced them with logic, but because your sheer conviction makes them believe the impossible is inevitable.\n\nThe Fire element accelerates everything about the Rat archetype. Your mind moves faster, your charm burns hotter, your ambition reaches higher. You don't accumulate resources slowly—you magnetize them through force of personality. Traditional Rats are strategic hoarders; you're a strategic gambler who bets big when you sense momentum. You read social dynamics like thermal imaging, detecting who's warming up to an idea and who's cooling off before they know it themselves. This makes you exceptional at building coalitions, launching ventures, and turning skeptics into disciples.\n\nYou generate Earth in the cycle—meaning your fiery activity produces tangible results, material outcomes, stability for others. Your projects don't stay theoretical. You're the startup founder who actually ships product, the organizer who fills the venue, the friend who doesn't just talk about the road trip but books the tickets. But you control Metal, which means your passion can melt structure, override systems, and burn through boundaries that others carefully maintain. You see rules as suggestions when you're on a roll. This makes you a revolutionary when institutions need shaking up, and a liability when consistency matters more than innovation.",
  },
  shadow: {
    body: "Your worst tendency is confusing motion with progress. You chase热度 (热—heat, the Fire gone wild) instead of sustainable momentum. When a project loses its initial spark, you don't troubleshoot—you abandon it for the next shiny thing that promises that hit of excitement. You've left a trail of 70%-complete ventures because finishing requires the Earth-phase patience you actively resist. Your impulsivity masquerades as decisiveness, but real decisiveness includes considering consequences beyond the immediate thrill.\n\nYou burn through relationships by treating people like rocket fuel for your ambitions. Not maliciously—you genuinely believe your enthusiasm benefits everyone—but you don't notice when you've drained someone's energy reserves. You control Metal, destroying the very structures that could give your fire lasting form. Deadlines, budgets, commitments—you see these as creativity-killers rather than the container that prevents your Fire from becoming destructive wildfire. When criticized, you flare into defensiveness or simply move to audiences who still find you dazzling. You'd rather find new believers than address why the old ones got exhausted.",
  },
  relationships: {
    body: "You need partners who can match your intensity without competing for the spotlight—Wood types who fuel your fire while maintaining their own ground. You're intoxicating in the early stages of any relationship because you make people feel like they're part of something electric. But sustaining connection requires you to occasionally dim your brightness and actually listen, which feels like suffocation to your Fire nature.\n\nYou're loyal when people stay exciting, which is a conditional loyalty you don't quite admit to yourself. The moment someone becomes predictable, your attention wanders. You need relationships that have built-in novelty—partners who evolve, friends who challenge you, collaborators who bring fresh perspectives. Stagnation is your relationship killer. You're better with people who have their own strong elemental identity rather than those who simply reflect your light back at you. Water partners can balance you if they're deep enough not to be evaporated by your heat. Earth partners ground you but often bore you unless they have their own fire. Metal partners create explosive conflicts—you melt their structure, they cut off your oxygen.",
  },
  elementBalance: {
    body: "You need deliberate Earth-building practices to transform your Fire into lasting form. Finish one project completely before starting the next—make this a non-negotiable rule, even when it feels like death. Create external structures you can't easily burn through: public commitments, financial stakes, accountability partners who won't be charmed into giving you passes.\n\nSchedule regular Water time—literal time near water, or metaphorically, time in reflection and stillness. Not meditation necessarily, but moments where you stop generating and start receiving. Your Fire needs fuel management, not constant ignition. Sleep more than you think you need. Eat before you're starving. Your body is not an infinite energy source regardless of how your mind feels. Work with Wood people who can channel your fire productively rather than Metal people who'll just fight you for control.",
  },
  matches: {
      "best": [
          {
              "slug": "wood-dragon",
              "name": "Wood Dragon",
              "reason": "Wood feeds your Fire perfectly—they fuel your vision with growth energy while having enough confidence not to be overshadowed by your intensity"
          },
          {
              "slug": "wood-monkey",
              "name": "Wood Monkey",
              "reason": "Their clever adaptability and your charismatic hustle create unstoppable momentum—both fast-moving yang energies that innovate rather than stagnate"
          },
          {
              "slug": "earth-ox",
              "name": "Earth Ox",
              "reason": "You generate Earth, they stabilize it—your fire produces results they can structure into lasting achievement, grounding your chaos productively"
          }
      ],
      "worst": [
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Water controls Fire in the cycle—their emotional depth and need for harmony directly extinguishes your passionate intensity, leaving both frustrated"
          },
          {
              "slug": "water-rat",
              "name": "Water Rat",
              "reason": "Same animal, opposing elements—they're strategic and patient where you're impulsive and bold, each thinking the other is doing Rat wrong"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Your Fire melts their Metal structure—you see their systems as restrictive, they see your spontaneity as reckless, constant elemental warfare"
          }
      ]
  },
}

export default content
