// ============================================
// FIRE DRAGON (丙辰) — The Celestial Blaze
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'fire-dragon',
  profile: getProfileBySlug('fire-dragon')!,
  archetype: {
    name: "The Celestial Blaze",
    tagline: "The Celestial Blaze — Fire Dragon",
  },
  atAGlance: {
      "element": "Fire (Passion, Transformation, Radiance)",
      "energy": "Yang",
      "archetype": "The Celestial Blaze",
      "coreStrength": "Magnetic charisma",
      "shadow": "Consuming intensity",
      "bestMatch": "wood-horse",
      "worstMatch": "water-pig",
      "luckyColor": "Crimson"
  },
  personality: {
    body: "You are the supernova of the zodiac cycle—double Fire energy makes you impossible to ignore and dangerous to dismiss. Where other Dragons calculate, you combust. Where they strategize, you ignite. Your presence doesn't enter rooms; it detonates them. This isn't performance or affectation—Fire Dragon energy is authentically incendiary, burning with a purity of purpose that either inspires devotion or triggers evacuation.\n\nYour charisma operates through sheer thermal force. People feel your conviction before you speak, sense your passion radiating outward like heat waves. You don't persuade through logic—you convert through intensity. When you believe in something, your enthusiasm becomes contagious, spreading faster than wildfire through dry brush. This makes you a natural revolutionary, the person who doesn't just imagine change but becomes the spark that ignites it.\n\nYet beneath the inferno lies surprising vulnerability. Fire requires fuel, and you burn through emotional resources at an unsustainable rate. Your highs reach stratospheric levels, but the crashes come hard and fast. You experience passion as total immersion—when you love, you incinerate boundaries; when you create, you consume yourself in the process. This isn't the steady Wood Dragon's growth or the reflective Water Dragon's depth. You are pure transformation, pure combustion, pure now.\n\nYour Dragon ambition gets supercharged by Fire's impatience. You want greatness and you want it immediately. Waiting feels like suffocation. Strategic patience feels like cowardice. This drives you to take risks that terrify others—launching ventures without safety nets, speaking truths that torch bridges, pursuing visions that require burning down what exists. Sometimes you're visionary. Sometimes you're reckless. Often you're both simultaneously.",
  },
  shadow: {
    body: "Your intensity doesn't just burn—it scorches everything in proximity. When challenged, you don't debate; you immolate. Your temper erupts with volcanic force, spewing damage you can't take back. Fire's destructive cycle means you control Metal—you melt boundaries, incinerate structure, reduce careful planning to ash. In conflict, you go nuclear, deploying emotional firepower wildly disproportionate to the offense.\n\nYou confuse exhaustion with weakness, pushing until you collapse. Fire cannot burn indefinitely without fuel, but you refuse to acknowledge limits until you've depleted yourself completely. This manifests as burnout masked as breakthrough, intensity mistaken for depth. You abandon projects the moment the initial flame dims, leaving behind a trail of half-consumed ambitions.\n\nYour need for constant stimulation makes you unreliable. When passion fades—and it always does—you vanish, seeking the next source of ignition. People become fuel for your fire rather than individuals with their own needs. You promise forever in moments of intensity, then ghost when the heat dissipates. This isn't malicious—Fire simply cannot sustain itself on yesterday's passion.",
  },
  relationships: {
    body: "You love like a wildfire—all-consuming, thrilling, potentially devastating. When you're in, you're completely in, offering a level of passion and presence that feels transcendent. Your partners get the full force of your attention, your desire, your belief in the relationship's destiny. This intensity creates powerful bonds quickly, but sustainability requires more than combustion.\n\nYou need partners who can withstand heat without getting burned. Watery types either extinguish your fire or get evaporated by it—the constant emotional processing drains your flame. Earth signs can provide grounding, but you often perceive their stability as stagnation. Wood feeds your fire beautifully, particularly Wood Horse's equally wild energy or Wood Tiger's adventurous spirit.\n\nYour relationships fail when intensity becomes intimidation. You demand that partners match your passion level constantly, creating exhaustion. You interpret normal relationship rhythms—periods of quiet, individual space, mundane routine—as rejection or decline. Learning that love can glow steadily rather than always blazing transforms your connections from spectacular burnouts to sustainable warmth.",
  },
  elementBalance: {
    body: "Balance Fire by deliberately cultivating Earth—commit to completing one project before starting three new ones. Earth is Fire's natural output in the generative cycle; channel your combustion into concrete results rather than dispersed heat. Set arbitrary timelines for sustaining effort past the initial excitement phase.\n\nPractice controlled burns. Schedule intense bursts of activity followed by mandatory rest periods. Fire needs oxygen to burn; rest isn't weakness, it's fuel management. Engage with Water element through reflection without letting it extinguish you—journaling, quiet mornings, activities that require stillness without demanding complete emotional submersion.\n\nSurround yourself with Wood—people, environments, activities that feed your flame sustainably rather than explosive accelerants. Avoid Metal's rigid structure that makes you want to melt everything, and recognize when your Fire is controlling Metal destructively—when you're burning through boundaries that actually serve you.",
  },
  matches: {
      "best": [
          {
              "slug": "wood-horse",
              "name": "Wood Horse",
              "reason": "Wood feeds Fire perfectly—their adventurous growth energy fuels your blaze without getting consumed"
          },
          {
              "slug": "wood-tiger",
              "name": "Wood Tiger",
              "reason": "Mutual intensity and courage—Wood's expansion meets Fire's transformation in exhilarating synergy"
          },
          {
              "slug": "earth-rooster",
              "name": "Earth Rooster",
              "reason": "Fire generates Earth—your passion creates their stability, their grounding contains your flame productively"
          }
      ],
      "worst": [
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Water controls Fire directly—their emotional depth and need for peace extinguishes your essential nature"
          },
          {
              "slug": "water-dog",
              "name": "Water Dog",
              "reason": "Constant conflict between your explosive intensity and their need for emotional security and loyalty rituals"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Fire melts Metal—your passionate chaos destroys their rigid structure, creating mutual frustration"
          }
      ]
  },
}

export default content
