// ============================================
// FIRE RABBIT (丙卯) — The Radiant Diplomat
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'fire-rabbit',
  profile: getProfileBySlug('fire-rabbit')!,
  archetype: {
    name: "The Radiant Diplomat",
    tagline: "The Radiant Diplomat — Fire Rabbit",
  },
  atAGlance: {
      "element": "Fire (Passion, Transformation)",
      "energy": "Yin",
      "archetype": "The Radiant Diplomat",
      "coreStrength": "Charismatic grace",
      "shadow": "Performative peacekeeping",
      "bestMatch": "wood-goat",
      "worstMatch": "water-rooster",
      "luckyColor": "Coral"
  },
  personality: {
    body: "The Fire Rabbit is charm weaponized for good. Where typical Rabbits withdraw into cautious observation, Fire propels them forward with magnetic warmth that draws others into their orbit. They possess an uncanny ability to make every interaction feel significant—not through grand gestures, but through focused attention that makes people feel genuinely seen. This isn't manipulation; it's Fire's transformative energy filtering through Rabbit's innate sensitivity to social dynamics.\n\nTheir diplomatic skill comes from reading emotional temperature with precision. They sense when a conversation needs lightening, when silence would be strategic, when to deploy humor as social lubricant. Fire gives them courage to engage where other Rabbits might flee, but they retain the species' preference for harmony over conflict. The result: someone who can navigate hostile rooms and emerge with new allies, who defuses tension not by avoiding it but by redirecting energy toward connection.\n\nThey excel in roles requiring relationship cultivation—not the transactional networking of the Snake, but genuine bridge-building. Fire Rabbits create communities around shared values, host gatherings that feel effortless but are actually choreographed for maximum connection, and remember the small details that make people feel valued. Their creativity burns bright in collaborative environments where their ideas can spark others into action.\n\nYet beneath the warmth lies strategic calculation. They know exactly which stories to share, which vulnerabilities to display for maximum relatability. Fire's passion manifests not as volatility but as sustained enthusiasm for people and projects they deem worthy. When they commit, they bring infectious energy that elevates everyone around them. They're the friend who remembers your anxiety about the presentation and texts you encouragement, the colleague who notices you're overwhelmed and redistributes tasks without being asked.",
  },
  shadow: {
    body: "Fire Rabbits can become addicted to being liked, morphing into whoever the room needs rather than asserting authentic positions. They avoid necessary confrontation by smoothing over legitimate grievances, prioritizing surface harmony over substantive resolution. This creates relationships built on performance rather than truth—exhausting for them, ultimately hollow for others.\n\nTheir diplomatic skills can devolve into manipulation when stressed. They learn which emotional buttons to push, which stories generate sympathy, how to position themselves as perpetual victims or heroes depending on the audience. Fire's transformative power becomes corrosive when used to rewrite narratives in their favor, burning away inconvenient truths.\n\nThey struggle with directness, wrapping criticism in so many compliments that the actual message disappears. This isn't kindness—it's conflict avoidance that leaves problems festering. Their need for approval can drive them to overcommit, saying yes to everything until they're spread so thin that nobody receives their full attention. The warmth that once felt genuine starts reading as performative, their careful attentiveness as calculated rather than caring.",
  },
  relationships: {
    body: "Fire Rabbits need partners who appreciate their warmth but won't exploit their conflict-averse nature. They thrive with people who create safe space for authenticity—who explicitly ask what they actually want rather than accepting their reflexive accommodation. They need relationships with enough friction to prevent stagnation but not so much that they retreat into people-pleasing.\n\nThey show love through attentive presence and thoughtful gestures calibrated to each person's preferences. But they need partners willing to call out their avoidance patterns, who won't let them deflect serious conversations with charm. Their ideal match appreciates their social gifts without demanding constant performance.\n\nIn friendship, they're loyal but can become resentful when always playing the harmonizer role. They need friends who reciprocate emotional labor and who notice when they're overextending. They bond through shared experiences and deep conversations, not superficial socializing. Fire Rabbits invest heavily in their inner circle, sometimes to the point of neglecting their own needs—they require people who actively check in on their wellbeing rather than assuming perpetual availability.",
  },
  elementBalance: {
    body: "Fire Rabbits must practice strategic withdrawal before exhaustion forces it. Schedule non-negotiable alone time to shed the social persona and reconnect with unfiltered preferences. Engage with Water element—literal water immersion, reflective practices—to cool Fire's compulsion toward constant engagement and soothe Rabbit's nervous system.\n\nCultivate Earth element through grounding routines that don't depend on external validation. Physical practices with measurable progress—strength training, pottery, gardening—help anchor identity in concrete capability rather than social perception. Say one difficult truth per week, starting small, to build tolerance for necessary discomfort. Fire generates Earth in the cycle—channel that passion into creating stable structures that support rather than just inspire.",
  },
  matches: {
      "best": [
          {
              "slug": "wood-goat",
              "name": "Wood Goat",
              "reason": "Wood feeds Fire while Goat's creativity and emotional depth give Rabbit authentic connection beyond performance"
          },
          {
              "slug": "wood-pig",
              "name": "Wood Pig",
              "reason": "Wood nourishes Fire; Pig's sincerity and generosity create safe space for Rabbit to drop diplomatic masks"
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Fire generates Earth; Dog's loyalty and directness balance Rabbit's avoidance with necessary groundedness"
          }
      ],
      "worst": [
          {
              "slug": "water-rooster",
              "name": "Water Rooster",
              "reason": "Water extinguishes Fire; Rooster's blunt criticism and need for precision clash with Rabbit's indirect harmony-seeking"
          },
          {
              "slug": "water-rat",
              "name": "Water Rat",
              "reason": "Water controls Fire; Rat's opportunism and emotional guardedness trigger Rabbit's people-pleasing without reciprocation"
          },
          {
              "slug": "metal-dragon",
              "name": "Metal Dragon",
              "reason": "Fire controls Metal but Dragon's dominance and spotlight-seeking leave no room for Rabbit's subtle influence style"
          }
      ]
  },
}

export default content
