// ============================================
// FIRE SNAKE (丙巳) — The Mesmerizing Flame
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'fire-snake',
  profile: getProfileBySlug('fire-snake')!,
  archetype: {
    name: "The Mesmerizing Flame",
    tagline: "The Mesmerizing Flame — Fire Snake",
  },
  atAGlance: {
      "element": "Fire (Passion, Transformation, Radiance)",
      "energy": "Yin",
      "archetype": "The Mesmerizing Flame",
      "coreStrength": "Magnetic intensity",
      "shadow": "Scorched-earth vengeance",
      "bestMatch": "metal-rooster",
      "worstMatch": "water-pig",
      "luckyColor": "Crimson"
  },
  personality: {
    body: "You burn with calculated intensity. Where other Fire types blaze openly, you smolder—yin Fire's contained heat creating pressure that either forges diamonds or incinerates everything nearby. You possess the Snake's natural magnetism amplified by Fire's transformative power, making you irresistible and slightly dangerous. People feel compelled to circle closer even when they sense the heat.\n\nYour intelligence operates like a laser, not a floodlight. You focus obsessively on what captures your interest, boring through problems others find impenetrable. This isn't the Wood Snake's patient strategy or the Metal Snake's cold precision—you consume information with passionate intensity, transforming raw data into weaponized insight. You see people's motivations with uncomfortable clarity because Fire illuminates and Snake penetrates. This combination makes you exceptional at influence, persuasion, and knowing exactly which words will reshape someone's reality.\n\nThe Fire element generates Earth in the productive cycle, meaning your passion naturally produces tangible results. You don't just dream—you manifest. But you manifest selectively, only for objectives worthy of your concentrated flame. Mediocre goals bore you. You need pursuits that justify the fuel you'll burn, projects that transform rather than merely succeed. When properly directed, you create lasting impact through sheer force of focused will.\n\nYour yin nature creates paradox: publicly charismatic yet privately selective, socially skilled yet emotionally guarded. You reveal exactly what serves your purpose while keeping your true depths hidden. Fire wants expression; Snake wants control. The result is someone who performs vulnerability strategically, shares selectively, and maintains mystery even in apparent intimacy. People think they know you. They don't.",
  },
  shadow: {
    body: "Your Fire controls Metal in the destructive cycle—you melt boundaries, structures, and anyone who opposes you. When threatened or betrayed, you don't forgive; you eliminate. The Snake's capacity for grudges combined with Fire's transformative power creates scorched-earth vengeance. You'll burn your own territory to ash rather than let an enemy claim it. This isn't hot anger that cools—it's sustained, strategic destruction dressed as justice.\n\nYour intensity becomes tyranny when unchecked. You manipulate through charisma, using your magnetism to reshape others' realities until they can't distinguish their desires from your influence. Fire generates Earth, but excessive Fire bakes Earth into hardpan—your passion can suffocate those close to you, demanding they fuel your flame while offering heat that burns rather than warms. You justify control as care, possession as protection. You collect people like treasures, then resent their need for air.",
  },
  relationships: {
    body: "You need partners who can withstand heat without melting or fleeing. Fire generates Earth—you're naturally drawn to Earth types who ground your intensity and transform your passion into substance. But you require Metal types who maintain form in your presence, offering the structure Fire needs to avoid becoming wildfire.\n\nYou don't do casual. Every connection matters or doesn't exist—you have acquaintances and intimates, nothing between. In love, you're possessive but loyal, demanding complete honesty while rationing your own truth. You test partners constantly, creating small crises to confirm their commitment. This exhausts people who need consistent temperature.\n\nYou match best with those who appreciate intensity without feeding drama, who can say no without triggering your control mechanisms. You need someone fascinated by your depths rather than frightened, someone whose own substance doesn't depend on your approval. Water types often attract you with their mystery, but unless they're strong Water, you'll evaporate them through sheer heat.",
  },
  elementBalance: {
    body: "Your excess Fire needs deliberate cooling—not elimination, but modulation. Spend time near actual water: oceans, lakes, rain. Water controls Fire in the destructive cycle, providing necessary limits. Cultivate relationships with Water types who won't simply evaporate under your intensity.\n\nPractice releasing control in low-stakes situations. Let someone else choose the restaurant. Fire generates Earth—create tangible things with your hands: pottery, woodworking, cooking. Physical creation grounds your mental intensity. When you feel the urge to burn a bridge, write the scorched-earth letter but don't send it for three days. Your yin nature supports strategic patience; use it. Feed your Fire with worthy fuel—challenging projects, meaningful goals—so it doesn't consume relationships for entertainment.",
  },
  matches: {
      "best": [
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal provides structure Fire needs; Rooster's precision channels Snake's intensity into sustainable brilliance rather than destruction."
          },
          {
              "slug": "earth-ox",
              "name": "Earth Ox",
              "reason": "Fire generates Earth—your passion fuels their stability; Ox's immovable nature withstands your heat without submission or flight."
          },
          {
              "slug": "wood-dragon",
              "name": "Wood Dragon",
              "reason": "Wood feeds Fire sustainably; Dragon matches your intensity with expansion rather than competition, creating mutual amplification."
          }
      ],
      "worst": [
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Water controls Fire destructively here—Pig's emotional fluidity triggers your control mechanisms; you scorch their innocence, they flood your focus."
          },
          {
              "slug": "fire-tiger",
              "name": "Fire Tiger",
              "reason": "Double Fire without balance—Tiger's explosive yang clashes with your yin intensity; both demand dominance, creating combustion without creation."
          },
          {
              "slug": "water-monkey",
              "name": "Water Monkey",
              "reason": "Water extinguishes Fire; Monkey's chaos frustrates Snake's need for control; your intensity reads as threatening, their adaptability as betrayal."
          }
      ]
  },
}

export default content
