// ============================================
// FIRE PIG (丙亥) — The Warm-Hearted Champion
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'fire-pig',
  profile: getProfileBySlug('fire-pig')!,
  archetype: {
    name: "The Warm-Hearted Champion",
    tagline: "The Warm-Hearted Champion — Fire Pig",
  },
  atAGlance: {
      "element": "Fire (Passion, Transformation, Radiance)",
      "energy": "Yin",
      "archetype": "The Warm-Hearted Champion",
      "coreStrength": "Generous enthusiasm",
      "shadow": "Reckless overextension",
      "bestMatch": "earth-goat",
      "worstMatch": "water-snake",
      "luckyColor": "Coral"
  },
  personality: {
    body: "The Fire Pig burns with a generous intensity that draws people like moths to a welcoming flame. You don't just feel emotions—you broadcast them at full volume, turning private sentiment into public celebration. Where other Pigs enjoy quiet comfort, you need an audience for your affection. Your Fire element transforms the Pig's natural generosity into something performative and magnetic. You throw parties that become legendary, champion causes with evangelical fervor, and love with a demonstrative warmth that can feel overwhelming to more reserved types.\n\nYour approach to life combines the Pig's appetite for pleasure with Fire's need for significance. You don't just want good food—you want the dinner that everyone remembers and talks about for years. You don't just help friends—you orchestrate dramatic rescues and grand gestures. This makes you inspiring but exhausting, beloved but occasionally smothering. You genuinely want everyone to be happy, but your method involves turning up the heat until everyone's as excited as you are.\n\nUnlike Metal Pigs who build systems or Water Pigs who flow around obstacles, you attack life head-on with passionate conviction. When you believe in something, you become its most vocal advocate, sometimes before fully understanding what you're advocating for. Your Fire element generates Earth—you stabilize others through your warm presence, creating environments where people feel safe to be vulnerable. But this same heat can scorch when you push too hard, demanding emotional reciprocity that others aren't ready to give. You're at your best when your natural kindness gets amplified by Fire's courage, standing up for the vulnerable with both heart and heat.",
  },
  shadow: {
    body: "Your Fire burns through resources—emotional, financial, physical—with alarming speed. You overcommit spectacularly, promising attendance at five events in one evening because you can't bear to disappoint anyone. Then you show up to none, exhausted and guilt-ridden. Your generous impulses become reckless when Fire removes the Pig's natural caution. You loan money you don't have, defend people who've betrayed you repeatedly, and stay in situations that drain you because walking away feels like abandoning your warmth.\n\nWhen your Fire element controls Metal (structure, boundaries), you melt down every fence meant to protect you. You interpret healthy limits as coldness, seeing any 'no' as rejection rather than self-preservation. Your shadow emerges as emotional volatility masked as passion—dramatic outbursts followed by equally dramatic apologies, burning bridges then desperately trying to rebuild them. You can become the friend who makes every gathering about their crisis, the partner whose love feels like an obligation rather than a gift. Your worst tendency is confusing intensity with intimacy, mistaking drama for depth.",
  },
  relationships: {
    body: "You love loudly and expect to be loved the same way. Quiet devotion confuses you—you need words, gestures, public declarations. This makes you generous with affection but demanding of validation. You're the partner who plans elaborate surprises and feels devastated when they're met with anything less than tears of joy. Your Fire element craves recognition for your warmth, which paradoxically makes your giving feel conditional.\n\nYou need partners who can match your enthusiasm without competing with it—Earth signs who receive your heat and transform it into something stable work well. Wood types appreciate your passion but may feel scorched by your intensity. You struggle with Water signs who dampen your flames with caution, and Metal types whose boundaries feel like rejection. Your best relationships involve people who let you be big and warm without requiring them to be equally loud, who understand that your dramatic expressions come from genuine feeling, not manipulation. You must learn that love can be quiet, that being cherished doesn't always look like being celebrated.",
  },
  elementBalance: {
    body: "Your Fire needs containment, not extinguishing. Build Earth through routine—commit to one cause instead of twelve, show up consistently rather than dramatically. Practice giving without announcement; let some kindness go unwitnessed. When you feel the urge to make grand gestures, do three small ones instead. Balance your outward heat with inward reflection: journal before you post, sit with feelings before broadcasting them.\n\nDevelop relationship with Metal element through boundaries: say no to one request daily, even minor ones. Notice how structures support rather than suffocate your warmth. Let others initiate sometimes. Your Fire generates Earth naturally when properly directed—channel passion into sustained action rather than spectacular burnout. Cook meals, tend gardens, build things slowly. Accept that not every emotion requires immediate expression or audience participation.",
  },
  matches: {
      "best": [
          {
              "slug": "earth-goat",
              "name": "Earth Goat",
              "reason": "Your Fire generates their Earth, creating stable warmth where creativity and compassion build something lasting together"
          },
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Wood feeds your Fire while Rabbit's diplomacy channels your passion into graceful action rather than chaos"
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Your shared loyalty combines with productive cycle—your Fire generates their Earth into unshakeable devotion"
          }
      ],
      "worst": [
          {
              "slug": "water-snake",
              "name": "Water Snake",
              "reason": "Water controls Fire in destructive cycle—their calculated coldness extinguishes your generous warmth into resentful smoke"
          },
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "Your Fire destroys their Metal structure while their cleverness manipulates your generous nature into exhaustion"
          },
          {
              "slug": "water-rat",
              "name": "Water Rat",
              "reason": "Water dampens Fire—their cautious accumulation clashes with your reckless generosity, creating mutual frustration"
          }
      ]
  },
}

export default content
