// ============================================
// FIRE HORSE (丙午) — The Untamable Spirit
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'fire-horse',
  profile: getProfileBySlug('fire-horse')!,
  archetype: {
    name: "The Untamable Spirit",
    tagline: "The Untamable Spirit — Fire Horse",
  },
  atAGlance: {
      "element": "Fire (Passion, Transformation)",
      "energy": "Yang",
      "archetype": "The Untamable Spirit",
      "coreStrength": "Fearless authenticity",
      "shadow": "Explosive volatility",
      "bestMatch": "earth-goat",
      "worstMatch": "water-pig",
      "luckyColor": "Crimson"
  },
  personality: {
    body: "You are fire doubled — the Horse's wild independence amplified by Fire's relentless drive. Where other signs calculate or defer, you charge forward on pure instinct and conviction. You don't enter rooms, you ignite them. Your presence is magnetic not because you seek attention, but because you refuse to dim your flame for anyone's comfort. People either gravitate toward your heat or retreat from it. You have no patience for the middle ground.\n\nYour passion isn't decorative — it's functional. You commit completely or not at all. When you believe in something, you become an unstoppable force, burning through obstacles with sheer intensity. This makes you exceptional in crisis, where others freeze and you accelerate. You trust your gut with absolute faith, and more often than not, that instinct proves sound. Your energy is contagious; you inspire others simply by refusing to compromise your vision.\n\nBut Fire Horse energy demands constant movement. Stagnation feels like suffocation. You need challenges that match your intensity, work that lets you run at full speed, relationships that don't try to leash you. Routine is your enemy. You'll abandon security for freedom without hesitation, which makes you simultaneously exhilarating and exhausting to be around. You value honesty over harmony — you'd rather have a brutal truth than a comfortable lie. This directness can wound, but you see it as respect. Why waste time on pretense?\n\nYour greatest gift is showing others what unfiltered authenticity looks like. In a world of calculated personas, you are defiantly, sometimes recklessly, yourself.",
  },
  shadow: {
    body: "Fire out of control becomes wildfire. Your intensity tips into volatility when you're not careful. You explode when frustrated, saying things designed to scorch, then wonder why people keep their distance. Your inability to moderate means you burn through relationships, jobs, and opportunities because you can't dial it down even when strategy demands it.\n\nYou mistake stubbornness for integrity. Once you've decided, you become immovable, even when evidence suggests you're wrong. Your instinct is so powerful you've stopped questioning it, but instinct without reflection is just impulse. You confuse boredom with intuition — just because something feels stale doesn't mean it's wrong. Sometimes the answer is commitment, not escape.\n\nYou drain people. Not everyone can match your pace, and you interpret their exhaustion as weakness or lack of passion. You demand others burn as bright as you, then feel betrayed when they prioritize sustainability over intensity. Your need for constant stimulation makes you restless, always chasing the next peak, never learning to value the plateau.",
  },
  relationships: {
    body: "You need partners who can handle heat without trying to extinguish it. The worst thing someone can do is attempt to tame you — you'll bolt immediately. You're drawn to people who match your intensity or provide grounding without constraint. Passion is non-negotiable; you'd rather be alone than in a lukewarm connection.\n\nYou're fiercely loyal when respected, but loyalty doesn't mean obedience. You need autonomy within intimacy, space to run even when committed. Your honesty can be brutal — you say what others think but won't voice. This creates either deep trust or permanent damage, depending on the recipient.\n\nYour challenge is learning that not every emotional flash requires expression. Fire generates Earth in the cycle — your passion can create stability if channeled, but only if you pause between impulse and action. You need people who don't flinch at your intensity but also don't enable your worst impulses. The right partner doesn't try to control the flame; they help you build a hearth.",
  },
  elementBalance: {
    body: "Feed Earth to contain your fire. Take on projects that require sustained effort, not just explosive starts. Physical exhaustion helps — run, climb, fight until your body's spent, so your mind can rest. When anger rises, write it out before speaking it out.\n\nAvoid excess Fire inputs: cut caffeine, limit alcohol, reduce inflammatory foods. Your system is already running hot. Seek Water element activities not to extinguish but to temper — swim, sit by rivers, practice silence. Notice the difference between intuition and reactivity: intuition is clear and calm, reactivity is urgent and hot. Before major decisions, wait 24 hours. Your instincts are good, but they're better when filtered through a cooling period.",
  },
  matches: {
      "best": [
          {
              "slug": "earth-goat",
              "name": "Earth Goat",
              "reason": "Fire generates Earth — your passion creates their stability; they ground you without constraining your spirit"
          },
          {
              "slug": "wood-tiger",
              "name": "Wood Tiger",
              "reason": "Wood feeds Fire — they fuel your intensity with fresh ideas while matching your need for independence"
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Earth contains Fire productively — they provide loyal grounding while respecting your untamable nature"
          }
      ],
      "worst": [
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Water extinguishes Fire — their need for ease and comfort directly opposes your intensity and drive"
          },
          {
              "slug": "water-rat",
              "name": "Water Rat",
              "reason": "Water controls Fire — their calculated caution frustrates your instinctive action, creating constant friction"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Fire melts Metal, Metal contains Fire — mutual destruction as your chaos clashes with their rigid order"
          }
      ]
  },
}

export default content
