// ============================================
// FIRE OX (丙丑) — The Relentless Forge
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'fire-ox',
  profile: getProfileBySlug('fire-ox')!,
  archetype: {
    name: "The Relentless Forge",
    tagline: "The Relentless Forge — Fire Ox",
  },
  atAGlance: {
      "element": "Fire (Passion, Transformation, Dynamism)",
      "energy": "Yin",
      "archetype": "The Relentless Forge",
      "coreStrength": "Unstoppable Conviction",
      "shadow": "Burnout Stubbornness",
      "bestMatch": "earth-rooster",
      "worstMatch": "water-ox",
      "luckyColor": "Burnt Orange"
  },
  personality: {
    body: "The Fire Ox is a paradox wrapped in motion—steady as bedrock, burning like a wildfire. This is the person who works sixteen-hour days not from desperation but from conviction, who transforms 'I believe' into sweating, bleeding reality. Where other Fire signs flare and flicker, the Fire Ox sustains the blaze through sheer endurance. They don't just have passion; they forge it into infrastructure.\n\nFire's transformative energy collides with Ox's methodical nature to create someone who renovates entire systems from the inside out. They're activists who build organizations, entrepreneurs who actually finish products, reformers who outlast opposition through relentless output. While Water Ox waits and Metal Ox calculates, Fire Ox moves—deliberately, powerfully, leaving scorched earth behind outdated methods. They see inefficiency as a personal insult and complacency as cowardice.\n\nTheir intensity manifests physically. Fire Ox doesn't pace—they stride. Doesn't discuss—they advocate. Their presence raises room temperature through sheer conviction. They champion causes with religious fervor, but unlike airy idealists, they show up at 6am to lay foundation. This combination generates Earth: their passionate work creates tangible results, institutions that outlive them, movements that change policy.\n\nThe Yin energy grounds Fire's Yang explosiveness just enough to sustain burn rather than detonate. They're not performers seeking applause; they're committed to the Work itself with monastic devotion. They'll spend years perfecting a craft, building a business, or fighting an injustice—not for recognition but because stopping feels like betrayal. Their loyalty runs molten-deep, their standards scorchingly high, their tolerance for excuses nonexistent.",
  },
  shadow: {
    body: "Fire Ox's greatest weakness is their inability to distinguish between commitment and self-immolation. They confuse exhaustion with virtue, viewing rest as weakness and delegation as abandonment. This leads to spectacular burnouts where they collapse not from lack of will but from ignoring every physiological warning sign. They become tyrants of productivity, measuring worth in output, treating their body like an infinite resource.\n\nTheir stubbornness calcifies under Fire's heat. Where Earth Ox might eventually listen to reason, Fire Ox digs in harder when challenged, their conviction hardening into dogma. They'll defend failing strategies simply because they've invested too much to pivot, burning relationships as collateral damage. Their need to be right exceeds their need to be effective. They control Metal—meaning they can cut through obstacles—but also control people, projects, and conversations with scorching intensity that leaves no room for collaboration. Associates become either disciples or obstacles.",
  },
  relationships: {
    body: "Fire Ox loves through action, not words. They show devotion by building—renovating your house, editing your manuscript at midnight, defending your reputation like hired security. But they struggle with emotional availability, mistaking service for intimacy. They need partners who recognize that their intensity isn't aggression but misdirected care.\n\nThey require someone who can absorb Fire without being consumed—Earth signs who ground their energy into productivity, or strategic Metal signs who channel their passion precisely. Water signs often clash: Water controls Fire in the destructive cycle, leading to mutual frustration as emotional needs douse productive flames. Fire Ox interprets feelings-talk as delay tactics.\n\nIn conflict, they don't yell—they prosecutor-interrogate, building logical cases for why you're objectively wrong. They need partners secure enough to stand their ground without getting burned, who can say 'you're being unreasonable' without triggering defensive escalation. Intimacy requires them learning that vulnerability isn't weakness and that sometimes the most productive thing is doing absolutely nothing together.",
  },
  elementBalance: {
    body: "Balance Fire's consumption by deliberately generating Earth: create tangible things that exist beyond your effort. Write, build, plant—make objects that prove you can stop working and value persists. Schedule non-negotiable rest like business meetings; your Ox nature respects structure.\n\nEngage Water element through strategic retreat: take actual baths, swim, visit rivers. Water controls Fire in the cycle—let it. Practice absorbing rather than generating, listening rather than advocating. Cultivate one relationship where you're explicitly not the leader, expert, or driver. Let someone else build while you simply witness. Your tendency to generate Earth means you create constantly—balance requires intentional stillness, trusting that your worth isn't measured in output alone.",
  },
  matches: {
      "best": [
          {
              "slug": "earth-rooster",
              "name": "Earth Rooster",
              "reason": "Fire generates Earth—your passion feeds their precision, creating detailed excellence without extinguishing your drive."
          },
          {
              "slug": "earth-snake",
              "name": "Earth Snake",
              "reason": "They channel your intensity into strategic mastery, grounding transformation into lasting wisdom."
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Fire controls Metal—you soften their rigidity while they sharpen your unfocused passion into precise execution."
          }
      ],
      "worst": [
          {
              "slug": "water-ox",
              "name": "Water Ox",
              "reason": "Water controls Fire—their patient contemplation constantly douses your driven momentum, leading to mutual resentment."
          },
          {
              "slug": "water-goat",
              "name": "Water Goat",
              "reason": "Your relentless productivity clashes with their emotional fluidity; you interpret feeling as procrastination, they see you as heartless."
          },
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Double Fire with no grounding—explosive intensity burns through resources and relationships with nothing sustainable built."
          }
      ]
  },
}

export default content
