// ============================================
// FIRE GOAT (丙未) — The Passionate Creator
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'fire-goat',
  profile: getProfileBySlug('fire-goat')!,
  archetype: {
    name: "The Passionate Creator",
    tagline: "The Passionate Creator — Fire Goat",
  },
  atAGlance: {
      "element": "Fire (Passion, Transformation)",
      "energy": "Yin",
      "archetype": "The Passionate Creator",
      "coreStrength": "Expressive warmth",
      "shadow": "Emotional combustion",
      "bestMatch": "wood-rabbit",
      "worstMatch": "water-dog",
      "luckyColor": "Coral"
  },
  personality: {
    body: "The Fire Goat burns with a creative fervor that transforms artistic vision into tangible beauty. You don't just feel emotions—you broadcast them through every medium available, whether canvas, conversation, or the carefully curated aesthetic of your living space. Fire's transformative power supercharges the Goat's natural artistic sensibility, making you someone who can't help but turn the mundane into something visually or emotionally striking. Your passion isn't loud or aggressive; it's warm, inviting, and deeply personal.\n\nYou operate on genuine enthusiasm rather than cold calculation. When you care about something—a project, a person, a cause—your commitment radiates outward, drawing others into your orbit through sheer authentic heat. This isn't performance; it's combustion. The problem is you expect others to match your emotional temperature, and when they don't, you interpret their coolness as rejection or indifference. You're building fires everywhere, frustrated that not everyone wants to stand this close to the flame.\n\nYour Yin nature means this Fire doesn't explode outward like the Yang Fire signs—it glows, smolders, and occasionally flares when provoked. You need emotional security to function, but Fire's volatility makes that security hard to maintain. You create beautiful things, throw amazing gatherings, and make people feel special, but underneath there's a constant anxiety about whether you're valued, whether your contributions matter, whether anyone actually sees you. Fire generates Earth in the productive cycle—your passion naturally creates stability for others, even when you yourself feel groundless.",
  },
  shadow: {
    body: "Your emotional temperature runs so hot that minor slights become major betrayals in your internal narrative. Fire's destructive cycle controls Metal—you literally burn through boundaries, structure, and rational limits when your feelings take over. You'll make impulsive decisions based on momentary intensity, then deal with the consequences later. The Goat's natural dependency becomes dramatic under Fire: you need constant emotional validation, and when it's not forthcoming, you either withdraw into wounded silence or escalate into theatrical displays of hurt.\n\nYou manipulate through vulnerability. When direct communication fails, you'll use tears, artistic suffering, or strategic helplessness to get what you need. It works, but it exhausts everyone around you. Your generosity has strings—you give intensely, then keep score secretly, building resentment when others don't reciprocate at your level. Fire Goats who don't manage their element become emotional arsonists, burning down relationships by demanding impossible levels of devotion while offering unstable passion in return.",
  },
  relationships: {
    body: "You fall hard and fast, confusing intensity with intimacy. Fire's nature is to consume fuel, and in relationships, you can accidentally treat partners as kindling for your emotional needs rather than separate beings with their own temperature. You're capable of profound devotion, but you need someone who can handle heat without getting burned—or worse, someone who won't try to extinguish you for being 'too much.'\n\nYour ideal partner provides Wood energy—growth, flexibility, steady fuel that feeds your Fire without demanding you dim yourself. You need someone who appreciates your creativity without requiring constant drama, who can ground you without smothering you. Earth partners can work if they're stable enough to contain your flames productively. Water signs either balance you beautifully or create constant steam—depends on whether they're flowing or flooding. Metal partners often feel too rigid; you interpret their structure as criticism and respond by burning hotter, which just makes them construct more boundaries.",
  },
  elementBalance: {
    body: "Stop treating every emotion like an emergency. Fire needs fuel management—not every feeling deserves a bonfire. Create a daily practice that doesn't involve audience or validation: morning pages, solo walks, anything that lets you process heat without performing it. Add Wood energy through plants, creative projects with timelines, or literally spending time in forests. Wood feeds Fire sustainably.\n\nBuild Earth deliberately: routines, savings accounts, commitments you keep even when you don't feel like it. Your passion generates stability for others—make sure you're generating some for yourself. Reduce Metal conflict by accepting that not everyone operates on feelings, and that's not a judgment of your worth. When you feel yourself spiraling into emotional drama, ask: 'Am I responding to reality or to the story I'm telling about reality?' The answer is usually uncomfortable.",
  },
  matches: {
      "best": [
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Wood feeds your Fire sustainably while Rabbit's gentleness matches your Yin sensitivity—creative harmony without drama"
          },
          {
              "slug": "wood-pig",
              "name": "Wood Pig",
              "reason": "Generous Wood energy fuels your passion while Pig's genuine warmth meets your need for emotional security"
          },
          {
              "slug": "earth-horse",
              "name": "Earth Horse",
              "reason": "Your Fire generates their Earth; Horse's optimism matches your enthusiasm with grounded stability"
          }
      ],
      "worst": [
          {
              "slug": "water-dog",
              "name": "Water Dog",
              "reason": "Water controls Fire in destructive cycle; Dog's moral rigidity clashes with your emotional fluidity—constant steam and judgment"
          },
          {
              "slug": "water-ox",
              "name": "Water Ox",
              "reason": "Water extinguishes your flame while Ox's emotional stoicism feels like rejection of your core nature"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Your Fire attacks their Metal; Rooster's criticism ignites your defensiveness—mutual destruction through elemental conflict"
          }
      ]
  },
}

export default content
