// ============================================
// FIRE MONKEY (丙申) — The Daring Catalyst
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'fire-monkey',
  profile: getProfileBySlug('fire-monkey')!,
  archetype: {
    name: "The Daring Catalyst",
    tagline: "The Daring Catalyst — Fire Monkey",
  },
  atAGlance: {
      "element": "Fire (Passion, Transformation, Radiance)",
      "energy": "Yang",
      "archetype": "The Daring Catalyst",
      "coreStrength": "Infectious creative vision",
      "shadow": "Reckless attention-seeking",
      "bestMatch": "earth-rat",
      "worstMatch": "water-pig",
      "luckyColor": "Crimson"
  },
  personality: {
    body: "You are the spark that ignites rooms and ideas simultaneously. Fire amplifies the Monkey's natural cleverness into something electric and impossible to ignore. Where other Monkeys might scheme quietly, you scheme loudly, with theatrical flair and absolute conviction that your brilliance deserves an audience. Your mind moves like wildfire—rapid, consuming, jumping from branch to branch before anyone else has processed the first thought. You don't just solve problems; you turn solutions into performances.\n\nThis isn't shallow showmanship. Fire gives your Monkey intellect an intense forward momentum. You see possibilities others miss because you're willing to burn through conventional thinking. Your passion transforms abstract cleverness into tangible action. When you commit to something, you throw every ounce of energy into it, inspiring others through sheer force of enthusiasm. You're the person who takes a half-formed idea and turns it into a movement, not through patient nurturing but through explosive catalytic energy.\n\nThe yang-on-yang intensity makes you charismatic but exhausting. You need constant stimulation, new challenges, fresh audiences. Boredom is physically painful for you—it's Fire being smothered, Monkey caged. You thrive in crisis and innovation, moments when everyone else is paralyzed and you're operating at peak capacity. Your humor is sharp and quick, often pushing boundaries because Fire doesn't respect limits and Monkey loves testing reactions.\n\nYou generate Earth through your work—your passion creates tangible results when focused. You control Metal by melting rigid structures, challenging authority with charm and audacity rather than direct confrontation. But this means you sometimes destroy without building, burn through resources (including people) without considering the ashes left behind.",
  },
  shadow: {
    body: "Your need for attention becomes desperate when unchecked. You escalate situations just to remain the center of focus, turning everything into drama. Fire Monkey's shadow is the performer who can't exit the stage, the innovator who sabotages their own projects once the initial excitement fades. You burn through relationships by demanding constant validation, interpreting anything less than enthusiasm as rejection.\n\nImpulsiveness becomes destructive when Fire overrides Monkey's usually sharp judgment. You commit to ventures without planning, chase novelty over substance, abandon projects the moment they require sustained effort rather than inspired bursts. Your cleverness turns manipulative—you use charm to avoid accountability, reframe your chaos as creativity. The worst version of you is all flash and no foundation, leaving scorched earth and broken promises while insisting you were just being spontaneous and authentic. You mock anything slow or careful as boring, unable to recognize that not all growth happens at fire speed.",
  },
  relationships: {
    body: "You need partners who can match your energy without competing for the spotlight. Earth signs provide the stability you won't create for yourself—they ground your Fire, give your ideas form, don't extinguish your passion but channel it. You're attracted to intensity but easily bored by consistency, which creates a painful pattern of pursuit and abandonment.\n\nIn love, you're passionate and generous but unreliable. You shower attention in explosive bursts then disappear into your next obsession. You need someone who understands that your affection is genuine even when inconsistent, who can call you on your drama without making it about control. You respect people who aren't dazzled by your performance, who see through the cleverness to the underlying insecurity.\n\nFriendships work best when there's mutual inspiration and space. You're loyal when genuinely connected but ruthless about cutting ties when relationships feel obligatory. You need friends who challenge you intellectually, who can keep up with your rapid pivots, who don't take your provocations personally.",
  },
  elementBalance: {
    body: "Stop performing for one hour daily. Sit with boredom instead of fleeing it—Fire needs containment to avoid burnout. Practice finishing what you start; completion generates Earth, giving your brilliance lasting form. Engage with Water element deliberately: listen more than you speak in at least one conversation per day, feel emotions rather than dramatizing them. Spend time with Metal types who value precision; their structure will irritate you but refine your scattered energy. Create with your hands—physical making slows Fire's racing mind while still expressing passion. When you feel the urge to escalate for attention, pause and ask whether you're genuinely excited or just afraid of being forgotten.",
  },
  matches: {
      "best": [
          {
              "slug": "earth-rat",
              "name": "Earth Rat",
              "reason": "Fire generates Earth; Rat's resourcefulness gives your visions stable form and practical pathways"
          },
          {
              "slug": "wood-dragon",
              "name": "Wood Dragon",
              "reason": "Wood feeds Fire; Dragon matches your yang intensity with flexible confidence and shared appetite for the extraordinary"
          },
          {
              "slug": "earth-snake",
              "name": "Earth Snake",
              "reason": "Fire generates Earth; Snake's strategic depth channels your impulsiveness into calculated brilliance without dampening passion"
          }
      ],
      "worst": [
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Water controls Fire; Pig's emotional sincerity drowns your theatrical energy, you read their depth as criticism of your performance"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Fire controls Metal but at cost; Rooster's precision clashes with your chaos, mutual frustration as they demand what you can't sustain"
          },
          {
              "slug": "water-tiger",
              "name": "Water Tiger",
              "reason": "Water controls Fire; both yang but incompatible—Tiger's deep courage exposes your surface flash, you exhaust each other competing"
          }
      ]
  },
}

export default content
