// ============================================
// METAL DRAGON (庚辰) — The Iron Emperor
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'metal-dragon',
  profile: getProfileBySlug('metal-dragon')!,
  archetype: {
    name: "The Iron Emperor",
    tagline: "The Iron Emperor — Metal Dragon",
  },
  atAGlance: {
      "element": "Metal (Precision, Structure, Refinement)",
      "energy": "Yang",
      "archetype": "The Iron Emperor",
      "coreStrength": "Unyielding Authority",
      "shadow": "Inflexible Perfectionism",
      "bestMatch": "water-rat",
      "worstMatch": "fire-horse",
      "luckyColor": "Platinum White"
  },
  personality: {
    body: "The Metal Dragon is the zodiac's most formidable force—a being of absolute conviction wrapped in diamond-hard resolve. Metal sharpens the Dragon's natural authority into something surgical and precise. Where other Dragons rely on charisma or spectacle, you command through sheer competence and unwavering standards. You don't just set the bar; you are the bar. Your presence doesn't ask for respect—it demands it through demonstrated excellence.\n\nYou operate with architectural thinking. Every decision gets scrutinized through multiple frameworks. Every plan has contingencies. You see the structural flaws in systems others consider functional, and you can't rest until you've redesigned them correctly. This makes you exceptional in crisis—while others panic, you're already three moves ahead, implementing solutions with military efficiency. Your Yang energy combined with Metal's consolidating force means you don't just lead; you forge empires.\n\nBut this is no warm-hearted monarch. Metal Dragon energy is autumn's blade—beautiful, sharp, uncompromising. You have little patience for emotional reasoning or subjective interpretations. Facts are facts. Standards exist for reasons. Mediocrity offends you at a cellular level. You'll dismantle someone's entire argument with a single well-placed observation, and you won't soften the blow. Your loyalty is absolute, but it must be earned through demonstrated integrity and capability.\n\nYou generate Water in the elemental cycle—meaning your precision and clarity create flow and wisdom in others. The best people around you become sharper, more focused, more capable. You control Wood, which manifests as an ability to prune chaos and redirect growth. When organizations need restructuring or visions need refining, you're the surgeon they call. Your gift is transformation through elimination—cutting away everything that doesn't serve the highest standard.",
  },
  shadow: {
    body: "Your shadow is the tyrant who mistakes rigidity for strength. When unbalanced, you become so attached to your vision of perfection that you destroy anything that deviates from it—including relationships, opportunities, and your own wellbeing. You stop accepting input and start demanding compliance. Metal's cutting nature turns from precision to cruelty. You'll deliver devastating critiques that leave others feeling worthless, and you'll justify it as 'honesty.'\n\nYour inability to bend creates brittleness. Where flexibility would preserve the relationship or project, you snap it instead. You'd rather be right than connected. You'd rather maintain standards than maintain partnerships. The Dragon's pride combines with Metal's judgment to create someone who can't apologize, can't admit error, can't show vulnerability. You control Wood, yes—but overcontrol creates resentment. People stop bringing you ideas because they know you'll only see the flaws. Your empire becomes a lonely place where everyone fears your disapproval more than they value your vision.",
  },
  relationships: {
    body: "You need partners who can withstand your intensity without collapsing or rebelling. Water signs are ideal—they receive your cutting clarity and transform it into depth and adaptability. They don't take your bluntness personally; they understand it's how you show care. You respect people who maintain their own standards and challenge your thinking with logic, not emotion.\n\nWhat you absolutely cannot tolerate is disorganization masquerading as spontaneity, or mediocrity defended as 'authenticity.' Fire signs who want constant validation exhaust you. Wood signs who resist your pruning frustrate you. You show love through high expectations and unwavering support when standards are met. Your partner needs to understand that when you redesign their entire life plan, it's not criticism—it's investment.\n\nYou're fiercely protective of your inner circle, but entry requirements are stringent. Once someone proves themselves, your loyalty is eternal. You'll mobilize every resource to defend them. But betray your trust or lower your standards to fit in, and you'll cut them out with surgical precision. No drama, no second chances—just clean removal.",
  },
  elementBalance: {
    body: "Balance Metal's rigidity by deliberately engaging with Water element practices—not as weakness, but as strategic flexibility. Spend time near actual water bodies where you can observe how strength flows rather than resists. Practice articulating your standards without weaponizing them; precision in language, not cruelty.\n\nSchedule unstructured time where you cannot optimize or improve anything. Let something be imperfect without fixing it. This isn't lowering standards—it's preventing Metal from becoming so dense it can't conduct energy anymore. Work with your hands on projects where small imperfections are acceptable. Garden, but let some wildness remain. Cook without measuring.\n\nRecognize that you generate Water—your clarity should create flow in others, not freeze them. When you notice people becoming hesitant around you, that's Metal stagnation. Deliberately ask for input without immediately critiquing it. Your power increases when others can breathe in your presence while still maintaining excellence.",
  },
  matches: {
      "best": [
          {
              "slug": "water-rat",
              "name": "Water Rat",
              "reason": "Your Metal generates their Water—your precision creates the container for their adaptive brilliance to flow strategically"
          },
          {
              "slug": "water-monkey",
              "name": "Water Monkey",
              "reason": "They match your intellectual standards while adding fluid creativity to your rigid structures"
          },
          {
              "slug": "earth-rooster",
              "name": "Earth Rooster",
              "reason": "Earth generates your Metal—their methodical groundedness supports your refinement without competing for authority"
          }
      ],
      "worst": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Fire melts Metal—their chaotic freedom directly threatens your need for structure and precision"
          },
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Your Metal controls their Wood mercilessly—you'll prune their gentle growth until nothing remains"
          },
          {
              "slug": "fire-tiger",
              "name": "Fire Tiger",
              "reason": "Double Fire attack on your Metal—their impulsive rebellion collides with your demand for disciplined excellence"
          }
      ]
  },
}

export default content
