// ============================================
// METAL OX (庚丑) — The Iron Pillar
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'metal-ox',
  profile: getProfileBySlug('metal-ox')!,
  archetype: {
    name: "The Iron Pillar",
    tagline: "The Iron Pillar — Metal Ox",
  },
  atAGlance: {
      "element": "Metal (Precision, Discipline, Structure)",
      "energy": "Yin",
      "archetype": "The Iron Pillar",
      "coreStrength": "Unshakeable Integrity",
      "shadow": "Unyielding Rigidity",
      "bestMatch": "water-rat",
      "worstMatch": "fire-horse",
      "luckyColor": "Steel Gray"
  },
  personality: {
    body: "The Metal Ox is an unbreakable force of principle and endurance. Where other signs waver or adapt, you stand firm—not from stubbornness alone, but from a deeply forged belief in standards, ethics, and methodical progress. Metal sharpens the Ox's already formidable determination into something surgical: you don't just work hard, you work with exacting precision. Every task has a correct way to be done, and you'll sacrifice speed, popularity, and comfort to do it right. You are the person others call when they need something built to last, whether that's a business system, a reputation, or a physical structure.\n\nYour Metal element brings refinement to the Ox's raw power. You're not content with brute force—you seek elegance in efficiency, beauty in order. You edit ruthlessly: excess is waste, shortcuts are lies, and half-measures insult your intelligence. This makes you exceptional in fields requiring both stamina and exactitude—engineering, law, craftsmanship, financial analysis, quality control. You see flaws others miss because your internal standards are calibrated to perfection. When you commit to something, it's not enthusiasm driving you; it's an iron contract with yourself.\n\nBut this is also where your Yin energy reveals itself. Unlike Yang Metal (which cuts outward, seeking change), your Metal turns inward—forging self-discipline, refining personal codes, building internal fortresses. You don't broadcast your principles; you embody them. People sense your integrity before you speak. You rarely seek the spotlight, but when injustice appears or standards slip, you become immovable. You won't argue loudly, but you will not bend. This quiet, gravitational authority makes you a natural guardian of institutions, traditions, and moral boundaries—though it can also make you the person everyone respects but few feel they truly know.",
  },
  shadow: {
    body: "Your greatest strength becomes your trap when Metal hardens into brittleness. You confuse rigidity with integrity, refusing to adapt even when circumstances demand it. You become the manager who enforces outdated policies because 'rules are rules,' the partner who withholds affection because vulnerability seems undisciplined, the friend who judges harshly and forgives slowly. Metal controls Wood in the destructive cycle—you prune growth, including your own, cutting away possibilities that don't fit your narrow vision of correctness.\n\nYour shadow emerges as cold perfectionism that punishes both yourself and others. You set impossible standards, then silently resent anyone who fails to meet them. You mistake emotional expression for weakness and spontaneity for chaos. Under stress, you don't explode—you freeze, withdrawing into isolated self-sufficiency while relationships rust from neglect. You become so focused on doing things right that you forget to ask why you're doing them at all. The Metal Ox at their worst is a prison warden to their own life, maintaining order in an increasingly empty fortress.",
  },
  relationships: {
    body: "You love through acts of service and unwavering commitment, not words or romance. You show up, you follow through, you remember what matters. But you struggle with emotional flexibility—you need partners who understand that your silence isn't coldness, it's Metal's inward-turning nature. You're most compatible with Water signs, which Metal generates: Water Rat, Water Pig, and Water Snake can soften your edges without weakening your core, translating your loyalty into emotional intimacy you struggle to voice.\n\nYou clash with Fire signs who demand spontaneity and passion over consistency. Fire melts Metal, and you experience their energy as chaos attacking your carefully built structure. Wood signs (especially Wood Tiger or Wood Rabbit) may initially attract you with their growth energy, but you'll unconsciously control and prune them—Metal cuts Wood—until resentment builds on both sides. You need someone who values your steadiness, respects your need for order, and gently challenges your rigidity without attacking your principles. Trust is your ultimate currency; betray it once, and the door closes permanently.",
  },
  elementBalance: {
    body: "Balance your Metal by consciously engaging Water practices—activities that generate flow from your structure. Journaling transforms rigid thoughts into fluid insight. Swimming or time near water literally connects you to the element you produce. Cultivate Earth energy through pottery, gardening, or cooking—Earth generates Metal, replenishing your reserves without forcing change.\n\nDeliberately practice small acts of flexibility: change your routine once weekly, say yes to an unplanned invitation, leave one task 'good enough' instead of perfect. These micro-adaptations prevent catastrophic brittleness. When you feel yourself hardening into judgment, ask: 'Am I protecting a principle or defending my fear of uncertainty?' Your integrity doesn't require inflexibility—steel's strength comes from controlled tempering, not absolute rigidity.",
  },
  matches: {
      "best": [
          {
              "slug": "water-rat",
              "name": "Water Rat",
              "reason": "Metal generates Water—your discipline creates the container for their flowing intelligence and emotional depth"
          },
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Water receives your structure gratefully; their genuine warmth melts your edges without threatening your integrity"
          },
          {
              "slug": "earth-rooster",
              "name": "Earth Rooster",
              "reason": "Earth generates Metal—their grounded perfectionism fuels yours; shared standards create mutual respect"
          }
      ],
      "worst": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Fire melts Metal—their chaotic freedom attacks your need for order; neither will compromise core nature"
          },
          {
              "slug": "wood-tiger",
              "name": "Wood Tiger",
              "reason": "Metal controls Wood—you'll unconsciously prune their wild growth until rebellion or resentment destroys connection"
          },
          {
              "slug": "fire-monkey",
              "name": "Fire Monkey",
              "reason": "Fire weakens Metal while Monkey's cleverness mocks your seriousness; mutual contempt disguised as banter"
          }
      ]
  },
}

export default content
