// ============================================
// METAL RABBIT (庚卯) — The Polished Strategist
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'metal-rabbit',
  profile: getProfileBySlug('metal-rabbit')!,
  archetype: {
    name: "The Polished Strategist",
    tagline: "The Polished Strategist — Metal Rabbit",
  },
  atAGlance: {
      "element": "Metal (Precision, Structure)",
      "energy": "Yin",
      "archetype": "The Polished Strategist",
      "coreStrength": "Refined execution",
      "shadow": "Perfectionist rigidity",
      "bestMatch": "water-pig",
      "worstMatch": "fire-rooster",
      "luckyColor": "Champagne gold"
  },
  personality: {
    body: "The Metal Rabbit combines the Rabbit's natural diplomacy with Metal's exacting standards, creating someone who navigates social landscapes with surgical precision. You don't just avoid conflict—you architect solutions that leave everyone thinking they won. Where typical Rabbits might be accused of being too soft, Metal adds a steel spine wrapped in velvet. You're the negotiator who remembers every clause, the host who coordinates twelve dietary restrictions without breaking a sweat, the friend who gives advice that's simultaneously kind and devastatingly accurate.\n\nMetal's autumn energy gives you an instinct for what needs pruning. You spot inefficiencies in systems the way others notice bad haircuts. This isn't the scattered criticism of Fire types—it's targeted, structural insight. You'll quietly reorganize an entire workflow, and people only realize later that everything suddenly runs smoother. The Rabbit's Yin nature means you rarely announce these improvements; you simply implement them and move on. Recognition matters less than the satisfaction of a thing done properly.\n\nYour aesthetic standards are non-negotiable. Metal governs refinement, and you apply this to everything from your workspace to your word choice. You're allergic to clutter, both physical and conversational. Small talk irritates you unless it serves a relational purpose. You'd rather have three well-chosen friends than thirty acquaintances, and you maintain those friendships with the same attention to detail you apply everywhere else. Birthdays are remembered, preferences noted, boundaries respected.\n\nThe strategic element here is real. Metal's controlling relationship with Wood means you instinctively understand how to redirect growth—including other people's chaotic energy. You don't fight force with force; you channel it, redirect it, refine it into something useful. This makes you exceptional at managing volatile personalities without ever raising your voice.",
  },
  shadow: {
    body: "Metal's cutting nature turns toxic when you wield standards as weapons. You can become the person who corrects everyone's grammar at dinner parties, who points out the single flaw in an otherwise excellent presentation, who makes people feel perpetually inadequate without saying anything explicitly cruel. The Rabbit's conflict-avoidance means you rarely explode—instead, you ice people out with polite distance that's somehow worse than anger.\n\nPerfectionism becomes paralysis. You'll delay launching projects because one element isn't quite right, miss opportunities because you're still refining your approach, withdraw from relationships because people inevitably disappoint your exact specifications. Metal's rigidity combines with Rabbit's retreat instinct—instead of bending, you simply vanish when things get messy. You ghost rather than negotiate, disappear rather than compromise.\n\nThe darker manifestation: weaponized competence. You become indispensable by being the only one who can meet your own standards, then resent the dependence you've engineered. You say yes to everything while silently cataloging how everyone fails to appreciate your precision, building resentment like interest in a savings account until you suddenly cut people off entirely.",
  },
  relationships: {
    body: "You need partners who can handle both your standards and your softness without confusing the two. The mistake people make is assuming your kindness means you're flexible—you're not. You're exacting about how relationships should function, but you express boundaries so diplomatically that partners often don't realize they've hit a wall until they're already on the other side of it.\n\nYou thrive with people who appreciate craftsmanship in relationships—those who understand that your remember-everything, plan-ahead, consider-all-angles approach is how you show love. Water types often work well because they flow around your structures without eroding them. You struggle with Fire's chaos and Wood's relentless pushing; both feel like assaults on the careful order you've created.\n\nIntimacy requires you to let people see the mess behind the polish. The Rabbit wants to present only the refined version; Metal wants to maintain impenetrable boundaries. Real connection happens when you allow someone to witness your standards-failing moments without immediately withdrawing. You need partners patient enough to wait out your retreat instincts and perceptive enough to recognize that your detailed attention to their preferences is the deepest declaration of care you know how to make.",
  },
  elementBalance: {
    body: "Metal excess manifests as brittleness—counter it by deliberately engaging Water activities that soften without weakening. This means actual rest, not productive relaxation. Take baths without bringing a book. Let conversations meander without steering them toward conclusions. Water nourishes Metal by giving it purpose beyond self-perfection.\n\nPractice Wood flexibility intentionally: say yes to spontaneous plans once a week, leave one area of your space deliberately unorganized, set a timer and stop perfecting after it goes off. Metal controls Wood, but you need some Wood energy to prevent total rigidity. Let things grow messily occasionally.\n\nCultivate Earth relationships—stable people who ground you without demanding you constantly perform competence. Earth generates Metal, feeding your strengths while absorbing some of your excessive edge. Spend time with people who are comfortable with silence and imperfection.",
  },
  matches: {
      "best": [
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Water receives Metal's precision while softening its edges; shared appreciation for quality and emotional depth"
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Earth generates Metal, providing stable ground for your refinement; shared loyalty and practical standards"
          },
          {
              "slug": "water-goat",
              "name": "Water Goat",
              "reason": "Water nourishes Metal while Goat's creativity gives your precision something beautiful to organize"
          }
      ],
      "worst": [
          {
              "slug": "fire-rooster",
              "name": "Fire Rooster",
              "reason": "Fire melts Metal while double perfectionism creates competing standards with no compromise mechanism"
          },
          {
              "slug": "wood-tiger",
              "name": "Wood Tiger",
              "reason": "Metal controls Wood aggressively; Tiger's chaos attacks your need for order while you prune their growth"
          },
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Fire melts Metal's structure while Horse's impulsiveness violates every strategic principle you hold"
          }
      ]
  },
}

export default content
