// ============================================
// METAL SNAKE (庚巳) — The Calculating Blade
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'metal-snake',
  profile: getProfileBySlug('metal-snake')!,
  archetype: {
    name: "The Calculating Blade",
    tagline: "The Calculating Blade — Metal Snake",
  },
  atAGlance: {
      "element": "Metal (Precision, Discipline)",
      "energy": "Yin",
      "archetype": "The Calculating Blade",
      "coreStrength": "Strategic ruthlessness",
      "shadow": "Cold manipulation",
      "bestMatch": "water-rooster",
      "worstMatch": "fire-pig",
      "luckyColor": "Platinum"
  },
  personality: {
    body: "The Metal Snake is precision incarnate—a creature of flawless strategy wrapped in silent intensity. Where other Snakes charm through mystique, you cut through complexity with surgical logic. Metal sharpens the Snake's already penetrating intelligence into something resembling a scalpel: you see patterns others miss, predict outcomes three moves ahead, and strike only when victory is mathematically certain. You don't gamble. You calculate.\n\nYour yin nature makes this coldness deceptive. You don't broadcast aggression—you store it, refine it, then deploy it with devastating accuracy when the moment arrives. People underestimate you because you're patient, composed, seemingly disengaged. That's their fatal error. Beneath the stillness runs an ambition forged in autumn's unforgiving clarity: you want excellence, control, and the satisfaction of being objectively right. Metal gives you standards that feel non-negotiable because they are—compromise feels like contamination to your elemental nature.\n\nYou excel in environments demanding precision: research, strategy, design, financial analysis, anywhere incompetence has measurable consequences. You have zero tolerance for sloppy thinking or emotional decision-making. Your work is immaculate because anything less feels physically wrong. This makes you invaluable in crisis—when others panic, you narrow focus, eliminate variables, execute. Metal generates Water in the cycle, meaning your discipline creates flow for others, though you rarely take credit. You'd rather be essential than celebrated.\n\nSocially, you're an enigma. Selective to the point of exclusion, you maintain a small circle of people who've earned access through competence or loyalty. You don't do small talk; you do strategic alliance. Friendships must serve purpose—intellectual stimulation, mutual advancement, or rare emotional resonance. This isn't coldness, it's Metal's insistence on quality over quantity.",
  },
  shadow: {
    body: "Your precision curdles into cruelty when unchecked. Metal controls Wood through cutting, and you wield criticism like a weapon—not to improve, but to dominate. You identify weaknesses in others with such accuracy that your observations land like assassinations. The problem isn't that you're wrong; it's that you use truth as a blade to maintain superiority. You manipulate through withheld information, strategic silence, and the calculated withdrawal of approval.\n\nYour standards become a cage. Perfectionism prevents you from starting projects, maintaining relationships, or accepting help. You'd rather fail alone than succeed with flawed collaboration. This rigidity makes you brittle—when reality doesn't conform to your calculations, you don't adapt, you resent. The Metal element's autumn energy can turn into perpetual pruning, cutting away anything that doesn't meet impossible thresholds until you're surrounded by nothing.\n\nJealousy runs deep. When others succeed through means you deem inferior—charm over competence, luck over strategy—you don't just disapprove, you quietly work to undermine. Your vengeance is patient, precise, and devastating because you've spent months identifying the exact point of maximum damage.",
  },
  relationships: {
    body: "You need partners who respect your need for control without enabling your coldness. Water signs (Rat, Pig, especially Water Rooster) work because Water is generated by Metal—they receive your discipline as nourishment rather than assault, offering emotional depth that tempers your hardness without demanding you become soft. Earth signs provide the grounding that stabilizes Metal's sharpness, though you'll clash with Earth types who prioritize harmony over honesty.\n\nYou're loyal once committed, but getting there requires passing tests you never explicitly announce. Betrayal—even minor inconsistency—ends relationships permanently. You don't forgive; you excise. In intimacy, you show love through acts of precision: remembering details, solving problems, protecting fiercely. Words feel inefficient. You need partners who understand that your silence isn't absence but the presence of deep calculation, and who can call out your cruelty without crumbling under your counterattack.\n\nFire signs exhaust you (Wood feeds Fire, and Metal controls Wood—circular tension). Fire Pig especially represents everything you despise: impulsive generosity, emotional decision-making, naive optimism. Their warmth feels like chaos to your order.",
  },
  elementBalance: {
    body: "Balance Metal by engaging the productive cycle: let yourself generate Water. Mentor someone without expecting perfection. Create systems that help others flow rather than just cutting away their mistakes. Practice Earth activities that feed your Metal—pottery, gardening, cooking—where precision serves growth, not domination.\n\nConsciously introduce Wood energy to challenge your control: improvisation, creative writing with no editing allowed, conversations where you don't plan responses. Let something be messy and functional rather than perfect and stillborn. Schedule regular exposure to Fire personalities—not to become them, but to remember that warmth has strategic value. Your sharpness cuts best when it's occasionally warmed, not perpetually frozen.",
  },
  matches: {
      "best": [
          {
              "slug": "water-rooster",
              "name": "Water Rooster",
              "reason": "Metal generates Water—your discipline gives their idealism structure; their emotional depth tempers your coldness into wisdom."
          },
          {
              "slug": "earth-ox",
              "name": "Earth Ox",
              "reason": "Earth feeds Metal—their patient endurance supports your precision; shared respect for competence and loyalty builds unshakable foundations."
          },
          {
              "slug": "water-dragon",
              "name": "Water Dragon",
              "reason": "Metal generates Water—you provide the strategic edge their vision needs; they offer ambition that matches your intensity without competing."
          }
      ],
      "worst": [
          {
              "slug": "fire-pig",
              "name": "Fire Pig",
              "reason": "Fire melts Metal—their impulsive generosity triggers your contempt; your coldness wounds their warmth; mutual incomprehension breeds resentment."
          },
          {
              "slug": "fire-tiger",
              "name": "Fire Tiger",
              "reason": "Fire melts Metal while Metal controls Wood—they're all passion and risk; you're all calculation and caution; explosive conflict inevitable."
          },
          {
              "slug": "wood-monkey",
              "name": "Wood Monkey",
              "reason": "Metal controls Wood—their playful chaos violates your need for order; you cut down their creativity; they mock your rigidity until war."
          }
      ]
  },
}

export default content
