// ============================================
// METAL RAT (庚子) — The Sharp-Witted Survivor
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'metal-rat',
  profile: getProfileBySlug('metal-rat')!,
  archetype: {
    name: "The Sharp-Witted Survivor",
    tagline: "The Sharp-Witted Survivor — Metal Rat",
  },
  atAGlance: {
      "element": "Metal (Precision, Discipline)",
      "energy": "Yang",
      "archetype": "The Sharp-Witted Survivor",
      "coreStrength": "Strategic precision",
      "shadow": "Cold manipulation",
      "bestMatch": "water-dragon",
      "worstMatch": "fire-horse",
      "luckyColor": "Silver"
  },
  personality: {
    body: "Metal Rat combines the Rat's natural cunning with Metal's surgical precision, creating someone who doesn't just survive—they dominate through calculated strategy. You're the person who sees seventeen moves ahead while everyone else is still figuring out the board. Metal sharpens the Rat's already formidable intelligence into something weaponized: you collect information like others breathe, file it systematically, and deploy it exactly when it maximizes advantage. There's nothing casual about how you operate.\n\nYour Metal structure gives the typically scattered Rat laser focus. Where other Rats chase every opportunity, you've already analyzed which three are worth pursuing and precisely how to exploit them. You set boundaries like steel walls—clear, immovable, uncompromising. People know exactly where they stand with you, which is either inside your fortress or outside it. Loyalty means something concrete to you: demonstrated value, consistent behavior, mutual benefit clearly defined. You're not sentimental, but you're absolutely reliable to those who've earned it.\n\nThe Yang energy makes you openly ambitious in ways that might make others uncomfortable. You don't pretend you're not competitive. You don't soften your edges to make mediocrity feel better. Metal's autumn energy means you're constantly pruning—relationships, projects, habits—cutting away what doesn't serve your refined standards. This creates an enviable clarity in your life but can feel ruthless to those who value inclusivity over excellence. You respect competence, despise waste, and have zero patience for emotional manipulation. Your wit is razor-sharp, your observations uncomfortably accurate, and your memory absolutely unforgiving of betrayal.",
  },
  shadow: {
    body: "Your precision becomes cold calculation that treats people like chess pieces. Metal's cutting nature turns your intelligence into a weapon you use preemptively—striking first because you've already determined someone might become a threat three years from now. You manipulate situations so skillfully that you sometimes forget there's a difference between strategic positioning and ethical behavior. The Rat's survival instinct, hardened by Metal, makes you hoard—information, resources, leverage—far past the point of security into pathological control. You become emotionally unavailable, mistaking vulnerability for weakness, connection for liability. Your standards become impossible, your judgments unforgiving, your worldview cynical. You sacrifice relationships on the altar of being right, of being prepared, of being invulnerable. The real danger: your brilliance makes your destructive patterns highly functional, so you never hit bottom hard enough to change course.",
  },
  relationships: {
    body: "You need partners who can match your intensity without trying to soften your edges. Someone who appreciates that your version of love is building an impenetrable fortress together, not endless emotional processing. You show care through practical action—anticipating needs, solving problems, creating security—but you need someone who recognizes that as intimacy, not avoidance. Metal makes you value quality over quantity in all relationships; you'd rather have three genuine allies than thirty shallow connections.\n\nYour challenge is letting people see your uncertainty without treating it like a tactical error. Metal Rats struggle with the idea that connection requires controlled vulnerability. You test people constantly, watching for weakness or betrayal, which exhausts those who just want straightforward trust. You need relationships where competence is celebrated, where strategic thinking is understood as a love language, where your partner doesn't demand you perform emotions you genuinely don't feel. But you must learn that not every relationship is a negotiation and not every person needs to prove their worth repeatedly.",
  },
  elementBalance: {
    body: "Generate Water—let your Metal precision flow into actual creation rather than just analysis. Start projects you can't completely control. Metal generates Water in the productive cycle; your discipline should produce wisdom and adaptability, not just harder boundaries. Practice making decisions with incomplete information. Deliberately leave some variables unoptimized. Your enemy is the belief that perfect strategy prevents all pain.\n\nAvoid excessive Wood control—stop cutting down every emerging possibility that doesn't fit your plan. Let some things grow wild. Metal controls Wood, but you over-prune until nothing spontaneous survives. Schedule unstructured time. Say yes to invitations without calculating ROI. Let someone else lead without mentally cataloging their inefficiencies. Balance your autumn energy with spring's experimental chaos, or you'll live in permanent winter.",
  },
  matches: {
      "best": [
          {
              "slug": "water-dragon",
              "name": "Water Dragon",
              "reason": "Metal generates Water—your precision gives their vision practical structure while they soften your edges with intuitive flow"
          },
          {
              "slug": "earth-ox",
              "name": "Earth Ox",
              "reason": "Earth generates Metal—their steady endurance fuels your refinement; both value competence and despise drama"
          },
          {
              "slug": "water-monkey",
              "name": "Water Monkey",
              "reason": "Metal generates Water—you provide strategic discipline to their cleverness; both operate through intelligence, not emotion"
          }
      ],
      "worst": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Fire controls Metal—their impulsive freedom melts your careful structures; chaos versus precision in perpetual conflict"
          },
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Metal controls Wood—you cut down their gentle growth with harsh judgment; your blade against their softness"
          },
          {
              "slug": "fire-goat",
              "name": "Fire Goat",
              "reason": "Fire controls Metal—their emotional fluidity overwhelms your need for clear boundaries and logical frameworks"
          }
      ]
  },
}

export default content
