// ============================================
// METAL TIGER (庚寅) — The Steel Enforcer
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'metal-tiger',
  profile: getProfileBySlug('metal-tiger')!,
  archetype: {
    name: "The Steel Enforcer",
    tagline: "The Steel Enforcer — Metal Tiger",
  },
  atAGlance: {
      "element": "Metal (Precision, Structure, Refinement)",
      "energy": "Yang",
      "archetype": "The Steel Enforcer",
      "coreStrength": "Disciplined conviction",
      "shadow": "Merciless rigidity",
      "bestMatch": "earth-horse",
      "worstMatch": "fire-rabbit",
      "luckyColor": "Gunmetal gray"
  },
  personality: {
    body: "The Metal Tiger is a formidable force—Tiger's raw courage tempered by Metal's exacting standards. Where ordinary Tigers charge on instinct, you operate with surgical precision. You don't just fight; you strategize, calculate angles, and strike with maximum efficiency. This isn't the wildcat brawling in alleys—this is the special forces operative who trains relentlessly, maintains their gear obsessively, and never wastes a move. You demand excellence from yourself first, then from everyone in your orbit.\n\nMetal sharpens Tiger's natural leadership into something almost martial. You create systems, protocols, hierarchies. When you enter a chaotic situation, you immediately begin imposing order—not through loud demands but through sheer force of competence. People follow you because you've already mapped the terrain, identified the threats, and developed contingencies. You have little patience for improvisation when proper preparation prevents problems. Your courage isn't reckless; it's backed by rigorous assessment of risk and capability.\n\nYour integrity is uncompromising. Metal's refinement process burns away impurities, and you apply this same standard to principles. Once you've determined the right course of action, you're immovable. This makes you trustworthy in crisis—you won't panic, won't compromise, won't abandon post. But it also makes you inflexible. You've refined your code of conduct to such a sharp edge that it cuts anyone who doesn't meet your specifications. You respect strength, competence, and dedication. Weakness disgusts you. Sloppiness offends you. Excuses enrage you. You're the drill sergeant, the quality control inspector, the auditor who finds every discrepancy and demands immediate correction.",
  },
  shadow: {
    body: "Your precision becomes cutting cruelty. Metal controls Wood—you literally chop down growth that doesn't conform to your standards. When someone fails your tests, you don't just correct them; you dismantle their confidence with surgical strikes to their weakest points. You tell yourself this is necessary toughness, but often it's just punishment for not being as strong as you are. Your high standards become impossible standards, and you alienate people who could be allies if you allowed room for human imperfection.\n\nThe shadow intensifies under stress. When threatened, you become the enforcer who mistakes brutality for strength. You double down on rules when flexibility is required, turn leadership into dictatorship, confuse respect with fear. Your courage warps into aggression—you pick fights to prove dominance rather than protect anything meaningful. Metal's refinement becomes obsessive perfectionism. You spend hours sharpening your blade when the battle is already lost, fixing trivial details while relationships collapse around you. You can't admit error because you've built your identity on being right, being strong, being superior. Compromise feels like defeat, so you'd rather burn everything down than bend.",
  },
  relationships: {
    body: "You need partners who respect strength but won't tolerate tyranny. You're drawn to competence—people who can match your intensity and meet your standards earn your fierce loyalty. But relationships require the vulnerability you've trained yourself to eliminate. You struggle with tenderness because Metal's nature is hard, defined, boundaried. Intimacy requires yielding, and yielding feels like weakness.\n\nYou show love through protection and provision, through making your people stronger. You'll train them, defend them, build structures that support them. What you can't easily do is simply sit with them in their pain without trying to fix or toughen them up. Your instinct when someone cries is to tell them to stop crying and start fighting. Sometimes people need a shoulder, not a battle plan.\n\nYou match well with Earth types who can absorb your intensity and provide stable ground for your sharp edges. Water types intrigue you—Metal generates Water in the cycle—your discipline feeds their depth. But Fire types often clash with you; Fire melts Metal, and you feel your carefully maintained structure threatened by their chaos and emotion.",
  },
  elementBalance: {
    body: "Balance Metal's rigidity by deliberately practicing yield. Set a timer and spend ten minutes daily doing something with no goal—doodle without making art, walk without destination, play without keeping score. Your instinct will be to optimize even this; resist. Spend time in water—swimming, floating—to connect with the element you generate. Water is Metal's natural outlet; when you're cutting everything around you, channel that energy into depth instead.\n\nPhysically, practice softness. Metal excess manifests as locked joints, clenched jaw, rigid posture. Do gentle mobility work, not aggressive training. Touch textiles, work with clay—materials that yield to pressure. When you catch yourself in judgmental mode, name three things the person does well before noting what they do wrong. This isn't lowering standards; it's recognizing that human beings aren't manufactured products, and growth requires more than quality control inspections.",
  },
  matches: {
      "best": [
          {
              "slug": "earth-horse",
              "name": "Earth Horse",
              "reason": "Earth supports Metal while Horse's independence matches your intensity without competing for dominance"
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Shared loyalty and principles; Earth grounds your sharpness while Dog respects your protective strength"
          },
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Metal generates Water—your discipline feeds their depth; Pig's warmth softens your edges without weakness"
          }
      ],
      "worst": [
          {
              "slug": "fire-rabbit",
              "name": "Fire Rabbit",
              "reason": "Fire melts Metal while Rabbit's diplomatic flexibility enrages your need for clear positions and strength"
          },
          {
              "slug": "fire-goat",
              "name": "Fire Goat",
              "reason": "Fire undermines your structure while Goat's emotional needs and scattered energy trigger your harshest enforcement"
          },
          {
              "slug": "wood-monkey",
              "name": "Wood Monkey",
              "reason": "Metal cuts Wood—you instinctively control Monkey's creativity; their playful chaos violates every protocol you've built"
          }
      ]
  },
}

export default content
