// ============================================
// METAL HORSE (庚午) — The Armored Charger
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'metal-horse',
  profile: getProfileBySlug('metal-horse')!,
  archetype: {
    name: "The Armored Charger",
    tagline: "The Armored Charger — Metal Horse",
  },
  atAGlance: {
      "element": "Metal (Precision, Structure, Refinement)",
      "energy": "Yang",
      "archetype": "The Armored Charger",
      "coreStrength": "Disciplined velocity",
      "shadow": "Rigid independence",
      "bestMatch": "earth-dog",
      "worstMatch": "fire-horse",
      "luckyColor": "Titanium silver"
  },
  personality: {
    body: "The Metal Horse is a paradox of controlled wildness—a creature built for speed but governed by precision. Where other Horses bolt on impulse, you calculate trajectories. Metal sharpens the Horse's natural momentum into a laser-focused drive toward tangible goals. You don't just want freedom; you want the structured systems that make freedom sustainable. This makes you the entrepreneur who builds empires, the athlete who perfects technique through relentless discipline, the artist whose wildest visions are executed with surgical precision.\n\nYou possess an almost military-grade work ethic. Metal's autumn energy brings harvest mentality—you understand that everything must be winnowed, refined, distilled to its essential form. The Horse's yang fire provides the engine; Metal provides the chassis and steering mechanism. You're charismatic but not performative. People follow you because you embody competence, not because you're trying to charm them. Your communication style is direct, sometimes brutally so. You say what needs to be said and expect others to handle it like adults.\n\nIndependence isn't just preferred—it's structural to your identity. You need autonomy like you need oxygen. Micromanagement makes you physically agitated. You'll build your own platforms, forge your own paths, create your own rules rather than submit to systems you consider inefficient or illogical. This isn't rebellion for its own sake; it's Metal's quality control meeting Horse's refusal to be corralled. You have exceptionally high standards—for yourself first, then for everyone else. When others meet those standards, you're fiercely loyal. When they don't, you cut them loose without sentimentality. Metal contracts, eliminates waste. You see no point in maintaining connections that don't serve mutual growth.",
  },
  shadow: {
    body: "Your precision becomes rigidity when stressed. Metal in excess grows brittle—you develop rules about everything, creating such tight structures around yourself that spontaneity suffocates. You'll abandon projects or relationships the moment they deviate from your predetermined path, unable to adapt when reality refuses to conform to your blueprint. The Horse's natural restlessness combines with Metal's cutting edge to make you ruthlessly dismissive. You don't just disagree with people—you mentally categorize them as incompetent and erase them from relevance. This leaves you increasingly isolated, surrounded only by those who never challenge your methods.\n\nYour independence curdles into emotional unavailability. You pride yourself on not needing anyone, which slowly transforms into an inability to receive support even when you desperately need it. The shadow Metal Horse believes vulnerability equals weakness, so you keep moving, keep working, keep achieving while your inner life becomes a desert. You can become addicted to difficulty itself—only respecting goals that require suffering to achieve, dismissing anything that comes easily as worthless. This is Metal's refinement instinct gone toxic, where you're constantly cutting away everything soft in yourself until only the hardened edges remain.",
  },
  relationships: {
    body: "You need partners who respect your autonomy but refuse to let you disappear entirely. The Metal Horse bonds through shared missions rather than emotional processing. You show love through competence—building things, solving problems, creating security through excellence. Grand emotional gestures make you uncomfortable; you'd rather prove devotion by consistently showing up and executing flawlessly on commitments.\n\nYou're attracted to people with their own strong sense of direction. Dependency repulses you. You want equals who can match your pace and occasionally race ahead, forcing you to level up. But here's your contradiction: you need someone grounded enough to create a home base you can return to between your ambitious sprints. Without that anchor, you just keep running until you collapse.\n\nIn conflict, you go cold rather than hot—Metal's contracting nature means you withdraw, fortify, become unreachable. You need to learn that disagreement doesn't require disconnection. Your people need to understand that your silence isn't rejection; it's processing mode. Give you space to think, then expect direct, solution-focused conversation. Never try to manipulate through emotion or guilt—you'll spot it instantly and lose all respect.",
  },
  elementBalance: {
    body: "Feed Metal by honoring completion cycles. Finish what you start before charging toward the next goal. Create rituals that mark endings—Metal governs letting go, not just refining. Practice deliberate rest; your body isn't actually made of metal, despite how you treat it.\n\nBalance Metal's contraction with activities that expand: improvisational anything, unstructured nature time, conversations with no agenda. Wood generates Fire—spend time with growth-oriented, visionary people who pull you out of pure execution mode into creative possibility.\n\nYour element generates Water, so channel achievements into deeper wisdom. Journal, mentor, teach. Let your hard-won precision flow into nourishing others rather than just accumulating more victories. When you feel yourself becoming brittle, seek Earth energy—pottery, gardening, cooking. Slow, sensory activities that reconnect you to organic rhythms instead of manufactured deadlines.",
  },
  matches: {
      "best": [
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Earth supports Metal; Dog's loyalty grounds Horse's independence without constraining it—shared integrity, mutual respect for competence"
          },
          {
              "slug": "water-tiger",
              "name": "Water Tiger",
              "reason": "Metal generates Water; Tiger matches Horse's courage while Water softens Metal's rigidity—adventurous equals with complementary wisdom"
          },
          {
              "slug": "earth-goat",
              "name": "Earth Goat",
              "reason": "Earth nourishes Metal; Goat's creativity needs Horse's structure, Horse's hardness needs Goat's artistic softening—productive contrast"
          }
      ],
      "worst": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Fire melts Metal; double Horse independence with no grounding—mutual stubbornness, nobody yields, relationship becomes a competition not partnership"
          },
          {
              "slug": "wood-monkey",
              "name": "Wood Monkey",
              "reason": "Metal cuts Wood; Monkey's changeability clashes with Horse's directional commitment—Monkey sees Horse as inflexible, Horse sees Monkey as unserious"
          },
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Metal controls Wood; Horse's intensity overwhelms Rabbit's gentleness—Horse frustrated by Rabbit's indirectness, Rabbit exhausted by Horse's demands"
          }
      ]
  },
}

export default content
