// ============================================
// METAL PIG (庚亥) — The Benevolent Stronghold
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'metal-pig',
  profile: getProfileBySlug('metal-pig')!,
  archetype: {
    name: "The Benevolent Stronghold",
    tagline: "The Benevolent Stronghold — Metal Pig",
  },
  atAGlance: {
      "element": "Metal (Precision, Discipline, Strength)",
      "energy": "Yin",
      "archetype": "The Benevolent Stronghold",
      "coreStrength": "Principled generosity",
      "shadow": "Righteous rigidity",
      "bestMatch": "water-rabbit",
      "worstMatch": "fire-snake",
      "luckyColor": "Champagne gold"
  },
  personality: {
    body: "The Metal Pig is a fortress with open gates—structured yet welcoming, disciplined yet warm. You combine the Pig's natural generosity with Metal's razor-sharp standards, creating someone who gives abundantly but only to causes and people that meet your ethical criteria. You don't scatter your kindness randomly; you architect it with precision. Where other Pigs might indulge everyone indiscriminately, you've built systems around your compassion. You volunteer, but you research the organization first. You help friends, but you won't enable destructive patterns. This is Metal cutting through sentimentality to create sustainable goodness.\n\nYour strength lies in principled abundance. You understand that true generosity requires boundaries, that saying yes to everything means saying yes to nothing of consequence. You create institutions rather than just giving handouts—the scholarship fund instead of the one-time loan, the meal-prep system instead of sporadic dinner deliveries. Metal gives you the spine to maintain standards even when people call you harsh; Pig ensures those standards serve collective wellbeing, not mere ego. You're the nonprofit director who fires underperformers because the mission matters more than being liked, the parent who sets firm rules because you actually care about outcomes.\n\nYou have exceptional taste combined with accessibility. Metal refines the Pig's appreciation for comfort into curated excellence—you know which kitchen knife is worth the investment, which charity operates with genuine efficiency, which friendship is built on substance versus performance. But unlike Metal Roosters who weaponize their discernment, you share your knowledge generously. You're not hoarding expertise; you're building others' capacity to make better choices. This makes you an invaluable mentor, the person who teaches someone to fish with the best rod and proper technique, not just once but until they've mastered it.",
  },
  shadow: {
    body: "Your standards can calcify into judgmental inflexibility. You start believing your way is the only ethical way, dismissing other approaches as sloppy or corrupt. Metal's cutting energy, when unbalanced, turns your principled nature into righteous rigidity—you refuse to help anyone who doesn't meet your exact criteria, even when circumstances are complex. You'll let a friendship die rather than compromise on a procedural disagreement. You mistake your specific implementation of values for the values themselves.\n\nYou can become withholding in the name of wisdom. Where you intend to teach discernment, you actually create scarcity—making people jump through elaborate hoops to prove they deserve your help, time, or affection. This isn't generosity; it's control dressed as mentorship. You deny requests with lectures about why the requester's approach is flawed, unable to simply say no without justifying your superiority. The fortress walls get higher even as you claim the gates are open to anyone who meets your reasonable standards. Your abundance becomes conditional to the point of disappearing entirely.",
  },
  relationships: {
    body: "You need partners who respect structure but soften your edges. You bond through shared standards and collaborative building—the relationship that improves both people's lives through mutual accountability. You're drawn to competence and integrity, dismissive of emotional chaos masquerading as depth. But you need someone who can challenge your rigidity without triggering your contempt, who meets your standards while also reminding you that standards exist to serve love, not replace it.\n\nYou express care through infrastructure—setting up systems, sharing resources, teaching skills. But you must learn that sometimes people need messy emotional presence, not optimization plans. Your partner needs to feel your warmth directly, not just experience the evidence of your care through well-organized shared spreadsheets. In conflict, you become coldly logical exactly when connection requires vulnerability. You cite principles instead of acknowledging feelings, convinced that rightness matters more than repair. The challenge is staying generous when your standards aren't met, maintaining the Pig's open heart even as Metal demands precision.",
  },
  elementBalance: {
    body: "Metal generates Water—practice flowing around obstacles instead of cutting through them every time. Spend time near actual water; notice how it achieves its goals through persistence and adaptation, not force. When you feel yourself hardening into judgment, physically soften your jaw and shoulders. Create one area of your life with absolutely no standards—a messy junk drawer, an unstructured weekly hour, permission to enjoy something objectively mediocre. Metal controls Wood, so tend actual plants; practice nurturing something that grows according to its own nature, not your blueprint. Let someone help you their way, not yours, and genuinely thank them. Schedule regular moments of pure indulgence with zero optimization—the point is pleasure, not improvement. Balance your precision with deliberate, principled softness.",
  },
  matches: {
      "best": [
          {
              "slug": "water-rabbit",
              "name": "Water Rabbit",
              "reason": "Metal generates Water; their diplomatic flow softens your rigidity while respecting your structure, creating sustainable intimacy."
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Earth generates Metal; their grounded loyalty strengthens your principles while tempering righteousness with genuine service."
          },
          {
              "slug": "water-goat",
              "name": "Water Goat",
              "reason": "Metal generates Water; their creative adaptability flows through your frameworks, adding beauty to your discipline."
          }
      ],
      "worst": [
          {
              "slug": "fire-snake",
              "name": "Fire Snake",
              "reason": "Fire melts Metal; their strategic intensity dissolves your boundaries, creating manipulation disguised as sophistication."
          },
          {
              "slug": "wood-monkey",
              "name": "Wood Monkey",
              "reason": "Metal controls Wood; you'll constantly cut down their experimental chaos, killing joy while they resist your every standard."
          },
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Fire melts Metal; their impulsive freedom threatens your careful structures, leaving you rigid and them feeling caged."
          }
      ]
  },
}

export default content
