// ============================================
// METAL GOAT (庚未) — The Refined Artisan
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'metal-goat',
  profile: getProfileBySlug('metal-goat')!,
  archetype: {
    name: "The Refined Artisan",
    tagline: "The Refined Artisan — Metal Goat",
  },
  atAGlance: {
      "element": "Metal (Precision, Structure)",
      "energy": "Yin",
      "archetype": "The Refined Artisan",
      "coreStrength": "Disciplined creativity",
      "shadow": "Perfectionist rigidity",
      "bestMatch": "earth-rabbit",
      "worstMatch": "fire-horse",
      "luckyColor": "Platinum silver"
  },
  personality: {
    body: "You bring Metal's precision to the Goat's artistic temperament, creating someone who doesn't just create—you refine until the work achieves perfection. Where other Goats drift with inspiration, you impose structure on beauty. You understand that true artistry requires discipline, that the sculptor's vision means nothing without the hand that can execute with exactness. Your taste is impeccable because Metal gives you the ability to see flaws others miss and the patience to eliminate them.\n\nThis isn't about cold calculation. Metal's controlling relationship with Wood means you can prune excess, strip away the unnecessary, and reveal essential form. You approach creative work like a master jeweler—each decision deliberate, each element serving purpose. Where Fire Goats explode with passion and Earth Goats nurture community art, you create objects of enduring value. You're drawn to crafts that demand precision: metalwork, architecture, fine woodworking, graphic design with exacting standards.\n\nYour social presence carries Metal's reserve. You don't perform or seek attention; your work speaks. When you do engage, you offer observations that cut through social pleasantness to name what others sense but won't say. People experience you as simultaneously gracious and exacting—you'll host beautifully but notice if someone uses the wrong fork. This isn't snobbery; Metal simply recognizes proper order.\n\nYou need solitude to create. Metal generates Water in the cycle, meaning your precision ultimately flows into depth and reflection. Your best work emerges after long periods of focused isolation, where you can refine without compromise. You're loyal to standards more than people, which makes you reliable but occasionally inflexible. When you commit to a principle or aesthetic, you don't waver.",
  },
  shadow: {
    body: "Your perfectionism becomes paralysis. Metal's cutting nature turns inward, and you spend hours refining details no one else will notice while avoiding actually finishing or sharing work. You weaponize standards, using your refined taste to dismiss others' efforts as crude or insufficient. This masks insecurity—if nothing meets your standards, you never risk genuine vulnerability.\n\nYou become brittle. Metal unbent becomes Metal broken. When life demands flexibility, you double down on rules and correctness, alienating people who need warmth, not critique. Your controlling relationship with Wood means you can strip away so much 'excess' that you leave relationships bare and lifeless. You prune until nothing grows.\n\nYou hoard approval while pretending indifference. Metal's Yin nature can become cold withdrawal disguised as dignity. You silently judge everyone's taste, craftsmanship, or choices, building an internal fortress of superiority that protects you from having to actually connect. Your refinement becomes a wall, your standards a moat. People stop sharing with you because they know you'll find the flaw.",
  },
  relationships: {
    body: "You need partners who appreciate quality without demanding constant warmth. You show love through exquisite gestures—the perfectly chosen gift, the meticulously planned evening—but struggle with messy emotional spontaneity. You're drawn to people who respect your need for order and can match your standards without competing.\n\nYou're fiercely loyal once committed, but getting you to commit requires patience. You're evaluating compatibility with the same precision you'd assess a joint's fit in woodworking. Once satisfied, you're devoted, though you may express it through acts of service rather than declarations. You need space within intimacy—time to work alone, surfaces kept clear, routines respected.\n\nYour challenge: learning that human connection requires tolerating imperfection. Metal generates Water, meaning your precision should flow into emotional depth, not freeze into criticism. The people who last with you are those who help you soften your edges while respecting your essential nature. You're not meant to become sloppy; you're meant to recognize that love itself is the ultimate refinement.",
  },
  elementBalance: {
    body: "Feed Water to prevent Metal from becoming too rigid. Spend time near actual water—coastlines, rivers—and let your mind wander without agenda. This allows your precision to generate flow rather than rigidity.\n\nBalance your control of Wood by engaging with growing things without trying to perfect them. Garden, but let some wildness remain. Work with wood, but appreciate the grain you can't control. This teaches you that structure serves life, not the reverse.\n\nPhysical practices that combine precision with breath work—archery, martial arts forms, instrument playing—keep Metal's nature active without becoming destructive. Create deadlines to force yourself to finish rather than endlessly refine. Share work at 90% to learn that imperfect-and-done beats perfect-and-hidden.",
  },
  matches: {
      "best": [
          {
              "slug": "earth-rabbit",
              "name": "Earth Rabbit",
              "reason": "Earth generates Metal while Rabbit's diplomacy softens your edges; they nurture your refinement without demanding you compromise standards"
          },
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Metal generates Water naturally; Pig's generosity gives you permission to relax while appreciating your precision"
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Earth supports Metal and Dog shares your loyalty to standards; you build something enduring together through shared discipline"
          }
      ],
      "worst": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Fire melts Metal and Horse's chaos disrupts your need for order; they experience your precision as controlling, you experience their freedom as reckless"
          },
          {
              "slug": "fire-monkey",
              "name": "Fire Monkey",
              "reason": "Fire destroys Metal structure while Monkey's tricks mock your seriousness; constant conflict between refinement and rebellion"
          },
          {
              "slug": "wood-tiger",
              "name": "Wood Tiger",
              "reason": "Metal controls Wood harshly and Tiger resists all restriction; you prune their growth, they experience you as suffocating"
          }
      ]
  },
}

export default content
