// ============================================
// WATER RABBIT (壬卯) — The Flowing Peacemaker
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'water-rabbit',
  profile: getProfileBySlug('water-rabbit')!,
  archetype: {
    name: "The Flowing Peacemaker",
    tagline: "The Flowing Peacemaker — Water Rabbit",
  },
  atAGlance: {
      "element": "Water (Wisdom, Adaptability, Flow)",
      "energy": "Yin",
      "archetype": "The Flowing Peacemaker",
      "coreStrength": "Intuitive diplomacy",
      "shadow": "Emotional escapism",
      "bestMatch": "wood-pig",
      "worstMatch": "fire-rooster",
      "luckyColor": "Midnight blue"
  },
  personality: {
    body: "The Water Rabbit is the zodiac's most emotionally intelligent diplomat. Where other Rabbits rely on charm and evasion, you add Water's depth—reading undercurrents in conversations that others miss entirely. You don't just avoid conflict; you absorb tension like a still pond absorbs ripples, transforming aggression into calm through sheer receptivity. This isn't weakness. It's strategic fluid intelligence. You understand that influence flows around obstacles rather than confronting them head-on.\n\nYour adaptability borders on chameleonic. In professional settings, you mirror the energy required—serious in boardrooms, playful in brainstorms—but this isn't performance. Water takes the shape of its container while remaining essentially unchanged. You maintain your core values while navigating diverse social landscapes. This makes you exceptional in roles requiring cultural sensitivity, mediation, or managing fragile egos. You can deliver hard truths so gently that people thank you for them.\n\nThe double-yin combination (Water + Rabbit) gives you an almost psychic sensitivity to emotional atmospheres. You know when someone's smile doesn't reach their eyes. You sense office politics before they surface. This perceptiveness is your superpower in relationships and negotiations, but it's also exhausting. You absorb everyone's emotional weather, and unlike Metal signs that deflect or Fire signs that burn through feelings, you hold them. This requires deliberate emotional drainage—literal time near water, in silence, away from human demands.\n\nYour creativity flows in waves rather than steady streams. Water Rabbits produce their best work in cyclical bursts, often after long periods of apparent inactivity. Others might see procrastination; you're actually in the essential germination phase. Your ideas need time to saturate and develop in the dark before surfacing. Trust your timing. It's more accurate than any deadline.",
  },
  shadow: {
    body: "Your gift for emotional absorption becomes pathological when you mistake drowning in feelings for empathy. Water stagnates without movement, and you can become a swamp of unprocessed emotions—yours and everyone else's. This manifests as passive-aggressive withdrawal, martyrdom, or emotional manipulation through guilt. You'll sacrifice your needs until resentment builds, then flood everyone with tears or cold silence instead of stating boundaries clearly.\n\nThe escapism is real. When overwhelmed, Water Rabbits don't fight—they dissolve. This looks like binge-watching until 4 AM, excessive drinking disguised as social lubrication, or retreating into fantasy relationships (online, fictional, or with emotionally unavailable people). You convince yourself you're 'recharging,' but you're actually avoiding. The difference: healthy solitude restores you for engagement; escapism numbs you from it. Your conflict avoidance can enable genuinely toxic people. You'll rationalize abuse as 'complexity' or 'they're going through something' long past the point where self-respect demands exit. Water's wisdom includes knowing when to flow away permanently, not just temporarily retreat.",
  },
  relationships: {
    body: "You need partners who provide gentle structure without rigidity—think riverbanks that guide without damming. Earth signs offer this naturally, grounding your emotional fluidity without suppressing it. You're drawn to intensity but fare better with steady warmth than volcanic passion. In love, you're devastatingly attentive, remembering details partners mentioned once months ago, anticipating needs before they're voiced.\n\nThe trap: you can love someone's potential rather than their reality, waiting for them to 'flow' into the person you sense they could become. This wastes years. Water Rabbits must learn that accepting someone as-is doesn't mean tolerating mistreatment. Your relationships thrive when you establish rhythms—predictable time together and apart. You need space to process emotions privately before discussing them, which partners can misread as secrecy.\n\nSexually, you're more adventurous than your innocent demeanor suggests, but only with trusted partners. Emotional safety is your aphrodisiac. You express love through anticipatory service—the coffee made before they wake, the problem solved before they ask—but you must vocalize your own needs. Assuming others will intuit your desires as you do theirs leads to chronic disappointment.",
  },
  elementBalance: {
    body: "Combat Water stagnation through literal movement near actual water—swim, walk by rivers, shower mindfully. When you notice emotional fog, ask: 'Is this mine?' Practice returning others' feelings to them. Journal to externalize the swirl; Water needs an outlet or it pools.\n\nGenerate Wood by feeding your creativity even when it feels pointless. Start projects with no outcome pressure. Wood growth gives Water purpose and direction—without it, you're a puddle, not a stream. Deliberately cultivate one Fire-element friend who pushes you toward directness. Their bluntness will feel aggressive but models the healthy assertion you avoid. Balance doesn't mean becoming Fire; it means borrowing its clarity when necessary. Schedule 'non-negotiable' time—boundaries you won't dissolve. Even marking two hours weekly as untouchable strengthens your containment.",
  },
  matches: {
      "best": [
          {
              "slug": "wood-pig",
              "name": "Wood Pig",
              "reason": "Water generates Wood; their growth-oriented generosity gives your emotional depth productive direction without demanding hardness."
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Earth contains Water; their loyal stability provides safe banks for your emotional flow while respecting your need for depth."
          },
          {
              "slug": "metal-goat",
              "name": "Metal Goat",
              "reason": "Metal generates Water; their refined creativity and emotional honesty mirror your sensitivity with better boundaries to learn from."
          }
      ],
      "worst": [
          {
              "slug": "fire-rooster",
              "name": "Fire Rooster",
              "reason": "Water controls Fire; their aggressive precision and public criticism evaporate your confidence, while you dampen their necessary spark."
          },
          {
              "slug": "fire-dragon",
              "name": "Fire Dragon",
              "reason": "Mutual exhaustion—your yin depth frustrates their yang explosiveness; they see hesitation where you see wisdom, you see recklessness where they see courage."
          },
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "They manipulate emotionally without your conscience; your empathy becomes their weapon, and their Metal structure cuts rather than contains you."
          }
      ]
  },
}

export default content
