// ============================================
// WATER ROOSTER (壬酉) — The Perceptive Observer
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'water-rooster',
  profile: getProfileBySlug('water-rooster')!,
  archetype: {
    name: "The Perceptive Observer",
    tagline: "The Perceptive Observer — Water Rooster",
  },
  atAGlance: {
      "element": "Water (Wisdom, Adaptability)",
      "energy": "Yin",
      "archetype": "The Perceptive Observer",
      "coreStrength": "Strategic insight",
      "shadow": "Detached manipulation",
      "bestMatch": "metal-snake",
      "worstMatch": "fire-rabbit",
      "luckyColor": "Charcoal gray"
  },
  personality: {
    body: "The Water Rooster combines the Rooster's natural precision with Water's fluid intelligence, creating someone who observes keenly before acting. Where typical Roosters announce themselves loudly, Water Roosters watch from the sidelines, absorbing patterns others miss. They're the colleague who stays quiet in meetings then sends an email later that perfectly diagnoses the real problem everyone danced around. Their strength lies in seeing through pretense—they detect inconsistency like a tuning fork detects false notes.\n\nWater softens the Rooster's harsh edges without dulling their analytical blade. These individuals adapt their communication style to their audience, knowing when to be direct and when to let silence do the work. They're excellent strategists because they understand timing—Water's wisdom teaches them that the right insight delivered at the wrong moment is worthless. They'll wait weeks for the perfect opening to share an observation that changes everything.\n\nTheir perfectionism runs deep but expresses subtly. Rather than loudly criticizing flaws, they ask pointed questions that make others realize their own mistakes. This indirect approach makes them influential without being abrasive. They excel in roles requiring pattern recognition—data analysis, investigative work, editorial positions, or any field where seeing what's hidden matters more than being seen. They're ruthlessly efficient with their energy, refusing to waste effort on battles that don't advance their position.\n\nThe Water element grants them emotional intelligence most Roosters lack. They read room dynamics instinctively and position themselves accordingly. But this perceptiveness can calcify into cynicism—they see so many flaws, so much performative nonsense, that genuine enthusiasm becomes difficult. They risk becoming the person who's always right but never truly connected.",
  },
  shadow: {
    body: "Water's adaptability becomes slipperiness when unchecked. The Water Rooster can rationalize withholding crucial information as \"strategic timing\" when it's actually manipulation. They use their perceptiveness as a weapon, cataloging others' weaknesses for potential leverage rather than compassionate understanding. Their ability to shift communication styles degrades into shapeshifting—being whoever they need to be to extract what they want, leaving others wondering who they actually are.\n\nTheir detachment masquerades as wisdom but often stems from fear of vulnerability. They critique from a distance to avoid the messiness of genuine engagement. This creates a fortress of analysis that protects them from criticism but also from intimacy. They can become emotional misers, hoarding their true thoughts and feelings while expecting others to remain transparent. Their silence, initially strategic, becomes a moat that isolates them. When Water Roosters stop participating and become permanent observers, they forfeit the influence they carefully cultivated.",
  },
  relationships: {
    body: "Water Roosters need partners who appreciate their depth without demanding constant emotional display. They show love through strategic support—remembering the detail you mentioned once, solving problems you didn't ask for help with, positioning you advantageously in social situations. They're intensely loyal once committed but slow to trust, testing partners' consistency before fully opening up.\n\nThey struggle with partners who need constant verbal reassurance or process emotions loudly. Drama exhausts them—they'd rather resolve issues through thoughtful conversation than heated arguments. They need space to retreat into their observational mode without it being interpreted as withdrawal. Best matches understand that their silence isn't absence but processing.\n\nIn friendships, they're the advisor everyone seeks but few truly know. They attract people with messy lives who need their clarity, which can become draining if they don't establish boundaries. They must learn that relationships require participation, not just perceptive commentary. Their challenge is moving from witness to co-creator, sharing the stage rather than critiquing the performance from the wings.",
  },
  elementBalance: {
    body: "Balance excess Water by deliberately engaging before you've fully analyzed. Set a timer—respond within one hour rather than waiting for perfect insight. Water generates Wood, so channel observations into creative output: write that analysis, design that system, build something tangible from your patterns. Control your tendency to douse others' Fire by finding one genuine thing to encourage daily. Practice stating your position directly instead of asking leading questions—own your critique rather than manipulating others into discovering it. Schedule regular participation in activities where you cannot observe from the sidelines: team sports, performance arts, collaborative projects that demand real-time presence. Let yourself be seen making mistakes. Water stagnates without flow—move your wisdom into action or it becomes cynicism.",
  },
  matches: {
      "best": [
          {
              "slug": "metal-snake",
              "name": "Metal Snake",
              "reason": "Metal generates Water while Snake shares strategic depth—both value precision and see through pretense without judgment."
          },
          {
              "slug": "metal-ox",
              "name": "Metal Ox",
              "reason": "Metal feeds Water's wisdom while Ox provides grounded consistency that helps Water Rooster trust and relax their guard."
          },
          {
              "slug": "water-dragon",
              "name": "Water Dragon",
              "reason": "Shared Water element creates mutual understanding—both ambitious and perceptive, they strategize together without power struggles."
          }
      ],
      "worst": [
          {
              "slug": "fire-rabbit",
              "name": "Fire Rabbit",
              "reason": "Water controls Fire, creating dampening dynamic—Rabbit's need for harmony clashes with Rooster's critical precision."
          },
          {
              "slug": "wood-rooster",
              "name": "Wood Rooster",
              "reason": "Water generates Wood but double Rooster energy breeds competitive criticism—both analyzing each other to death."
          },
          {
              "slug": "fire-dog",
              "name": "Fire Dog",
              "reason": "Water extinguishes Fire's passionate idealism—Dog sees Water Rooster's strategy as cold calculation lacking moral center."
          }
      ]
  },
}

export default content
