// ============================================
// WATER DRAGON (壬辰) — The Tidal Force
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'water-dragon',
  profile: getProfileBySlug('water-dragon')!,
  archetype: {
    name: "The Tidal Force",
    tagline: "The Tidal Force — Water Dragon",
  },
  atAGlance: {
      "element": "Water (Wisdom, Depth, Flow)",
      "energy": "Yang",
      "archetype": "The Tidal Force",
      "coreStrength": "Strategic depth",
      "shadow": "Manipulative withdrawal",
      "bestMatch": "metal-monkey",
      "worstMatch": "earth-dog",
      "luckyColor": "Deep sapphire"
  },
  personality: {
    body: "Water Dragon commands through depth rather than spectacle. Where other Dragons roar, you observe—storing information like reservoirs hold rain, releasing it only when the moment creates maximum impact. Your Yang energy doesn't announce itself with fire; it moves like ocean currents, invisible on the surface but capable of redirecting entire ships. You understand that true power flows around obstacles rather than crashing through them.\n\nYour element gives Dragon ambition a patience other Dragons lack. You'll spend years positioning yourself, building networks invisible to those watching for overt displays. This makes you exceptionally dangerous in negotiations—you've already mapped every possible outcome before others realize the game has started. Water's wisdom tempers Dragon's ego just enough to make you effective rather than self-destructive. You know when to advance and when to retreat, a flexibility that confounds more rigid personalities.\n\nPeople underestimate you until they're already caught in your undertow. Your charm runs deep and cold—magnetic precisely because it doesn't try too hard. You attract through mystery rather than performance, drawing others into depths they didn't know they wanted to explore. In leadership, you create environments where people think they're acting independently while you've already shaped every available choice. This isn't malicious; it's simply how you operate. You see patterns in human behavior the way water finds cracks in stone, and you're patient enough to let pressure do the work.\n\nYour creativity flows in cycles—periods of stillness followed by torrential output. You need both. The stillness isn't laziness; it's accumulation. You're absorbing, processing, waiting for the moment when everything you've gathered crystallizes into something undeniable.",
  },
  shadow: {
    body: "You manipulate when you could communicate. That strategic mind becomes controlling, orchestrating situations so elaborately that authentic connection becomes impossible. People become pieces on your game board, valued for utility rather than humanity. You tell yourself you're protecting them by managing outcomes, but you're really protecting yourself from vulnerability.\n\nWithdrawal is your weapon of choice. When challenged, you don't fight—you vanish emotionally, becoming unreachable in ways that make others question their own reality. This passive aggression is Water's destructive cycle in action: you erode others' confidence through absence and ambiguity. You know exactly how much silence creates maximum doubt, and you use it.\n\nYour depth becomes stagnation when fear masquerades as patience. You'll claim you're waiting for the right moment while actually you're paralyzed, watching opportunities drift past because moving means risking your carefully constructed position. The element that should flow becomes a swamp—still, dark, breeding toxicity. You hoard information, connections, resources, convinced that scarcity keeps you safe when it actually keeps you isolated.",
  },
  relationships: {
    body: "You bond through shared secrets and strategic alliance before emotional intimacy. Partners often feel they're being studied rather than loved, because honestly, they are—at least initially. You're assessing loyalty, mapping their patterns, determining if they're safe. This creates relationships that feel profound but oddly hollow, depth without warmth.\n\nYou need partners who can call you on your control without triggering your retreat. Someone who sees your manipulation clearly, names it directly, and stays anyway—not because they're weak, but because they're strong enough to handle your depths without drowning. You respect strength that doesn't perform.\n\nSexual connection opens you faster than emotional conversation. Physical intimacy bypasses your strategic mind, letting Water's natural flow emerge. Here you're genuinely present rather than three moves ahead. The challenge is building relationships that sustain themselves outside the bedroom, where your tendency to orchestrate resurfaces. You thrive with people who maintain their own center regardless of your tides—who can be pulled by your current without losing themselves in it.",
  },
  elementBalance: {
    body: "Generate Wood by committing to creative projects with deadlines. Water without Wood direction becomes scattered depth—you need the structure of growth to channel your wisdom into tangible form. Start things and finish them; your tendency to endlessly refine is stagnation dressed as perfectionism.\n\nBalance your control over Fire by accepting emotional spontaneity. Not everything requires strategy. Let yourself react without calculating consequences occasionally. Your fear of Fire's chaos keeps you rigid; small doses of unplanned expression prevent explosive burnout.\n\nSeek Metal companionship—people with clear boundaries and direct communication. They'll provide the structure that helps you flow productively rather than pooling. And occasionally let yourself be truly still—not strategizing, just being. Water stagnates or depletes; stillness restores. The difference is intention.",
  },
  matches: {
      "best": [
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "Metal generates Water while Monkey's cleverness matches your strategic depth—mutual respect without power struggles"
          },
          {
              "slug": "metal-rat",
              "name": "Metal Rat",
              "reason": "Metal feeds your Water element while Rat's resourcefulness appreciates your patient accumulation of advantage"
          },
          {
              "slug": "wood-rooster",
              "name": "Wood Rooster",
              "reason": "You generate Wood while Rooster's precision gives your flowing strategy concrete structure and accountability"
          }
      ],
      "worst": [
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Earth controls Water—Dog's moral rigidity dams your flow and judges your strategic ambiguity as dishonesty"
          },
          {
              "slug": "earth-goat",
              "name": "Earth Goat",
              "reason": "Earth blocks Water—Goat needs emotional reassurance you can't provide, creating stagnant neediness that suffocates you both"
          },
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Water controls Fire—your depth extinguishes Horse's spontaneity while their chaos disrupts your careful positioning"
          }
      ]
  },
}

export default content
