// ============================================
// WATER SNAKE (壬巳) — The Enigmatic Depths
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'water-snake',
  profile: getProfileBySlug('water-snake')!,
  archetype: {
    name: "The Enigmatic Depths",
    tagline: "The Enigmatic Depths — Water Snake",
  },
  atAGlance: {
      "element": "Water (Wisdom, Adaptability, Flow)",
      "energy": "Yin",
      "archetype": "The Enigmatic Depths",
      "coreStrength": "Strategic intuition",
      "shadow": "Secretive manipulation",
      "bestMatch": "metal-rooster",
      "worstMatch": "fire-horse",
      "luckyColor": "Midnight blue"
  },
  personality: {
    body: "The Water Snake moves through life like a river finding its path—unhurried, observant, impossibly patient. You don't announce your presence. You watch, calculate, and act only when the moment tilts in your favor. Water's wisdom combined with Snake's natural cunning creates someone who reads people like open books while remaining an elegant mystery themselves. You don't need to dominate a room; you shape it from the shadows, planting ideas that others believe they thought of first.\n\nYour intuition borders on clairvoyance, not through mysticism but through relentless observation. You notice what people don't say, track patterns others miss, and store information like water filling every crack in stone. This makes you a devastating strategist in business, relationships, and any arena requiring long-term planning. Where other Snakes might strike with venom, you prefer the slow erosion of water—wearing down obstacles so gradually that resistance crumbles without understanding why.\n\nYet beneath this calculated exterior flows genuine depth. Water Snakes possess emotional intelligence that cuts through pretense. You understand human motivation at its rawest level—the fears, desires, and insecurities people hide even from themselves. This can manifest as profound empathy or as a weapon, depending on your alignment. You're drawn to psychology, philosophy, and the hidden mechanics of power not from academic interest but because understanding the invisible currents that move people gives you control over your own fate.\n\nYou need solitude like lungs need air. Social performance drains you, not because you're awkward—you're often magnetically charismatic when needed—but because operating in the world requires you to hide your true depth. Alone, you can finally stop calculating and just exist in the fluid, formless state that feels like home.",
  },
  shadow: {
    body: "Your greatest strength becomes your cage: you manipulate so instinctively that you forget how to be direct. Water Snake shadows play emotional chess with everyone, engineering outcomes through subtle pressure rather than honest conversation. You withhold information as leverage, reveal vulnerabilities strategically, and test loyalty through manufactured scenarios. This creates relationships built on power dynamics rather than trust, leaving you surrounded by people yet fundamentally isolated.\n\nYour patience can curdle into passive-aggressive vindictiveness. You don't explode—you remember. Slights from years ago resurface as cold revenge delivered so subtly the target doesn't connect their current misfortune to ancient offense. This corrodes your spirit more than it harms them. The real trap: you become so comfortable in emotional depth that you mistake brooding for profundity, drowning in your own intensity rather than flowing forward. You can spend years analyzing a wound instead of letting it heal.",
  },
  relationships: {
    body: "You need partners who can handle your depth without demanding you become shallow, who respect your privacy without feeling shut out. The fatal pattern: you attract people drawn to your mystery, then resent them for not truly knowing you—while actively hiding your authentic self. Intimacy terrifies and compels you equally.\n\nYou show love through anticipation—remembering obscure preferences, solving problems before they're voiced, creating safety through invisible attentiveness. But you struggle to receive care that isn't earned or strategic. Genuine vulnerability feels like tactical stupidity. The healthiest relationships for you involve partners secure enough not to pry, intuitive enough to sense your unspoken needs, and patient enough to let you surface in your own time. You thrive with people who appreciate silence, who understand that your withdrawal isn't rejection but necessary restoration. Physical touch often communicates what words can't for you—Water Snakes frequently express through sensation what they lock behind language.",
  },
  elementBalance: {
    body: "Your Water nature needs containment or it disperses into anxiety and paranoia. Establish Metal boundaries: structured routines, clear personal rules, non-negotiable standards that prevent you from shapeshifting into whatever others want. Metal generates Water in the productive cycle—good boundaries actually increase your adaptability by giving you a solid form to return to.\n\nFeed your Water into Wood: create something that grows beyond you. Mentor, write, build projects with legacy. Water generates Wood—your wisdom becomes sterile if hoarded, powerful if it nourishes future growth. Counter Fire environments that evaporate your depth: high-drama people, chaotic workplaces, relationships requiring constant emotional labor. Water controls Fire, but only when you're not already depleted. Practice directness weekly—say one uncomfortably honest thing without strategic calculation. This prevents your natural cunning from becoming pathological.",
  },
  matches: {
      "best": [
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal generates Water—their structured precision gives your depth productive form without demanding you become shallow."
          },
          {
              "slug": "wood-ox",
              "name": "Wood Ox",
              "reason": "You generate their Wood element—your strategic wisdom nourishes their steady growth; they provide grounding without judgment."
          },
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "Metal feeds your Water—their clever boundaries challenge your manipulation positively; intellectual equals who respect your complexity."
          }
      ],
      "worst": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Water controls Fire, creating exhausting power struggle—their impulsive transparency clashes with your calculated mystery; mutual contempt."
          },
          {
              "slug": "fire-tiger",
              "name": "Fire Tiger",
              "reason": "You extinguish their Fire enthusiasm—they demand emotional immediacy you can't provide; they see manipulation where you see strategy."
          },
          {
              "slug": "earth-pig",
              "name": "Earth Pig",
              "reason": "Earth muddies your Water clarity—their naive trust feels like stupidity to you; your depth feels like deception to them."
          }
      ]
  },
}

export default content
