// ============================================
// WATER TIGER (壬寅) — The Intuitive Hunter
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'water-tiger',
  profile: getProfileBySlug('water-tiger')!,
  archetype: {
    name: "The Intuitive Hunter",
    tagline: "The Intuitive Hunter — Water Tiger",
  },
  atAGlance: {
      "element": "Water (Wisdom, Adaptability)",
      "energy": "Yang",
      "archetype": "The Intuitive Hunter",
      "coreStrength": "Strategic intuition",
      "shadow": "Manipulative secrecy",
      "bestMatch": "wood-horse",
      "worstMatch": "earth-monkey",
      "luckyColor": "Midnight blue"
  },
  personality: {
    body: "The Water Tiger combines the raw courage of the Tiger with Water's strategic depth, creating someone who hunts not with blind aggression but with calculated precision. You don't just pounce—you observe, wait, and strike when the moment reveals itself. Where Fire Tigers burn hot and Metal Tigers cut sharp, you flow around obstacles, finding weakness through patience rather than force.\n\nYour Yang energy drives you forward, but Water tempers that charge with wisdom. You're the leader who reads the room before speaking, who knows what people want before they articulate it. This makes you dangerously effective in negotiations, politics, or any arena where understanding human nature matters more than raw power. You collect information like Water collects in low places—naturally, persistently, comprehensively.\n\nWater generates Wood in the elemental cycle, meaning your adaptability fuels growth and expansion. You're not interested in maintaining systems; you're interested in infiltrating them, understanding them, then transforming them from within. Your charisma isn't loud—it's magnetic. People feel drawn to you without knowing why, sensing the depth beneath your calm surface.\n\nYou control Fire, which means you can extinguish hotheaded impulses in yourself and others. When teams panic, you go cold and clear. When others rage, you redirect. This gives you uncanny crisis management ability, but it also means you sometimes withhold emotional warmth when people need reassurance, not strategy. Your confidence comes from preparation—you've already war-gamed seventeen scenarios before anyone else noticed the problem.",
  },
  shadow: {
    body: "Your strategic mind becomes manipulative when threatened. You don't fight fair—you gather secrets, find leverage, and strike at vulnerabilities others don't know they've exposed. Water's nature is to seek the lowest point, and in you, that can mean targeting someone's deepest insecurities rather than addressing conflict directly.\n\nYou hoard information and control access to yourself. People feel they know you, but they don't—you've shown them a carefully curated version. This creates relationships where others are vulnerable while you remain protected, an imbalance that eventually breeds resentment. Your adaptability becomes shapeshifting: you mirror what people want to see, losing track of your actual values in the process.\n\nWhen Water Tigers feel cornered, they don't explode—they go cold, withdraw, and plan revenge. You can hold grudges for years, waiting for the perfect moment to settle scores. Your intuition curdles into paranoia, seeing threats in neutral actions, interpreting kindness as manipulation because that's how you operate.",
  },
  relationships: {
    body: "You need partners who can handle your depth without demanding you perform emotions you're not feeling. You show love through protection and strategic support—remembering details, removing obstacles, anticipating needs—but you struggle with simple verbal affection or physical presence without purpose.\n\nYou're attracted to people with strong Wood energy because Water generates Wood—you naturally want to fuel growth in others. But you need someone who won't let you hide, who calls out your emotional unavailability without triggering your withdrawal reflex. Fire signs fascinate you because you control Fire, but that power dynamic can become toxic if you're not careful.\n\nIn conflict, you go silent and strategic when you should stay present and vulnerable. You need friends who understand that your disappearance isn't rejection—it's how you process—but who also won't let you ghost indefinitely. Your loyalty runs deep as underground rivers, but people can't drink from water they can't access.",
  },
  elementBalance: {
    body: "Your Water excess makes you overly cerebral and emotionally evasive. Build Wood energy through physical growth activities: martial arts that emphasize form development, gardening projects that require sustained attention, mentoring relationships where you must show up consistently.\n\nLimit solitary planning time. Your strategic mind needs constraints or it spirals into paranoid scenario-building. Set a timer for problem-solving, then physically move—your body holds wisdom your mind dismisses. Introduce Fire through deadline-based creative work: performing, public speaking, anything that demands immediate response rather than endless preparation. You need experiences where calculation fails and instinct must carry you.",
  },
  matches: {
      "best": [
          {
              "slug": "wood-horse",
              "name": "Wood Horse",
              "reason": "Water generates Wood—you fuel their adventurous growth while their movement keeps you from stagnating in overthinking."
          },
          {
              "slug": "wood-dog",
              "name": "Wood Dog",
              "reason": "Their loyal transparency balances your secrecy; you provide strategy for their protective instincts."
          },
          {
              "slug": "earth-pig",
              "name": "Earth Pig",
              "reason": "Earth contains Water's overflow—their grounded trust provides safe harbor for your deeper currents."
          }
      ],
      "worst": [
          {
              "slug": "earth-monkey",
              "name": "Earth Monkey",
              "reason": "Earth blocks Water's flow—their need for stability clashes with your fluid tactics, creating mutual frustration."
          },
          {
              "slug": "fire-snake",
              "name": "Fire Snake",
              "reason": "You control Fire but Snake matches your strategic secrecy—two manipulators circling creates paranoid stalemate."
          },
          {
              "slug": "metal-tiger",
              "name": "Metal Tiger",
              "reason": "Metal depletes Water—their rigid principles drain your adaptability while you erode their structure."
          }
      ]
  },
}

export default content
