// ============================================
// WATER DOG (壬戌) — The Faithful Tide
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'water-dog',
  profile: getProfileBySlug('water-dog')!,
  archetype: {
    name: "The Faithful Tide",
    tagline: "The Faithful Tide — Water Dog",
  },
  atAGlance: {
      "element": "Water (Wisdom, Adaptability)",
      "energy": "Yang",
      "archetype": "The Faithful Tide",
      "coreStrength": "Intuitive loyalty",
      "shadow": "Emotional drowning",
      "bestMatch": "wood-rabbit",
      "worstMatch": "fire-dragon",
      "luckyColor": "Midnight blue"
  },
  personality: {
    body: "The Water Dog is loyalty tempered by wisdom, devotion that flows rather than demands. Where other Dogs bark at injustice with rigid righteousness, you sense the deeper currents beneath surface conflicts. Water softens the Dog's typically harsh judgment, creating someone who protects without becoming a tyrant, who serves without martyrdom. You're the friend who shows up at 3am not with lectures but with presence, who reads emotional undercurrents others miss entirely.\n\nYour Yang energy pushes Water's natural contemplation outward into action. You don't just feel deeply—you respond, you intervene, you mobilize. This creates exceptional crisis navigation skills. When chaos erupts, you become eerily calm, channeling panic into purposeful movement. You see twenty steps ahead because Water grants pattern recognition while Dog instinct identifies who needs protection and from what.\n\nThe faithful tide doesn't crash—it surrounds, penetrates, reshapes. You influence through persistent presence rather than dramatic gestures. In groups, you're rarely the loudest voice but somehow your quiet observations shift entire dynamics. People confide in you because you hold their secrets like water holds reflections—perfectly, without distortion or judgment.\n\nYour adaptability isn't weakness—it's strategic fluidity. You change approach without abandoning principles, flowing around obstacles the rigid Dog would exhaust itself attacking. This makes you unexpectedly effective in complex social and professional environments. You achieve Dog's protective goals through Water's indirect methods, understanding that sometimes the most loyal act is letting someone face their own consequences while you wait, ready, at the shore.",
  },
  shadow: {
    body: "Water's depth becomes drowning when you absorb everyone's emotional turbulence without proper boundaries. You collect others' pain like sediment, layer upon layer, until you're so heavy with unprocessed grief—most of it not even yours—that you can barely move. This isn't compassion; it's compulsive emotional hoarding.\n\nYour intuition curdles into paranoid hypervigilance. You sense danger everywhere because Water amplifies Dog's already acute threat detection into exhausting constant scanning. You read betrayal in innocent moments, disloyalty in minor oversights. This prophetic anxiety often creates the very abandonment you fear—people withdraw from your intensity.\n\nWhen hurt, you don't rage like Fire signs—you go cold and deep, nursing resentments in dark internal spaces where they ferment into something toxic. You'll ghost someone completely, cutting them off with Water's absolute boundary while privately replaying their transgressions endlessly. This emotional withholding punishes both parties, leaving relationships frozen in unresolved conflict.",
  },
  relationships: {
    body: "You bond through shared vulnerability and demonstrated reliability over time. Surface charm doesn't move you; you need to witness how someone handles failure, crisis, their own shadows. Once you commit, your loyalty is oceanic—overwhelming, all-encompassing, occasionally suffocating.\n\nYou need partners who can swim in emotional depth without drowning, who understand that your silences aren't rejection but processing time. Someone who mistakes your fluidity for lack of conviction will frustrate you endlessly. You require appreciation for how your indirect approach often accomplishes what direct confrontation cannot.\n\nYour greatest relationship gift is creating safe harbors—spaces where others can be wholly themselves without performance or pretense. You remember everything: the small fears shared at midnight, the dreams mentioned once in passing. This attentiveness builds profound intimacy, though you must resist keeping score of emotional labor invested versus received.",
  },
  elementBalance: {
    body: "Stop absorbing. Distinguish between empathy and emotional merging—you can understand someone's pain without making it your own. Practice literal water immersion: cold showers to shock yourself back into your own body, swimming to remember you're separate from the medium you move through.\n\nFeed Wood to discharge excess Water: create something tangible with your emotional insights. Write, build, grow actual plants. Wood converts Water's swirling depths into upward growth, giving your intuitions material form.\n\nEstablish land boundaries. Schedule containment: specific times for deep feeling, with hard stops. Not every drowning person wants rescue; some need to learn to swim. Your loyalty serves no one when you're depleted.",
  },
  matches: {
      "best": [
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Water generates Wood—your depth nourishes their growth; both value subtle influence over force"
          },
          {
              "slug": "metal-pig",
              "name": "Metal Pig",
              "reason": "Metal generates Water—they provide structure for your flow; shared devotion without Dog's anxiety"
          },
          {
              "slug": "earth-horse",
              "name": "Earth Horse",
              "reason": "Earth contains Water—they ground your depths; Horse's movement prevents stagnation"
          }
      ],
      "worst": [
          {
              "slug": "fire-dragon",
              "name": "Fire Dragon",
              "reason": "Water controls Fire—you dampen their blaze; Dragon's ego clashes with Dog's service orientation"
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Earth controls Water—they dam your flow into rigid channels; double Dog loyalty becomes suffocating duty"
          },
          {
              "slug": "fire-rooster",
              "name": "Fire Rooster",
              "reason": "Water extinguishes Fire—your depth feels threatening to their surface brilliance; critical styles clash destructively"
          }
      ]
  },
}

export default content
