// ============================================
// WATER OX (壬丑) — The Deep Current
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'water-ox',
  profile: getProfileBySlug('water-ox')!,
  archetype: {
    name: "The Deep Current",
    tagline: "The Deep Current — Water Ox",
  },
  atAGlance: {
      "element": "Water (Depth, Wisdom, Adaptability)",
      "energy": "Yin",
      "archetype": "The Deep Current",
      "coreStrength": "Strategic patience",
      "shadow": "Paralysis by overthinking",
      "bestMatch": "water-snake",
      "worstMatch": "fire-horse",
      "luckyColor": "Deep indigo"
  },
  personality: {
    body: "The Water Ox is the reservoir that never runs dry — a being of profound patience backed by strategic intelligence. Where other Oxen charge forward with blunt force, you understand that water carves canyons by persistent flow, not sudden impact. You see patterns others miss because you're willing to wait, watch, and absorb information until the complete picture emerges. This isn't indecision; it's tactical genius wrapped in quiet observation.\n\nYour Ox nature gives you legendary endurance and reliability, but Water adds something the other Oxen lack: flexibility in method while maintaining absolute clarity of destination. You'll change your approach a dozen times if needed, flowing around obstacles rather than battering through them. People mistake this adaptability for weakness until they realize you've already won by the time they figured out the game. You build systems, relationships, and projects with the understanding that depth matters more than speed.\n\nIn work environments, you're the person who sees the flaw in the plan during the first meeting but stays silent until you've mapped every consequence. When you finally speak, your insights carry the weight of thorough consideration. You excel in roles requiring long-term strategy, crisis management, or rebuilding what others have destroyed. Your emotional intelligence is sharper than people expect from an Ox — Water gives you the ability to read undercurrents in group dynamics, sensing tension before it surfaces.\n\nYour greatest asset is this combination: Ox tenacity meeting Water wisdom. You don't just endure hardship; you study it, learn from it, and emerge with knowledge that becomes your next advantage. Where Fire Oxen burn out and Earth Oxen become rigid, you remain fluid yet unbreakable.",
  },
  shadow: {
    body: "Your strategic mind becomes your prison when Water stagnates. You overthink until simple decisions become paralysis — analyzing every angle, anticipating every consequence, drowning in your own depth. This isn't careful consideration anymore; it's fear disguised as wisdom. You'll spend months researching the perfect approach while opportunities evaporate, convincing yourself you're being prudent when you're actually hiding.\n\nWhen threatened, you don't fight or flee — you flood. Emotional withdrawal becomes your weapon, going cold and silent in ways that punish others through absence. You'll cut people off completely, ghosting relationships rather than confronting conflict directly. This passive-aggressive iciness feels like protection but leaves you isolated in your own deep water, bitter that no one understands you while refusing to let anyone close enough to try. Your Ox stubbornness combines with Water's tendency to pool in dark places, creating grudges that calcify into permanent resentment.",
  },
  relationships: {
    body: "You love like deep water — still on the surface, powerful underneath. Partners need to understand that your emotional reserve isn't coldness; it's the time you need to fully process feelings before expressing them. You're intensely loyal once committed, but getting you to that commitment requires someone patient enough to let trust accumulate gradually. You don't do whirlwind romances; you do slow-building bonds that become unshakeable.\n\nYou need partners who respect your need for solitary processing time and don't mistake your silence for disengagement. Your ideal match understands that you show love through consistent action and strategic support rather than dramatic gestures. You remember everything — birthdays, offhand comments about preferences, patterns in their behavior — and use this knowledge to care for them in quietly profound ways.\n\nYour challenge is learning that vulnerability isn't weakness and that sometimes relationships need the mess of immediate emotional expression rather than perfectly processed responses delivered three days later. You must resist the urge to solve your partner's problems when they just need you to feel with them.",
  },
  elementBalance: {
    body: "When Water stagnates, introduce Wood energy — start projects that force forward movement. Plant something. Write daily, even badly. Wood draws Water upward, breaking paralysis through growth-oriented action. Set artificial deadlines to prevent endless rumination.\n\nStrengthen Fire to counter excessive coldness: engage in activities that demand immediate response without analysis. Dance. Play competitive games. Fire warms Water into productive circulation rather than stagnant pooling.\n\nAvoid excess Metal energy, which generates more Water you don't need — too much structure, perfectionism, and rigid planning only deepens your overthinking. Your Ox nature already provides plenty of discipline.\n\nPhysical practice: moving water meditation. Stand in flowing streams, take cold showers mindfully, swim in natural bodies of water. Remind your body that Water's nature is movement, not stillness.",
  },
  matches: {
      "best": [
          {
              "slug": "water-snake",
              "name": "Water Snake",
              "reason": "Double Water creates profound mutual understanding; both value strategic depth and patient wisdom without pressuring for premature action"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal generates Water in productive cycle; Rooster's precision channels your depth into structured brilliance without drowning in it"
          },
          {
              "slug": "earth-rat",
              "name": "Earth Rat",
              "reason": "Earth controls Water beneficially here; Rat's resourcefulness gives your strategy practical outlets, grounding wisdom into tangible results"
          }
      ],
      "worst": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Water controls Fire destructively; your cautious depth clashes with Horse's impulsive speed, each frustrating the other's core operating rhythm"
          },
          {
              "slug": "fire-goat",
              "name": "Fire Goat",
              "reason": "You'll drown their creative Fire with excessive analysis; Goat needs emotional warmth you struggle to provide when Water runs cold"
          },
          {
              "slug": "wood-tiger",
              "name": "Wood Tiger",
              "reason": "While Water generates Wood, Tiger's explosive growth overwhelms your need for controlled, strategic development — too much chaos for your depth"
          }
      ]
  },
}

export default content
