// ============================================
// WATER MONKEY (壬申) — The Quicksilver Mind
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'water-monkey',
  profile: getProfileBySlug('water-monkey')!,
  archetype: {
    name: "The Quicksilver Mind",
    tagline: "The Quicksilver Mind — Water Monkey",
  },
  atAGlance: {
      "element": "Water (Wisdom, Adaptability)",
      "energy": "Yang",
      "archetype": "The Quicksilver Mind",
      "coreStrength": "Strategic fluidity",
      "shadow": "Slippery evasion",
      "bestMatch": "wood-dragon",
      "worstMatch": "fire-horse",
      "luckyColor": "Midnight blue"
  },
  personality: {
    body: "Water Monkey possesses the most adaptable intelligence in the zodiac — a mind that flows around obstacles rather than confronting them head-on. Where other Monkeys rely on quick wit and performance, you operate through strategic observation and psychological insight. Water's wisdom tempers Monkey's restless energy, creating someone who reads situations with uncanny accuracy before making a move. You don't just solve problems; you dissolve them by finding the path of least resistance.\n\nYour genius lies in understanding hidden motivations and unspoken dynamics. You watch people the way water studies stone — patiently, constantly, until you know exactly where the cracks are. This isn't manipulation for sport like other Monkeys; it's strategic positioning. You genuinely prefer elegant solutions to flashy victories. When others are still arguing their positions, you've already shifted the entire conversation in your preferred direction without anyone noticing.\n\nThe Yang energy keeps you from Water's typical passivity. You're contemplative but not paralyzed, strategic but not stagnant. You move when the timing is perfect, not a moment before or after. This makes you maddeningly effective in negotiations, politics, or any arena requiring both patience and opportunism. You can wait years for the right moment, then strike with decisive clarity.\n\nYour humor runs dark and observational. You notice the absurdities others miss because you're always slightly outside the action, watching the patterns. People find you charming but can't quite pin you down — you're friendly without being known, helpful without being committed. You collect information like water collects sediment, and you remember everything. This makes you an invaluable ally and a dangerous enemy, though you'd prefer neither label. You'd rather be the one who quietly influenced the outcome without being credited or blamed.",
  },
  shadow: {
    body: "Your adaptability becomes evasion when threatened. You'll slip away from commitment, accountability, or difficult emotions with such practiced ease that people don't realize you've vanished until you're gone. You rationalize this as strategic flexibility, but it's often just fear of being pinned down or truly known. Water Monkey can spend entire relationships being present but unavailable, helpful but uncommitted.\n\nYou manipulate through omission and misdirection. You don't lie outright — that's too obvious — you just let people believe convenient misunderstandings. You'll watch someone struggle when you could help, simply because correcting them doesn't serve your interests. This casual withholding of truth corrodes trust slowly, like water eroding stone.\n\nWhen anxious, you over-analyze until you're paralyzed by contingencies. The same strategic mind that makes you brilliant becomes a prison of endless \"what-ifs.\" You'll delay decisions indefinitely, always waiting for more information, better timing, clearer conditions. Meanwhile, opportunities dissolve. Your fear of making the wrong move prevents you from making any move at all.",
  },
  relationships: {
    body: "You need partners who can handle your emotional fluidity without demanding constant definition. You show love through attention and strategic support — remembering details, anticipating needs, removing obstacles from their path. But you struggle with direct emotional expression. \"I love you\" feels too fixed, too exposed. You'd rather demonstrate through action than declare through words.\n\nYou're drawn to people who respect your need for psychological space. Clingy partners trigger your evasion instinct immediately. You need someone who understands that your withdrawal isn't rejection — it's how you process and recalibrate. The right partner gets periodic distance without drama and full presence when you resurface.\n\nYour greatest relationship gift is seeing people clearly without judgment. You observe their patterns, their defenses, their hidden hopes, and you work with what's actually there rather than some idealized version. This makes you remarkably effective at helping people grow — when you choose to invest that attention. Your greatest failure is withholding that gift when it requires emotional risk on your part, leaving partners feeling seen but not known in return.",
  },
  elementBalance: {
    body: "Stop circling and commit to something concrete. Your Water nature generates Wood — growth requires roots, not just flow. Pick one project, one relationship, one goal and stay with it through discomfort. Set artificial deadlines; your natural timing is often just sophisticated procrastination.\n\nWater controls Fire, so you extinguish your own passion when imbalanced. Schedule spontaneity. Force yourself into situations where you can't prepare or strategize. Say yes before you've calculated all angles. Your growth lives in the messy, uncontrolled moments you typically avoid.\n\nPhysically ground yourself. Winter energy needs counterbalance — hot baths, spicy food, vigorous exercise that generates heat. Create friction deliberately. Your tendency is to eliminate resistance; sometimes resistance is exactly what you need.",
  },
  matches: {
      "best": [
          {
              "slug": "wood-dragon",
              "name": "Wood Dragon",
              "reason": "Water generates Wood — you provide the strategic depth that channels their visionary momentum into sustainable growth."
          },
          {
              "slug": "wood-rat",
              "name": "Wood Rat",
              "reason": "Shared intelligence and resourcefulness, with Water feeding their Wood ambitions while they provide practical grounding."
          },
          {
              "slug": "metal-snake",
              "name": "Metal Snake",
              "reason": "Metal generates Water — their philosophical structure deepens your intuitive wisdom without demanding emotional transparency."
          }
      ],
      "worst": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Water controls Fire — your strategic caution extinguishes their spontaneous momentum, creating mutual frustration and stagnation."
          },
          {
              "slug": "fire-tiger",
              "name": "Fire Tiger",
              "reason": "Their direct Yang Fire approach clashes with your indirect Water method — they see evasion where you see strategy."
          },
          {
              "slug": "earth-ox",
              "name": "Earth Ox",
              "reason": "Earth blocks Water's flow — their rigid structures and demand for straightforward commitment trigger your escape instincts."
          }
      ]
  },
}

export default content
