// ============================================
// WATER RAT (壬子) — The Fluid Strategist
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'water-rat',
  profile: getProfileBySlug('water-rat')!,
  archetype: {
    name: "The Fluid Strategist",
    tagline: "The Fluid Strategist — Water Rat",
  },
  atAGlance: {
      "element": "Water (Wisdom, Adaptation, Flow)",
      "energy": "Yang",
      "archetype": "The Fluid Strategist",
      "coreStrength": "Adaptive intelligence",
      "shadow": "Evasive manipulation",
      "bestMatch": "metal-ox",
      "worstMatch": "fire-horse",
      "luckyColor": "Midnight blue"
  },
  personality: {
    body: "Water Rats embody the marriage of elemental depth and animal cunning. Where other Rats scheme loudly, you plot in silence, reading currents others don't perceive. Your Water element grants you the wisdom to wait—unusual for the typically impatient Rat—and the intelligence to know exactly when stillness serves better than motion. You don't just adapt to circumstances; you dissolve resistance through patient erosion, wearing down obstacles the way rivers carve canyons.\n\nYour strategic mind operates on multiple timescales simultaneously. You're planning three moves ahead while appearing casually engaged in the present moment. This dual awareness makes you exceptionally difficult to outmaneuver. Unlike the frantic energy of Fire Rats or the accumulative drive of Earth Rats, you understand that power flows to those who control information and timing. You collect knowledge the way water collects in low places—naturally, inevitably, without announcement.\n\nThe Yang energy of the Rat keeps you from Water's tendency toward complete passivity. You're contemplative but not paralyzed, flexible but not spineless. When you move, it's with decisive force, like a dam breaking. People underestimate you because your softness seems like weakness, but you know that water cuts stone given enough time. Your humor is wry and observant, your social skills impeccable, your networking instincts legendary. You understand that influence is about connection, not domination.\n\nYour challenge is distinguishing between strategic flexibility and directionless drift. Water seeks the path of least resistance, and the Rat seeks advantage—together, these can create someone who's so busy being clever they forget to commit to anything substantial. You need projects that reward long-term vision, environments where your capacity for deep observation translates into meaningful action.",
  },
  shadow: {
    body: "Your greatest weakness is using intelligence as an excuse for emotional evasion. When confronted, you become slippery—changing the subject, reframing the question, disappearing into vagueness. This isn't adaptation; it's avoidance dressed in philosophical clothing. You can manipulate through withholding, control through confusion, maintaining power by keeping others off-balance.\n\nWater Rats at their worst become information hoarders who weaponize what they know. You'll collect secrets not for strategic value but for the sense of superiority it provides. Your flexibility can degrade into opportunism—you'll shift positions so frequently that no one, including yourself, remembers what you actually believe. The Rat's survival instinct combined with Water's formlessness creates someone who's never quite present, never fully committed, always keeping an exit strategy active even in relationships that deserve loyalty. You rationalize betrayal as pragmatism and call emotional unavailability wisdom.",
  },
  relationships: {
    body: "You need partners who can handle your depth without requiring constant emotional demonstration. You show love through attentiveness, through remembering details, through strategic support—not through dramatic declarations. The right person appreciates that your silence isn't absence but observation, that your questions mean you're engaged, that your flexibility is a gift not a flaw.\n\nYou're drawn to people with clear structure because they provide the containment Water lacks. Metal and Earth types often work well—they give you boundaries to flow within rather than against. You despise emotional manipulation and respect directness, even when it's uncomfortable. Your intimacy deepens slowly, like water seeping into soil, but once you commit, your loyalty runs to surprising depths.\n\nThe problem emerges when you use your perceptiveness to stay two steps emotionally removed. You'll analyze your partner's needs instead of stating your own, manage the relationship instead of participating in it. Real connection requires you to occasionally be pinned down, to make declarations you can't later reinterpret.",
  },
  elementBalance: {
    body: "You need deliberate structure to prevent endless drift. Set external commitments with consequences—deadlines you can't talk your way out of, partnerships where others depend on your follow-through. Water generates Wood in the elemental cycle, so engage in projects with visible growth: writing that accumulates into a body of work, investments that compound, skills that develop through practice.\n\nPhysically, you need to combat Water's tendency toward stagnation. Moving water stays fresh; still water breeds problems. Regular exercise that involves flow states—swimming, martial arts, dance—keeps your energy cycling. Create routines around your flexibility rather than rejecting structure entirely. Spend time with Fire types who won't let you hide in ambiguity; they'll force you to commit and clarify, which generates the creative tension you need to avoid becoming formless.",
  },
  matches: {
      "best": [
          {
              "slug": "metal-ox",
              "name": "Metal Ox",
              "reason": "Metal generates Water and provides the structural containment that channels your strategic flow into sustained achievement"
          },
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "Metal feeds your depth while Monkey's cleverness matches your intelligence without competing for the same strategic territory"
          },
          {
              "slug": "wood-pig",
              "name": "Wood Pig",
              "reason": "You generate Wood's growth, and Pig's sincerity grounds your tendency toward excessive calculation in genuine connection"
          }
      ],
      "worst": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Water controls Fire in destructive cycle; Horse's need for freedom clashes with Rat's territorial instincts—mutual frustration"
          },
          {
              "slug": "fire-goat",
              "name": "Fire Goat",
              "reason": "Your Water dampens their Fire's creative expression, while Goat's emotional demands overwhelm your calculated approach"
          },
          {
              "slug": "earth-horse",
              "name": "Earth Horse",
              "reason": "Earth blocks Water's flow and Horse's independence triggers Rat's controlling tendencies—stalemate through opposition"
          }
      ]
  },
}

export default content
