// ============================================
// WATER GOAT (壬未) — The Empathic Healer
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'water-goat',
  profile: getProfileBySlug('water-goat')!,
  archetype: {
    name: "The Empathic Healer",
    tagline: "The Empathic Healer — Water Goat",
  },
  atAGlance: {
      "element": "Water (Wisdom, Adaptability)",
      "energy": "Yin",
      "archetype": "The Empathic Healer",
      "coreStrength": "Emotional depth",
      "shadow": "Absorbing toxicity",
      "bestMatch": "wood-rabbit",
      "worstMatch": "fire-horse",
      "luckyColor": "Deep indigo"
  },
  personality: {
    body: "The Water Goat moves through life like a stream finding its course—gentle, persistent, reshaping itself around obstacles rather than confronting them head-on. This is the zodiac's natural empath, someone who doesn't just understand others' emotions but physically feels them. Water amplifies the Goat's already sensitive nature, creating an individual who reads unspoken pain like others read books. You don't just listen to people's problems; you metabolize them, process them through your own system until you find the thread of healing.\n\nYour wisdom comes from depth, not speed. While others rush to conclusions, you sink into the complexity of situations, understanding that most problems have emotional roots that logic alone cannot reach. Water's adaptability means you can shift your approach depending on who needs you—firm boundaries with manipulators, soft compassion with the wounded, playful distraction for the overwhelmed. This fluidity makes you an exceptional mediator, therapist, artist, or anyone whose work requires emotional intelligence and nuanced perception.\n\nBut this element doesn't make you weak. Water controls Fire in the elemental cycle—you have an uncanny ability to calm rage, cool heated conflicts, and dissolve aggressive energy through strategic withdrawal or redirection. You don't fight battles; you make them irrelevant. Your creativity flows naturally, often expressed through writing, music, or visual arts that channel the emotional undercurrents you constantly swim through. You need solitude like others need air, not because you're antisocial but because you must regularly empty the emotional bucket you've been filling all day.",
  },
  shadow: {
    body: "Your empathy becomes your poison when you lose the boundary between feeling with someone and becoming them. You absorb toxic people's energy and call it compassion, carrying their dysfunction until it manifests as your own anxiety, depression, or physical exhaustion. Water's nature is to merge and dissolve, but you take this too far—sacrificing your needs, ignoring your own pain, martyring yourself on the altar of everyone else's comfort. You mistake self-abandonment for kindness.\n\nWater Goats drown in indecision, overthinking every choice until the opportunity passes. Your ability to see multiple perspectives curdles into paralysis. You say yes when you mean no, avoid confrontation until resentment builds like stagnant water, then either explode inappropriately or sink into passive-aggressive withdrawal. Your need for approval makes you pliable to manipulation—you'd rather twist yourself into uncomfortable shapes than risk someone's disappointment. When overwhelmed, you escape: substances, fantasy, sleep, anything to avoid the flooding feelings you can't process.",
  },
  relationships: {
    body: "You need partners who appreciate your depth without exploiting it. The right person understands that your sensitivity is strength, not weakness—they protect your boundaries when you forget to, remind you that you're allowed to have needs, and don't dump their unprocessed trauma onto you expecting free therapy. You give so naturally that you often attract takers; learning to notice this pattern before you're drained is your relationship curriculum.\n\nYou bond through emotional honesty and shared vulnerability. Small talk exhausts you; you want the real conversation beneath the surface pleasantries. In love, you're devoted almost to a fault, anticipating needs before they're spoken, creating sanctuary for your person to be fully themselves. But you need reciprocity—not grand gestures, but genuine care for your inner world. You shut down with criticism, blossom with gentleness. The relationship dynamic you must avoid: becoming the emotional parent to a perpetual child who takes your nurturing as their birthright.",
  },
  elementBalance: {
    body: "Balance your Water by generating Wood—channel that emotional absorption into creative output. Write, paint, garden, build something. Wood uses Water's flow productively instead of letting it pool into stagnation. Establish physical boundaries: time limits on emotionally draining people, literal closed doors for solitude, saying no as a complete sentence. Practice the Fire you control: assert yourself, speak directly, let some conflicts exist without drowning them in accommodation. Near actual water regularly—you need it to discharge the emotional static you collect. But also get warm and dry: heat, sunlight, vigorous movement to prevent the cold dampness that leads to rumination and melancholy.",
  },
  matches: {
      "best": [
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Water generates Wood—you nourish their growth while their gentle structure gives your flow direction and purpose."
          },
          {
              "slug": "wood-pig",
              "name": "Wood Pig",
              "reason": "Water feeds Wood's expansion—shared empathy and idealism, but Pig's optimism prevents your melancholic spirals."
          },
          {
              "slug": "metal-pig",
              "name": "Metal Pig",
              "reason": "Metal generates Water—their principled clarity channels your emotional depth into purposeful compassion rather than diffusion."
          }
      ],
      "worst": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Water controls Fire—your need for depth clashes with their restless independence; you drown their flame, they evaporate your peace."
          },
          {
              "slug": "earth-ox",
              "name": "Earth Ox",
              "reason": "Earth controls Water—their rigidity dams your flow; you feel contained and judged, they see you as scattered and impractical."
          },
          {
              "slug": "fire-rooster",
              "name": "Fire Rooster",
              "reason": "Water destroys Fire—your indirect style frustrates their blunt precision; they scorch your sensitivity, you dampen their enthusiasm."
          }
      ]
  },
}

export default content
