// ============================================
// WATER HORSE (壬午) — The Adaptive Nomad
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'water-horse',
  profile: getProfileBySlug('water-horse')!,
  archetype: {
    name: "The Adaptive Nomad",
    tagline: "The Adaptive Nomad — Water Horse",
  },
  atAGlance: {
      "element": "Water (Adaptability, Depth)",
      "energy": "Yang",
      "archetype": "The Adaptive Nomad",
      "coreStrength": "Fluid independence",
      "shadow": "Directionless drifting",
      "bestMatch": "wood-tiger",
      "worstMatch": "fire-horse",
      "luckyColor": "Midnight blue"
  },
  personality: {
    body: "The Water Horse is a paradox in motion — a restless spirit tempered by emotional intelligence. Where typical Horses bolt toward goals with single-minded intensity, you flow around obstacles like water finding multiple paths downhill. This makes you the most strategically flexible of all Horse types, capable of pivoting careers, relationships, or entire life directions without the existential panic others experience. You read social currents instinctively, knowing when to push forward and when to let circumstances carry you.\n\nYour Water element brings depth to the Horse's natural charisma. You don't just charm people — you actually listen to them, absorbing their stories and motivations. This makes you exceptional in roles requiring genuine human connection: counseling, negotiation, investigative work, or any field where understanding subtext matters more than surface performance. Unlike more rigid Horse types, you can work within systems you don't fully respect, biding your time until conditions shift in your favor.\n\nThe Yang energy ensures you never become passive despite Water's receptive nature. You're adaptive, not accommodating. When you change direction, it's strategic repositioning, not surrender. You travel light emotionally and materially, understanding that attachment creates drag. This gives you remarkable resilience — job loss, relationship endings, even geographic upheaval rarely devastates you because you trusted the impermanence all along. You recover faster than others because you never fully committed to the illusion of permanence.\n\nYour gift is reading the flow of circumstances and adjusting your course without losing momentum. While others fight upstream or get stuck in eddies of indecision, you find the channel that carries you forward with minimal resistance. This isn't laziness — it's sophisticated pattern recognition applied to life itself.",
  },
  shadow: {
    body: "Your adaptability becomes evasion when you flow away from every commitment that demands sustained effort. You rationalize serial abandonment as \"following the path of least resistance,\" but sometimes resistance exists because the goal matters. You can spend decades sampling experiences without mastering anything, mistaking variety for growth. Relationships suffer particularly — you're emotionally present until depth requires vulnerability, then suddenly you're \"not ready\" or \"need space\" or discover some fundamental incompatibility you ignored for months.\n\nThe darker manifestation is manipulative fluidity. Because you read people so well, you know which version of yourself each person wants to see. You shape-shift through social contexts without a stable core, becoming whoever opens doors or avoids conflict. This creates a hollow center — you've adapted so thoroughly to external currents that you've lost track of your own desires. Eventually, you wake up living someone else's life, wondering how you drifted so far from shore. Your fear of stagnation can become its own prison, where you're constantly moving but never arriving anywhere that matters.",
  },
  relationships: {
    body: "You need partners who provide direction without rigidity — think lighthouse, not anchor. The worst match is someone who either demands you stay still or drifts as aimlessly as you can. You thrive with people who have clear values and goals but respect your need for autonomous navigation. They should call you on evasive behavior without trying to control your route.\n\nIn practice, you're the partner who's genuinely interested in others' internal worlds, asking follow-up questions weeks later about things they mentioned in passing. But you struggle with the repetitive maintenance of long-term intimacy — the daily check-ins, the predictable anniversaries, the sustained presence through boring stretches. You're exceptional in crisis, adapting to sudden challenges with calm resourcefulness, but you get restless during stable periods.\n\nYou express love through understanding rather than grand gestures, through being exactly who your partner needs in shifting circumstances. The challenge is letting yourself be known with equal depth. Practice revealing your own uncertainties instead of just absorbing others'. The right relationship doesn't pin you down — it gives you a home base from which to wander, and a reason to return.",
  },
  elementBalance: {
    body: "Water already dominates your nature, so balance means adding structure without rigidity. Commit to one skill or project for a fixed period — not forever, just long enough to experience depth rather than perpetual sampling. Set arbitrary boundaries: \"I will stay in this city for two years\" or \"I will see this relationship through one full seasonal cycle before evaluating.\" The timeline matters less than practicing sustained presence.\n\nPhysically, engage practices that build consistent patterns: daily morning routines, regular meal times, weekly commitments. Not to restrict you, but to create a stable container for your fluid nature. Think of it as riverbanks — they don't stop the water's flow, they give it direction and power. When you feel the urge to flee, pause and ask: \"Am I responding to genuine misalignment, or just discomfort with stability?\" Sometimes staying is the most radical adaptation available.",
  },
  matches: {
      "best": [
          {
              "slug": "wood-tiger",
              "name": "Wood Tiger",
              "reason": "Water nourishes Wood — your adaptability fuels their growth-oriented courage, creating expansive adventures with emotional intelligence."
          },
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Your depth meets their diplomatic grace; Water generates Wood, and you provide the emotional flow their social skill channels beautifully."
          },
          {
              "slug": "metal-dog",
              "name": "Metal Dog",
              "reason": "Water carries Metal — their loyal principles give your fluidity purpose, while you soften their rigidity with adaptive wisdom."
          }
      ],
      "worst": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Water controls Fire — you dampen their intensity while they evaporate your depth, creating frustrating mutual nullification."
          },
          {
              "slug": "earth-ox",
              "name": "Earth Ox",
              "reason": "Earth blocks Water — their immovable stability feels like suffocation, while your constant flowing reads as flakiness to their steadfast nature."
          },
          {
              "slug": "fire-dog",
              "name": "Fire Dog",
              "reason": "You extinguish their passionate idealism with cool pragmatism, while their moral intensity feels exhaustingly rigid to your adaptive ethics."
          }
      ]
  },
}

export default content
