// ============================================
// WATER PIG (壬亥) — The Boundless Heart
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'water-pig',
  profile: getProfileBySlug('water-pig')!,
  archetype: {
    name: "The Boundless Heart",
    tagline: "The Boundless Heart — Water Pig",
  },
  atAGlance: {
      "element": "Water (Wisdom, Depth, Flow)",
      "energy": "Yin",
      "archetype": "The Boundless Heart",
      "coreStrength": "Infinite compassion",
      "shadow": "Emotional flooding",
      "bestMatch": "wood-rabbit",
      "worstMatch": "fire-snake",
      "luckyColor": "Midnight blue"
  },
  personality: {
    body: "You are Water amplifying Pig—depth meeting indulgence, wisdom fused with generosity. Where other Pigs scatter their warmth, you direct yours with emotional intelligence and intuitive precision. Water gives you insight into hidden currents in every room, every relationship, every unspoken need. You don't just feel—you read the temperature of collective emotion and adjust yourself accordingly. This makes you the confidant everyone seeks when life fractures, the steady presence when chaos reigns.\n\nYour compassion isn't performative. It's oceanic—vast, genuine, occasionally overwhelming. You absorb others' pain like a sponge, genuinely believing you can transmute suffering through sheer empathetic force. This isn't naive optimism; it's Water's understanding that nothing is permanent, that all states can shift. You trust in flow. When others panic at obstacles, you simply find another route. Your adaptability isn't weakness—it's strategic fluidity. You'll change your approach seventeen times without losing sight of your goal: creating warmth, connection, comfort.\n\nWater Pig doesn't perform generosity—you embody it. Your home becomes a refuge. Your table, perpetually set for unexpected guests. Your phone, always on for late-night crisis calls. But here's where Water's wisdom emerges: unlike Earth Pig's dutiful service or Fire Pig's exuberant hosting, you give from deep reserves that regenerate through solitude and reflection. You know when to retreat. You understand that your power comes from stillness, from the quiet moments where you recharge your emotional batteries. The best version of you balances boundless giving with fierce protection of your inner sanctuary.",
  },
  shadow: {
    body: "Water's depth becomes drowning when unbalanced. You don't just feel emotions—you marinate in them, sometimes until they pickle. Your empathy turns parasitic, absorbing others' darkness until you can't distinguish their pain from yours. You say yes when you mean no, not from people-pleasing but from genuine inability to witness disappointment. This creates resentment that pools in your depths, unexpressed, until it poisons your relationships from beneath.\n\nYour adaptability degrades into shapelessness. Without boundaries, you become whoever others need, losing your outline entirely. Friends describe you as \"so understanding\" while secretly wondering if you have opinions. Your fear of conflict—Water's tendency to flow around obstacles—means you avoid necessary confrontations until problems metastasize. You'll ghost rather than argue, dissolve rather than define limits. The shadow Water Pig sacrifices selfhood on the altar of harmony, then wonders why they feel invisible.",
  },
  relationships: {
    body: "You connect through emotional availability and non-judgmental presence. Partners feel seen in ways they've never experienced—you intuit needs before they're voiced, create safety for vulnerability, hold space for transformation. But you need someone who won't drain your reserves, who understands that your depth requires periods of surface calm.\n\nYou're drawn to damaged souls, believing your Water can heal all wounds. Sometimes it can. Often it can't. The healthiest relationships for you involve mutual replenishment—partners who fill your cup as you fill theirs. You need someone who respects your disappearing acts, who doesn't interpret your need for solitude as rejection. Physical affection matters less than emotional intimacy; you bond through late-night conversations and shared silence. You're loyal to a fault, staying in relationships long past their expiration because you see potential, not reality. Learning to release what no longer flows is your relational lesson.",
  },
  elementBalance: {
    body: "You need Wood—direction for your flow. Plant gardens, literally or metaphorically. Set morning routines that give structure to your formless days. Create projects with defined endpoints rather than endless emotional maintenance.\n\nReduce Water excess: limit alcohol and excessive fluids before bed. Avoid doom-scrolling that floods you with others' suffering. Install genuine boundaries—practice the phrase \"I need time to consider that.\" Schedule deliberate solitude as fiercely as you schedule helping others. Use Earth's stability: walk barefoot, work with clay, cook one-pot meals that ground your scattered energy. Fire activities in moderation—dance, bright lights, social events—to evaporate stagnant emotion. Your balance comes from remembering you're a river, not a reservoir. Flow requires both giving and receiving.",
  },
  matches: {
      "best": [
          {
              "slug": "wood-rabbit",
              "name": "Wood Rabbit",
              "reason": "Water nourishes Wood's growth; Rabbit's gentleness matches your emotional depth without exploitation"
          },
          {
              "slug": "wood-goat",
              "name": "Wood Goat",
              "reason": "You feed their creativity while they provide artistic structure for your formless compassion"
          },
          {
              "slug": "metal-dog",
              "name": "Metal Dog",
              "reason": "Metal contains Water's overflow; Dog's loyalty provides the secure container you need to pour freely"
          }
      ],
      "worst": [
          {
              "slug": "fire-snake",
              "name": "Fire Snake",
              "reason": "Water controls Fire but Snake's intensity evaporates your depth; mutual exhaustion through elemental opposition"
          },
          {
              "slug": "fire-monkey",
              "name": "Fire Monkey",
              "reason": "Their chaos disrupts your need for emotional flow; you dampen their spark, they mock your sensitivity"
          },
          {
              "slug": "earth-dragon",
              "name": "Earth Dragon",
              "reason": "Earth dams Water's natural movement; Dragon's dominance muddies your clarity into stagnant compliance"
          }
      ]
  },
}

export default content
