// ============================================
// WOOD ROOSTER (甲酉) — The Principled Craftsman
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'wood-rooster',
  profile: getProfileBySlug('wood-rooster')!,
  archetype: {
    name: "The Principled Craftsman",
    tagline: "The Principled Craftsman — Wood Rooster",
  },
  atAGlance: {
      "element": "Wood (Growth, Flexibility, Vision)",
      "energy": "Yin",
      "archetype": "The Principled Craftsman",
      "coreStrength": "Ethical precision",
      "shadow": "Moralistic rigidity",
      "bestMatch": "fire-snake",
      "worstMatch": "metal-rabbit",
      "luckyColor": "Jade green"
  },
  personality: {
    body: "The Wood Rooster combines the Rooster's exacting standards with Wood's capacity for growth and ethical vision. You're not just meticulous—you're meticulous in service of something larger. Where Metal Roosters enforce rules for order's sake, you enforce principles because you genuinely believe in cultivating a better world. Your criticism cuts, but it comes from wanting people to reach their potential, not from petty judgment.\n\nWood gives your Rooster precision a forward-thinking quality. You see the blueprint for how things should develop over time. You're the project manager who doesn't just check boxes but considers whether the entire framework serves growth. You'll redesign systems if they stifle development, even when everyone else wants to maintain the status quo. This makes you an exceptional mentor when you channel your detail-orientation toward nurturing others' skills rather than just correcting their mistakes.\n\nYour Yin energy means you work through persistent, patient pressure rather than dramatic displays. You don't announce your standards—you embody them daily. People notice your consistency before they notice your intensity. You're the colleague who quietly improves every process you touch, whose ethical stance becomes obvious through accumulated actions rather than speeches.\n\nThe Wood-Rooster tension creates interesting dynamics. Wood wants flexibility and expansion; Rooster demands precision and control. You resolve this by becoming principled rather than rigid—you adapt methods but never compromise core values. You'll change the entire approach if it serves your ethical vision, but you won't cut corners. This makes you formidable in fields requiring both integrity and innovation: sustainable design, ethical technology, educational reform, craftsmanship with conscience.",
  },
  shadow: {
    body: "Your ethical precision turns moralistic when Wood's growth drive fixates on 'improving' others. You stop nurturing potential and start enforcing your vision of what people should become. The Rooster's critical eye, filtered through Wood's idealism, produces someone who doesn't just notice flaws but feels personally offended by others' lack of development. You lecture. You over-explain why your way serves everyone's growth, when really you're just controlling.\n\nWood imbalance makes you self-righteous. You convince yourself your rigidity is actually principled flexibility, that your frustration is compassionate disappointment. You stop seeing people as they are and only see how far they fall short of your standards. The craftsman becomes the taskmaster. You micromanage under the guise of mentorship, criticize under the banner of helping people grow.\n\nWhen stressed, you become the worst of both elements: Wood's judgmental superiority meeting Rooster's nitpicking perfectionism. You create impossible standards, then feel betrayed when others don't meet them. Your ethical vision becomes an excuse for chronic dissatisfaction with reality.",
  },
  relationships: {
    body: "You need partners who respect your principles but won't accept your lectures. Someone who can say 'I hear your values, now stop managing my growth' without triggering your corrective instincts. You're intensely loyal once you've decided someone meets your ethical standards—the challenge is not making people audition forever for your approval.\n\nIn intimacy, you show love through wanting to build something meaningful together, through consistent presence rather than grand gestures. But you have to resist treating relationships like improvement projects. Your partner is not lumber to be shaped into furniture. Wood Roosters in healthy relationships learn that accepting someone fully is different from lowering standards—it's recognizing that your vision isn't the only valid path of growth.\n\nYou're drawn to people who share your values but express them differently, who remind you that principles can manifest in various forms. Fire signs energize your vision without threatening your precision. Earth signs ground your ideals in practical reality.",
  },
  elementBalance: {
    body: "Balance excess Wood by practicing acceptance without abandonment of standards—witness without intervening. Physical craftsmanship helps: woodworking, gardening, cooking. Activities where you shape materials that don't have feelings to hurt when you demand precision.\n\nWhen you feel moralistic, add Fire: socialize your vision outward into genuine inspiration rather than inward into judgment. Teach workshops. Share your craft publicly. Fire transforms Wood's growth drive from control into contagious enthusiasm.\n\nGround in Earth weekly: finish something simple with no higher purpose. Clean a room. Organize files. Let the Rooster perfect something mundane so it stops trying to perfect people's souls. Metal helps too—structured reflection time where you examine whether your 'principles' are actually wisdom or just preferences dressed up as ethics.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-snake",
              "name": "Fire Snake",
              "reason": "Wood feeds Fire—your principles fuel their strategic vision; both value refined execution with deeper purpose"
          },
          {
              "slug": "earth-ox",
              "name": "Earth Ox",
              "reason": "Wood controls Earth productively—you provide vision, they provide steadfast implementation without ego battles"
          },
          {
              "slug": "water-rat",
              "name": "Water Rat",
              "reason": "Water nourishes Wood—their adaptability softens your rigidity while respecting your ethical framework"
          }
      ],
      "worst": [
          {
              "slug": "metal-rabbit",
              "name": "Metal Rabbit",
              "reason": "Metal cuts Wood harshly—their refined avoidance clashes with your insistence on principled confrontation"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Double Rooster perfectionism with Metal cutting your Wood growth—competing visions of order without flexibility"
          },
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Wood feeds Fire excessively—they burn through your carefully constructed principles with reckless freedom"
          }
      ]
  },
}

export default content
