// ============================================
// WOOD DRAGON (甲辰) — The Creative Titan
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'wood-dragon',
  profile: getProfileBySlug('wood-dragon')!,
  archetype: {
    name: "The Creative Titan",
    tagline: "The Creative Titan — Wood Dragon",
  },
  atAGlance: {
      "element": "Wood (Growth, Vision, Expansion)",
      "energy": "Yang",
      "archetype": "The Creative Titan",
      "coreStrength": "Visionary momentum",
      "shadow": "Domineering idealism",
      "bestMatch": "fire-rat",
      "worstMatch": "metal-dog",
      "luckyColor": "Jade green"
  },
  personality: {
    body: "The Wood Dragon is ambition wrapped in vision, a force that doesn't just dream but builds empires from those dreams. Wood's growth drive amplifies the Dragon's natural authority into something more expansive and less tyrannical—you lead not through intimidation but through inspiring others with your relentless forward motion. Where Metal Dragons command and Water Dragons strategize, you cultivate. You see potential everywhere and possess the rare gift of making others believe in possibilities they'd never considered.\n\nYour creativity isn't delicate or precious—it's structural, architectural, world-building. You don't paint watercolors; you design cities. Wood gives the Dragon's fire a sustainable fuel source, so your enthusiasm doesn't burn out in spectacular crashes but maintains steady growth over years. You're the entrepreneur who scales thoughtfully, the artist who builds movements, the leader who creates institutions that outlive your direct involvement. You think in ecosystems, not transactions.\n\nYet this is no soft-hearted idealist. Yang Wood has spine—flexible but unbreaking. You bend around obstacles with strategic grace, rerouting your growth toward sunlight when something blocks your path. The Dragon's confidence means you rarely doubt your direction, and Wood's spring energy means you're perpetually in expansion mode. You don't wait for permission or perfect conditions. You start, adjust, and grow through doing.\n\nYour charm is understated compared to flashier Dragons. People follow you because you're going somewhere worth following, not because you demanded it. You generate Fire in others—your vision kindles their passion, your growth mindset gives them permission to evolve. But you control Earth too, which means you can be surprisingly pragmatic about resources, timelines, and what's actually buildable versus what's fantasy.",
  },
  shadow: {
    body: "Your growth impulse becomes tyranny when unchecked. You don't just want things to grow—you need them to grow according to your vision, at your pace, in your direction. This manifests as subtle control disguised as helpfulness: you're not micromanaging, you're just \"helping things develop properly.\" Wood's flexibility inverts into manipulation when you bend every situation toward your predetermined outcome while pretending it's organic.\n\nThe Dragon's ego plus Wood's expansionism creates someone who genuinely believes their way is objectively better, not just preferable. You steamroll over others' boundaries while calling it \"momentum\" or \"not getting stuck in small thinking.\" Your idealism becomes a weapon—anyone not sharing your vision is \"limiting\" or \"playing small.\" You control Earth, which means you can smother others' initiatives by overgrowing their space, casting shade while claiming you're just doing your natural thing.\n\nWhen stressed, you become rigid despite Wood's supposed flexibility—your vision calcifies into dogma, and your growth drive becomes frantic expansion for its own sake. You confuse motion with progress, adding more projects instead of deepening existing ones. The shadow Wood Dragon is exhausting to work with: inspiring but domineering, visionary but inflexible, generous but controlling.",
  },
  relationships: {
    body: "You need partners who can handle your momentum without either collapsing under it or competing with it. Fire types thrive with you—you generate their element, fueling their passion while they transform your growth into cultural impact. But you'll smother Earth partners if you're not careful, your constant expansion making them feel inadequate or controlled.\n\nIn intimacy, you're more generous than other Dragons, genuinely invested in your partner's development. But \"development\" often means \"becoming the version I envision,\" and that's where problems start. You don't mean to be controlling—you're just so certain about optimal growth paths that you forget others might have their own trajectory. You need someone with enough Metal in their nature to prune your excesses without killing your vision, or enough Water to nourish without drowning your fire.\n\nYou're loyal but not particularly attentive to emotional subtlety. You show love through opportunities, through opening doors and expanding possibilities. If your partner needs quiet presence over grand gestures, you'll miss the mark. Your best relationships involve shared missions where your growth drive serves collective goals rather than becoming a force others must manage.",
  },
  elementBalance: {
    body: "Your Wood excess needs Metal's pruning and Water's patience. Physically, you require actual rest, not just \"slower growth.\" Practice stopping completely—meditation that isn't goal-oriented, walks without podcasts, meals without networking. Your body needs downtime where nothing develops.\n\nSeek Metal's discernment: Not every opportunity deserves your energy. Get comfortable saying no to good ideas to protect great ones. Journal daily on what you'll deliberately not do. Water's wisdom: Let some things grow at their own pace. Plant actual seeds and notice you can't force germination. In relationships, practice receiving others' visions without immediately expanding or improving them. Ask questions instead of offering solutions. Your balance comes from learning that sometimes the most powerful growth move is strategic restraint.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-rat",
              "name": "Fire Rat",
              "reason": "You generate their Fire while they ground your vision with clever resourcefulness—mutual amplification without competition"
          },
          {
              "slug": "fire-monkey",
              "name": "Fire Monkey",
              "reason": "Your structural creativity meets their innovative chaos; you build the container for their genius"
          },
          {
              "slug": "water-tiger",
              "name": "Water Tiger",
              "reason": "Water nourishes your Wood while Tiger matches your courage—they flow where you grow, creating dynamic balance"
          }
      ],
      "worst": [
          {
              "slug": "metal-dog",
              "name": "Metal Dog",
              "reason": "Metal chops Wood while Dog's righteousness clashes with your expansive vision—constant pruning feels like betrayal"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Their Metal precision cuts your growth impulse; you feel criticized, they feel you're recklessly overextending"
          },
          {
              "slug": "earth-goat",
              "name": "Earth Goat",
              "reason": "You control and smother their Earth nature; your momentum overwhelms their need for gentle stability"
          }
      ]
  },
}

export default content
