// ============================================
// WOOD TIGER (甲寅) — The Compassionate Adventurer
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'wood-tiger',
  profile: getProfileBySlug('wood-tiger')!,
  archetype: {
    name: "The Compassionate Adventurer",
    tagline: "The Compassionate Adventurer — Wood Tiger",
  },
  atAGlance: {
      "element": "Wood (Growth, Vision)",
      "energy": "Yang",
      "archetype": "The Compassionate Adventurer",
      "coreStrength": "Courageous expansion",
      "shadow": "Impulsive overextension",
      "bestMatch": "fire-horse",
      "worstMatch": "metal-monkey",
      "luckyColor": "Forest green"
  },
  personality: {
    body: "You combine Tiger's explosive courage with Wood's expansive vision—a force that charges forward not for glory alone, but to break new ground where others can grow. Where Metal Tiger calculates dominance and Fire Tiger burns for attention, you're driven by an almost missionary zeal to pioneer territories of justice, possibility, and authentic experience. You don't just want to win; you want everyone to see what's possible beyond the current horizon.\n\nYour Wood nature tempers Tiger's aggression with genuine idealism. You fight for causes, not trophies. This makes you the revolutionary who actually cares what happens after the regime falls, the entrepreneur who measures success by the ecosystem you build rather than the empire you control. You're flexible enough to change tactics mid-charge, which sounds impossible for a Tiger but becomes your signature move—the ability to pivot without losing momentum.\n\nThe Yang energy doubles down in you, creating someone who doesn't wait for permission or consensus. You spot an injustice, a gap in the market, an unexplored trail, and you're already moving while others are still forming committees. This makes you magnetic to those exhausted by hesitation and paralysis. People follow you not because you promise safety, but because your confidence in growth itself is infectious.\n\nYour compassion isn't soft—it's strategic. You understand that helping others expand their potential creates allies rather than dependents. You mentor aggressively, delegate boldly, and genuinely celebrate when someone you've championed outgrows your shadow. This Wood-fueled generosity makes you a rarity among Tigers: one who builds movements, not cults of personality.",
  },
  shadow: {
    body: "Your shadow is the crusader who tramples the garden while claiming to plant it. You overextend so reflexively that you confuse motion with progress, starting initiatives you'll abandon once the novelty fades. This isn't laziness—it's Wood's growth drive without Metal's pruning discipline. You launch the nonprofit, the startup, the movement, then resent the maintenance phase when pioneering turns to plumbing.\n\nYour compassion becomes coercion when you decide you know what growth looks like for everyone. You push people toward opportunities they didn't ask for, label their hesitation as fear rather than wisdom, and secretly view stability-seekers as obstacles to evolution. This missionary zeal blinds you to the violence of imposed expansion—Wood's darker truth that not every vine that grows serves the forest.\n\nWorst, you avoid confronting your own limits by constantly expanding into new territory. Can't fix your relationship? Start a new project. Can't master the fundamentals? Pivot to the next big idea. Your flexibility becomes escapism, and your vision becomes a distraction from the unglamorous work of deepening rather than widening.",
  },
  relationships: {
    body: "You need partners who can match your momentum without requiring constant heroic gestures to prove your commitment. You're loyal through adventure, not through sitting still, which confuses partners who equate presence with proximity. You show love by inviting people into your expanding world, by fighting their battles alongside your own, by assuming they want to grow as relentlessly as you do.\n\nThe danger: you attract people who want a leader, then resent them for not being peers. Or you choose independent spirits, then feel abandoned when they don't join every crusade. You need someone who has their own mission but sees yours as complementary rather than competitive—Fire types who can transform your vision into sustainable heat, or Earth partners grounded enough to say \"not every hill requires charging.\"\n\nYou struggle with emotional maintenance—the daily tending that relationships require when nothing's actively broken or exciting. Learn that depth isn't stagnation. Your partner staying home to read isn't betraying growth; your relationship reaching a stable rhythm isn't death, it's the maturation that precedes the next genuine expansion rather than the next distraction.",
  },
  elementBalance: {
    body: "Feed your Wood by engaging with actual growth cycles, not just expansion theater. Garden something—literally. Watch plants teach you that growth includes dormancy, that roots matter as much as shoots, that pruning enables flourishing. This grounds your vision in biological reality rather than abstract ambition.\n\nBalance with Metal: set completion criteria before starting projects. Define what \"done\" looks like. Let Metal cut away the 60% of initiatives that dilute your impact. One pioneering project finished transforms more than ten abandoned at 40%.\n\nCultivate Earth: commit to one community, relationship, or practice for longer than feels exciting. Let yourself be stabilized by repetition. Your Wood will resist this as limitation; that resistance is exactly why you need it.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Wood feeds Fire—your vision fuels their passionate execution while they transform your ideas into contagious energy."
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Earth receives Wood's growth—their loyalty grounds your expansion, giving your crusades a stable base without clipping your wings."
          },
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Water nourishes Wood—their diplomatic abundance supports your pioneering without demanding you slow down to their pace."
          }
      ],
      "worst": [
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "Metal cuts Wood—their sharp critique dismantles your vision before it can root, while your expansion threatens their need for clever control."
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal chops Wood—their perfectionism prunes your momentum into paralysis, judging your pivots as lack of discipline rather than flexibility."
          },
          {
              "slug": "earth-ox",
              "name": "Earth Ox",
              "reason": "Wood depletes Earth—your constant expansion exhausts their stability, while their immovable patience feels like obstruction to your growth imperative."
          }
      ]
  },
}

export default content
