// ============================================
// WOOD MONKEY (甲申) — The Inventive Trickster
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'wood-monkey',
  profile: getProfileBySlug('wood-monkey')!,
  archetype: {
    name: "The Inventive Trickster",
    tagline: "The Inventive Trickster — Wood Monkey",
  },
  atAGlance: {
      "element": "Wood (Growth, Innovation)",
      "energy": "Yang",
      "archetype": "The Inventive Trickster",
      "coreStrength": "Creative Problem-Solving",
      "shadow": "Manipulative Schemes",
      "bestMatch": "fire-rat",
      "worstMatch": "metal-tiger",
      "luckyColor": "Emerald Green"
  },
  personality: {
    body: "The Wood Monkey is a strategic innovator who sees possibilities where others see obstacles. Wood's growth orientation combines with the Monkey's clever adaptability to create someone who doesn't just solve problems—they redesign the entire game. You're the person who hacks systems, invents workarounds, and finds the hidden door everyone else missed. Your mind moves like spring vines—constantly exploring new directions, testing boundaries, wrapping around obstacles rather than confronting them head-on.\n\nWhere Metal Monkey calculates and Earth Monkey stabilizes, you improvise with infectious enthusiasm. Wood's expansive nature softens the Monkey's typical self-interest into something more collaborative. You genuinely enjoy bringing others along on your adventures, sharing discoveries, teaching tricks. Your ideas grow organically, branching in unexpected directions. You'll start a conversation about gardening and end up launching a community composting network with an app component and a barter system.\n\nYour humor is sharp but rarely cruel—Wood's compassionate growth energy tempers the Monkey's tendency toward mockery. You use wit to open doors, not slam them. People trust you because you make risk feel like play, complexity feel simple. You're excellent at reading social dynamics, knowing exactly when to push an idea and when to let it germinate. Your flexibility means you rarely get attached to one approach; if plan A fails, you're already three moves into plan C.\n\nThe Yang energy keeps you visible and active. You're not the behind-the-scenes strategist—you're demonstrating, persuading, recruiting. Wood generates Fire in the elemental cycle, and you naturally spark enthusiasm in others. Your projects grow because you're skilled at finding the leverage points where small efforts create cascading results.",
  },
  shadow: {
    body: "Your flexibility can become slipperiness. When Wood's growth drive combines with Monkey cunning, you can rationalize anything—rules don't apply because you've found a loophole, promises are flexible because circumstances changed, manipulation is justified because your intentions are good. You convince yourself that the ends justify remarkably dubious means. Your ability to see multiple angles becomes an excuse for avoiding commitment.\n\nWood controls Earth in the destructive cycle, and you can destabilize foundations others depend on. Your constant innovation disrupts without consideration for those who need stability. You get bored and tear down systems that are working fine, just not exciting. People feel used when they realize your charm was strategic, that you were networking rather than connecting. Your schemes can grow wild, becoming more complex than necessary, solving problems that don't exist while ignoring real consequences. When challenged, you deflect with humor or pivot to a new topic, never quite accountable.",
  },
  relationships: {
    body: "You need partners who can keep pace with your branching ideas without losing themselves in your schemes. You're attracted to people who challenge your assumptions and call out your manipulations—not with rigidity, but with grounded clarity. In love, you're playful and attentive, but you can treat relationships like projects, always optimizing rather than simply being present.\n\nYou thrive with Fire signs who amplify your enthusiasm into real manifestation—they take your ideas and run with them, providing the decisive action you sometimes avoid. Water signs offer depth but can feel too slow or emotionally demanding. You appreciate Metal's structure when it provides frameworks for your creativity, but clash when it becomes criticism of your methods.\n\nYour intimacy style involves shared adventures and intellectual connection. You show love through problem-solving and creating opportunities. But you must learn that sometimes people need consistency more than cleverness, presence more than possibilities. Your partners need to trust that you won't scheme your way out when things get difficult, that your flexibility doesn't mean you'll simply adapt yourself into a different relationship.",
  },
  elementBalance: {
    body: "To balance Wood's growth with Monkey's restlessness, commit to finishing what you start before branching to new projects. Set a quarterly review where you evaluate whether your innovations actually improved anything or just created complexity. Practice transparency—explain your reasoning instead of presenting conclusions as if they're obvious. Spend time with Earth signs who model follow-through without judgment.\n\nPhysically, engage in activities that require sustained growth toward mastery: martial arts, musical instruments, languages. Wood needs direction for its expansion. When you feel yourself scheming, pause and ask whether you're solving a real problem or avoiding something uncomfortable. Your genius lies in creative problem-solving, not in outwitting consequences.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-rat",
              "name": "Fire Rat",
              "reason": "Wood feeds Fire—your innovation fuels their ambitious action, creating unstoppable collaborative momentum"
          },
          {
              "slug": "water-dragon",
              "name": "Water Dragon",
              "reason": "Water nourishes Wood—their visionary depth provides substance for your creative schemes without dampening flexibility"
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Wood controls Earth productively—your growth challenges their rigidity while their loyalty grounds your scattered energy"
          }
      ],
      "worst": [
          {
              "slug": "metal-tiger",
              "name": "Metal Tiger",
              "reason": "Metal cuts Wood—their forceful directness clashes with your indirect approach, creating mistrust and power struggles"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal chops Wood—their exacting standards and blunt criticism stifle your experimental, boundary-pushing creativity"
          },
          {
              "slug": "earth-ox",
              "name": "Earth Ox",
              "reason": "Wood depletes Earth—your constant innovation exhausts their need for stability, while their stubbornness frustrates your flexibility"
          }
      ]
  },
}

export default content
