// ============================================
// WOOD SNAKE (甲巳) — The Thoughtful Philosopher
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'wood-snake',
  profile: getProfileBySlug('wood-snake')!,
  archetype: {
    name: "The Thoughtful Philosopher",
    tagline: "The Thoughtful Philosopher — Wood Snake",
  },
  atAGlance: {
      "element": "Wood (Growth, Expansion, Vision)",
      "energy": "Yin",
      "archetype": "The Thoughtful Philosopher",
      "coreStrength": "Strategic wisdom",
      "shadow": "Paralysis by analysis",
      "bestMatch": "fire-horse",
      "worstMatch": "metal-rooster",
      "luckyColor": "Emerald green"
  },
  personality: {
    body: "You're the Snake who thinks before striking — and thinks some more after that. Wood softens the Snake's typical intensity into something more reflective, turning raw cunning into genuine wisdom. Where Metal Snakes calculate and Water Snakes seduce, you contemplate. You see patterns others miss because you're willing to sit with complexity rather than forcing quick answers. Your mind works like roots spreading through soil — slowly, persistently, finding connections in unexpected places.\n\nThis contemplative nature makes you an exceptional strategist, but not the boardroom variety. You strategize about ideas, ethics, systems. You want to understand why people do what they do, why societies function as they function. The Snake gives you penetrating insight; Wood gives you the patience to use it constructively rather than destructively. You don't just want to win — you want everyone to grow from the experience. That's rare for a Snake.\n\nYour communication style reflects this. You don't hiss warnings or strike with verbal venom. Instead, you ask questions that make people reconsider their entire framework. You plant seeds of doubt or inspiration and let them grow naturally. This makes you influential in subtle ways — people often adopt your ideas without realizing they came from you. You're fine with that. Recognition matters less than seeing your vision take root.\n\nThe philosophical bent is real, not affectation. You genuinely enjoy abstract thought, ethical puzzles, long conversations that spiral into unexpected territory. But Wood keeps you from disappearing entirely into your head. You want your insights to have practical application, to help things grow. You're building frameworks for understanding, gardens of thought where others can cultivate their own wisdom.",
  },
  shadow: {
    body: "Your greatest weakness is overthinking yourself into inaction. Wood's expansive nature combined with Snake's analytical depth creates endless layers of consideration. You see so many angles, so many potential consequences, that decision-making becomes torture. Meanwhile, opportunities pass. Relationships stagnate. You're still mapping the terrain while others have already crossed it.\n\nThis manifests as passive manipulation through withdrawal. When stressed, you don't attack — you disappear into contemplation, leaving others unsure where they stand. You call it 'taking time to process,' but it's often avoidance dressed up as wisdom. You use philosophical detachment as armor against vulnerability. 'I'm just observing' becomes an excuse for not committing.\n\nYou can also be insufferably superior about your insight. The combination of Snake's natural sense of being special and Wood's intellectual growth creates a person who thinks they've evolved beyond others' petty concerns. You don't say it directly — that would be crude — but it oozes from your 'curious' questions and 'just wondering' observations. People feel condescended to without being able to pinpoint why.",
  },
  relationships: {
    body: "You need partners who can draw you out of your head and into embodied experience. Your ideal match doesn't just tolerate your contemplative nature — they interrupt it with action, warmth, and life happening right now. You're attracted to people with strong Fire energy because they convert your endless deliberation into actual movement. They don't let you philosophize about the relationship instead of having one.\n\nIn conflict, you retreat into analytical mode, dissecting what went wrong instead of feeling it. This frustrates more direct partners who want emotional presence, not a thesis on relationship dynamics. You need someone who can say 'I don't want your analysis, I want your heart' and mean it.\n\nYour gift in relationships is creating space for deep growth. You see your partner's potential and nurture it patiently. You ask questions that help them understand themselves better. You don't rush their process. When you're not hiding behind philosophy, you're genuinely supportive of others' evolution. You just need to remember that sometimes growth requires messy action, not just elegant thought.",
  },
  elementBalance: {
    body: "Stop researching and start doing. Seriously. Pick one project, one decision, one conversation you've been 'considering' and execute it this week. Wood element balances through action that generates Fire — literally creating heat through movement. Exercise that makes you sweat, not yoga you can think through. Dance, run, fight, build something with your hands.\n\nLimit your input. You consume too much information, which feeds the analysis paralysis. One book at a time. One podcast episode, not the entire archive. Your Wood needs focus to generate upward growth, not endless lateral expansion.\n\nSpend time with people who embody what you overthink. Want to understand courage? Befriend someone brave and watch them act. Your insight deepens through observation of living examples, not more theory.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Wood feeds Fire — your vision fuels their action, their momentum prevents your stagnation"
          },
          {
              "slug": "earth-ox",
              "name": "Earth Ox",
              "reason": "Wood controls Earth productively — you provide vision, they provide the structure to manifest it"
          },
          {
              "slug": "water-rat",
              "name": "Water Rat",
              "reason": "Water nourishes Wood — their adaptability and social intelligence support your growth without overwhelming you"
          }
      ],
      "worst": [
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal cuts Wood — their precision and criticism chop down your expansive thinking before it can develop"
          },
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "Metal restricts Wood — their sharp cleverness turns your contemplation into competitive analysis"
          },
          {
              "slug": "wood-tiger",
              "name": "Wood Tiger",
              "reason": "Double Wood with conflicting expression — you philosophize about action while they demand immediate movement"
          }
      ]
  },
}

export default content
