// ============================================
// WOOD HORSE (甲午) — The Free-Spirited Wanderer
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'wood-horse',
  profile: getProfileBySlug('wood-horse')!,
  archetype: {
    name: "The Free-Spirited Wanderer",
    tagline: "The Free-Spirited Wanderer — Wood Horse",
  },
  atAGlance: {
      "element": "Wood (Growth, Expansion)",
      "energy": "Yang",
      "archetype": "The Free-Spirited Wanderer",
      "coreStrength": "Adventurous vision",
      "shadow": "Restless escapism",
      "bestMatch": "fire-goat",
      "worstMatch": "metal-rat",
      "luckyColor": "Forest green"
  },
  personality: {
    body: "You're the zodiac's perpetual motion machine with a compass pointed toward possibility. Wood feeds the Horse's already blazing yang energy with expansive growth impulses, creating someone who doesn't just want freedom—you need horizons that keep receding. Where typical Horses gallop toward immediate thrills, Wood gives you visionary scope. You're chasing ideas, movements, causes that feel bigger than yourself. This isn't wanderlust for its own sake; it's growth-seeking behavior hardwired into your elemental DNA.\n\nYour Wood element manifests as ethical wandering. You don't just travel—you evangelize about what you've discovered. You return from experiences wanting to plant seeds, share perspectives, expand everyone's worldview. There's missionary zeal here, but the flexible kind. Unlike rigid Metal types, you adapt your message to the terrain. You're the entrepreneur who pivots three times before finding product-market fit, the teacher who redesigns curriculum mid-semester because students need something different, the activist switching tactics when one approach stalls.\n\nThis combination creates infectious optimism that borders on prophetic. You see potential where others see obstacles because Wood energy literally grows toward light, and Horse energy refuses to acknowledge barriers. People either find this inspiring or exhausting—sometimes both. You initiate projects with breathtaking enthusiasm, rally others to your vision, then occasionally gallop toward the next thing before the first takes root. Your strength isn't patient cultivation; it's the explosive germination phase. You're spring incarnate—all budding possibility, rapid expansion, green shoots breaking through concrete.",
  },
  shadow: {
    body: "Your growth impulse becomes invasive species behavior when unchecked. You overcommit, overextend, overpromise—not from malice but from genuine belief that you can grow fast enough to meet every opportunity. This creates a trail of half-finished projects and people who felt abandoned mid-journey. Wood generates Fire in the elemental cycle, and you can burn through relationships by constantly feeding your need for new terrain. You mistake movement for progress, confusing the dopamine hit of novelty with actual development.\n\nThe darker manifestation: you use idealism as escapism. When reality gets complex or boring, you reframe leaving as \"following your truth\" or \"honoring your growth.\" You're capable of spectacular rationalization, dressing up restlessness as spiritual evolution. Commitments feel like cages not because they actually limit you, but because Wood Horse energy pathologically resists containment. You can become the person who's always about to start their real life—after this trip, this certification, this revelation—never recognizing that constant preparation is just fear of arrival dressed in inspirational language.",
  },
  relationships: {
    body: "You need partners who can either match your pace or anchor without clinging. The fundamental tension: you're genuinely warm and generous (Wood's compassionate nature) but allergic to emotional heaviness. You show love through expansion—introducing partners to new experiences, broadening their perspectives, championing their growth. But you struggle when people need you to simply stay still and be present.\n\nYou're most dangerous to Earth types who mistake your enthusiasm for stability, then feel destabilized when you need to roam. Wood controls Earth in the destructive cycle, and you unconsciously undermine people who try to contain your growth through guilt or obligation. You need relationships structured around shared direction rather than shared space—partners who have their own horizons to chase. When you find someone whose growth trajectory runs parallel to yours, you're remarkably loyal. But loyalty for you means mutual expansion, not mutual enclosure. You'll commit to a journey but rebel against a cage, even a comfortable one.",
  },
  elementBalance: {
    body: "Balance your Wood by deliberately completing growth cycles instead of just starting them. Pick three projects maximum and stay with each until it fruits—Wood energy needs to see seeds become harvest sometimes. Add Metal practices: structured routines, finished drafts, maintained commitments. This isn't about killing your spontaneity; it's about direction-channeling rather than direction-scattering.\n\nPhysically, you need movement that goes somewhere—long-distance running, cycling routes with destinations, hiking trails with summits. Aimless gym routines will bore you into quitting. Feed Fire productively by mentoring others; your growth impulse becomes generative when you help others expand rather than just chasing your own horizons. Recognize that depth is another form of growth. Sometimes the most radical expansion is downward, into roots, not outward into branches.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-goat",
              "name": "Fire Goat",
              "reason": "Wood feeds Fire; your vision fuels their creative warmth without demanding they keep pace with your galloping."
          },
          {
              "slug": "fire-tiger",
              "name": "Fire Tiger",
              "reason": "Double yang adventurers who generate heat through shared momentum; Wood feeds their passionate initiatives."
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Your Wood controls their Earth gently; you expand their worldview while they provide loyal groundedness without caging."
          }
      ],
      "worst": [
          {
              "slug": "metal-rat",
              "name": "Metal Rat",
              "reason": "Metal chops Wood; their calculating control kills your spontaneous growth, creating mutual resentment."
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal cuts Wood brutally; their precision and criticism prune your expansive optimism into defensive withdrawal."
          },
          {
              "slug": "water-ox",
              "name": "Water Ox",
              "reason": "Their plodding endurance frustrates your need for speed; Water weakens Wood when stagnant rather than flowing."
          }
      ]
  },
}

export default content
