// ============================================
// WOOD OX (甲丑) — The Steadfast Cultivator
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'wood-ox',
  profile: getProfileBySlug('wood-ox')!,
  archetype: {
    name: "The Steadfast Cultivator",
    tagline: "The Steadfast Cultivator — Wood Ox",
  },
  atAGlance: {
      "element": "Wood (Growth, Flexibility, Vision)",
      "energy": "Yin",
      "archetype": "The Steadfast Cultivator",
      "coreStrength": "Patient Innovation",
      "shadow": "Stubborn Righteousness",
      "bestMatch": "fire-snake",
      "worstMatch": "metal-rooster",
      "luckyColor": "Jade Green"
  },
  personality: {
    body: "You combine the Ox's legendary persistence with Wood's expansive vision—a rare individual who builds gardens, not just structures. Where typical Oxen dig trenches and hold positions, you plant seeds and watch them become forests. Your strength isn't mere endurance; it's directed growth with purpose. You work toward long-term transformations others can't even conceptualize yet, plowing fields that won't yield harvests for years.\n\nWood softens the Ox's notorious rigidity into something more adaptive. You still move slowly, methodically, but you bend around obstacles rather than smashing through them. When a tree root encounters rock, it finds another path—that's your problem-solving style. You're the person who spends three years developing a better system while everyone else complains about the old one. Your patience isn't passive; it's strategic waiting for the right conditions.\n\nYour compassion runs deeper than sentiment. You genuinely want to cultivate potential in others, often mentoring younger colleagues or nurturing projects everyone else abandoned. But this isn't soft—you expect growth, demand it even. You'll give someone twelve chances if you see genuine effort, zero chances if you detect laziness. Your standards are high because Wood understands: anything worth growing requires consistent care.\n\nThe shadow? You can be insufferably certain about your ethical frameworks. Wood brings idealism, Ox brings conviction, and together they create someone who believes their slow-grown principles are universal truths. You'll sacrifice efficiency for integrity, which is admirable until you're lecturing coworkers about compostable coffee cups while the company burns. Your flexibility has limits—you bend, but only in directions you've pre-approved.",
  },
  shadow: {
    body: "Your worst tendency is disguising stubbornness as principle. You tell yourself you're being consistent when you're actually being inflexible, that you're maintaining standards when you're just refusing to adapt. Wood gives you vision for how things should grow, Ox makes you dig in when reality disagrees, and the combination produces someone who can waste years trying to cultivate a garden in concrete.\n\nYou become preachy when stressed. That compassionate mentor energy curdles into judgmental superiority—suddenly you're the arbiter of what constitutes authentic growth, real effort, proper values. You stop listening because you've already diagnosed the problem: people aren't following the natural order you've identified. The irony? Your rigidity about growth principles prevents your own evolution. You'll ignore feedback for months, then act wounded when people stop offering it.",
  },
  relationships: {
    body: "You need partners who appreciate slow cultivation but won't tolerate stagnation disguised as patience. You're deeply loyal once committed—Wood's growth orientation makes you invested in the relationship's long-term development. You remember anniversaries, tend to shared routines, build traditions deliberately. But you also expect your partner to grow in specific directions, and you can be controlling about the process.\n\nYour intimacy style is consistent rather than passionate. You show love through sustained attention—making coffee the same way for twenty years, remembering how someone takes their tea. Romance to you is reliability compounded over time. Fire signs often misread this as lack of excitement; they're wrong. Your devotion deepens like tree rings, year after year.\n\nThe relationship killer: you withdraw when feeling unappreciated, then resent others for not noticing your withdrawal. Wood Oxen will silently tend a dying relationship for years rather than have a direct confrontation about needs. You need partners who explicitly acknowledge your contributions and who challenge your certainty with enough force to actually register.",
  },
  elementBalance: {
    body: "Your Wood needs pruning, not just watering. Engage in activities that force spontaneity—improvisational classes, travel without itineraries, projects with hard deadlines that prevent your endless refinement cycles. You balance by occasionally choosing speed over perfection.\n\nPractical grounding: work with actual plants. Gardening gives you immediate feedback on your tendencies—you can't lecture a tomato plant into growing faster, can't stubbornly insist a shade plant thrives in full sun. Fire activities—competitive sports, public speaking, anything requiring quick decisions—prevent Wood from becoming overgrown with possibilities and Ox from becoming entrenched in routine. Your flexibility improves when you practice it under pressure, not just in your head.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-snake",
              "name": "Fire Snake",
              "reason": "Wood feeds Fire—your steady cultivation fuels their brilliant transformations without being consumed by their intensity."
          },
          {
              "slug": "water-rat",
              "name": "Water Rat",
              "reason": "Water nourishes Wood—their adaptability irrigates your growth while your direction channels their scattered energy productively."
          },
          {
              "slug": "earth-dog",
              "name": "Earth Dog",
              "reason": "Wood controls Earth generatively—you provide vision for their loyal protection, they provide stable ground for your long-term cultivation."
          }
      ],
      "worst": [
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal chops Wood—their cutting precision and rigid schedules clash with your patient, organic growth approach, creating constant friction."
          },
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "Metal axes Wood while Monkey chaos opposes Ox stability—they'll dismantle your carefully built systems for fun, triggering your worst rigidity."
          },
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Your Wood feeds their Fire but they burn too hot and fast—they'll consume your patient cultivation energy with unsustainable demands."
          }
      ]
  },
}

export default content
