// ============================================
// WOOD PIG (甲亥) — The Generous Soul
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'wood-pig',
  profile: getProfileBySlug('wood-pig')!,
  archetype: {
    name: "The Generous Soul",
    tagline: "The Generous Soul — Wood Pig",
  },
  atAGlance: {
      "element": "Wood (Growth, Generosity)",
      "energy": "Yin",
      "archetype": "The Generous Soul",
      "coreStrength": "Compassionate abundance",
      "shadow": "Self-sacrificing overextension",
      "bestMatch": "fire-goat",
      "worstMatch": "metal-monkey",
      "luckyColor": "Jade green"
  },
  personality: {
    body: "The Wood Pig combines the Pig's inherent warmth with Wood's expansive growth energy, creating someone who genuinely believes there's enough for everyone. You don't just share what you have—you actively grow resources to give away. Where other signs accumulate, you cultivate. Your generosity isn't performative charity; it's the natural overflow of someone who sees abundance as a renewable cycle rather than a finite pie.\n\nYour flexibility makes you remarkably adaptable in social situations. Like bamboo bending in wind, you adjust to others' needs without losing your core integrity. This isn't weakness—it's Wood's intelligent responsiveness. You read rooms intuitively, knowing when to offer support and when to step back. People feel safe around you because you're not rigid about outcomes. You're invested in their growth, not in controlling their path.\n\nThe Wood element amplifies the Pig's already considerable emotional intelligence with strategic vision. You don't just feel deeply; you understand how emotions fuel action. This makes you exceptional at motivating teams, building communities, and creating environments where people thrive. You see potential in others before they see it themselves, and you're willing to invest time nurturing that potential without demanding immediate returns.\n\nYour weakness? You confuse enabling with empowering. Wood grows outward indiscriminately—nourishing weeds as readily as flowers. You'll pour energy into people who take without reciprocating, mistaking their consumption for connection. Your horror of being perceived as selfish makes you ignore your own depletion until you're running on fumes, snapping at the people you genuinely love while still smiling at the users who drain you.",
  },
  shadow: {
    body: "Your generosity becomes self-destruction when you can't distinguish between support and sacrifice. You'll cancel your own needs to accommodate others, then resent them for accepting what you freely offered. This passive-aggressive martyrdom poisons relationships because people never know they've crossed a line—you don't set boundaries until you explode.\n\nWood out of balance grows invasively. You involvement in others' lives crosses into intrusion. You're \"helping\" when no one asked, fixing problems that aren't yours, then feeling hurt when people don't appreciate your unsolicited intervention. Your flexibility becomes spinelessness—agreeing to things you'll later sabotage through \"forgetfulness\" or half-effort because you couldn't say no directly.\n\nYou enable destructive behavior by cushioning natural consequences. Your friend misses deadlines? You cover. Your partner won't handle their issues? You compensate. This prevents growth—the very thing Wood should facilitate. You're so focused on preventing discomfort that you block the productive struggle necessary for real development.",
  },
  relationships: {
    body: "You need partners who reciprocate your generosity without exploiting it. The difference is crucial—reciprocity isn't transactional scorekeeping but mutual investment. You thrive with people who give without being asked, who notice when you're depleted and actively refill your reserves. Fire signs often work well because they naturally generate warmth that feeds your growth without requiring you to manufacture it yourself.\n\nYou're attracted to people with clear needs because it gives you purpose, but sustainable relationships require you to be needed AND wanted. Someone who appreciates your overflow without depending on it. You need explicit permission to rest, or you'll keep performing generosity out of habit.\n\nSexually and emotionally, you're attentive to the point of self-erasure. You need partners who actively draw out your desires, who refuse to let you disappear into service. The best relationships force you to receive—not as obligation but as genuine gift. You need to experience wanting without guilt, taking without owing.",
  },
  elementBalance: {
    body: "Practice strategic withholding. Not every request deserves your immediate yes. Let people sit in their discomfort long enough to develop their own solutions. This isn't cruelty—it's allowing Wood's growth principle to work properly.\n\nPhysically contain your expansion. Set specific hours for availability. Define clear limits on resources you'll share. Wood needs boundaries or it becomes invasive groundcover instead of purposeful forest.\n\nNurture something that can't reciprocate—a garden, a craft, a skill. Pour your generous energy into growth that doesn't require you to manage others' emotions or fix their problems. This satisfies Wood's need to cultivate without the complex entanglement of human neediness.\n\nRegularly audit your relationships. Who actually feeds your growth versus who only consumes? Prune ruthlessly. Wood's health depends on directing resources toward thriving growth, not sustaining dead weight.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-goat",
              "name": "Fire Goat",
              "reason": "Wood feeds Fire naturally; your nurturing meets their creative warmth in sustainable mutual growth"
          },
          {
              "slug": "water-rabbit",
              "name": "Water Rabbit",
              "reason": "Water nourishes Wood; their gentle emotional depth replenishes your giving without demanding it"
          },
          {
              "slug": "fire-dog",
              "name": "Fire Dog",
              "reason": "Your generosity meets their loyalty; Fire transforms your growth into shared purpose and protection"
          }
      ],
      "worst": [
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "Metal cuts Wood; their sharp opportunism exploits your generosity while mocking your sincerity"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal chops Wood relentlessly; their criticism prunes your flexibility into anxious people-pleasing"
          },
          {
              "slug": "earth-snake",
              "name": "Earth Snake",
              "reason": "Wood controls Earth but depletes itself; their calculated withholding triggers your compulsive giving"
          }
      ]
  },
}

export default content
