// ============================================
// WOOD GOAT (甲未) — The Artistic Dreamer
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'wood-goat',
  profile: getProfileBySlug('wood-goat')!,
  archetype: {
    name: "The Artistic Dreamer",
    tagline: "The Artistic Dreamer — Wood Goat",
  },
  atAGlance: {
      "element": "Wood (Growth, Compassion)",
      "energy": "Yin",
      "archetype": "The Artistic Dreamer",
      "coreStrength": "Creative empathy",
      "shadow": "Escapist procrastination",
      "bestMatch": "fire-rabbit",
      "worstMatch": "metal-ox",
      "luckyColor": "Sage green"
  },
  personality: {
    body: "You're the zodiac's sensitive artist—someone who feels the world in textures, colors, and unspoken emotional currents. Wood gives the Goat's natural creativity a directional force, channeling whimsy into actual projects rather than just daydreams. You don't just imagine beautiful things; you want to grow them, nurture them, see them take root in the world. Your compassion isn't performative—it's cellular. You genuinely ache when others hurt, and you'll rearrange your entire life to help someone heal.\n\nThis Wood-Goat combination makes you flexible in ways that confuse more rigid signs. You adapt, bend, find the path of least resistance—not out of weakness, but because you intuitively understand that forcing things breaks them. You're drawn to environments where aesthetic matters, where people value emotional intelligence over brute efficiency. Traditional corporate structures feel suffocating because they demand you prune your natural growth pattern into unnatural shapes.\n\nYour creativity flows in organic bursts, not scheduled blocks. You might spend three days obsessively working on a project, then need a week to wander and replenish. This isn't laziness—Wood element grows through cycles of expansion and rest. The problem is modern life doesn't respect this rhythm, so you're constantly fighting systems designed for Metal's precision or Fire's sustained intensity. You need space to meander, to follow tangents, because that's where your best insights hide.\n\nPeople underestimate you because you seem soft, accommodating, maybe even fragile. They don't realize your flexibility is strategic. You survive situations that would shatter more brittle personalities because you know how to yield without breaking. Your empathy reads the room before conflict escalates, and you defuse tension through creative compromise rather than confrontation.",
  },
  shadow: {
    body: "Your adaptability curdles into avoidance when stressed. Instead of confronting problems, you drift into fantasy worlds—scrolling endlessly, binging shows, disappearing into daydreams where everything's already resolved. This escapism isn't harmless procrastination; it's Wood element stagnating, refusing to push through resistance. You convince yourself you're 'processing' when you're actually hiding.\n\nYour compassion becomes a trap when you absorb everyone's emotions without boundaries. You'll sacrifice your own needs to keep peace, then resent people for taking what you freely gave. This passive-aggressive martyrdom poisons relationships slowly. You don't explode—you withdraw, grow distant, let connections wither through neglect while claiming you're just 'overwhelmed.'\n\nDecision paralysis haunts you. Every choice feels like it might hurt someone or close off possibilities, so you freeze, letting opportunities decay while you deliberate. Your need for consensus becomes an excuse to avoid leadership. You'll sabotage your own projects right before completion because finishing means facing judgment, and staying in the 'almost there' phase feels safer than risking failure.",
  },
  relationships: {
    body: "You need partners who appreciate your emotional depth without exploiting it. Someone who gives you space to retreat and recharge, but also gently pulls you back when you drift too far into isolation. You're attracted to people with Fire energy—they warm your sometimes-melancholic Wood nature, inspire you to manifest dreams into reality—but too much Fire exhausts you. You need them to respect that your slower pace isn't resistance; it's how you grow.\n\nIn love, you're devoted but need constant reassurance that it's safe to be vulnerable. You test partners unconsciously, creating small conflicts to see if they'll stay when things get messy. Stop doing this. Your withdrawal when hurt feels like punishment to others, even though you're just protecting yourself. Learn to articulate needs before resentment builds.\n\nYou thrive with Earth signs who ground your flights of fancy into practical form, helping you complete what you start. Water signs understand your emotional complexity but can create codependent pools of mutual stagnation. Metal signs often frustrate you with their rigidity, mistaking your flexibility for lack of conviction.",
  },
  elementBalance: {
    body: "To balance excess Wood: engage with Earth element through hands-on creation—pottery, gardening, cooking. Physical making grounds airy dreams into tangible form. Set artificial deadlines with real consequences; your flexibility needs boundaries or it becomes drift.\n\nTo strengthen weak Wood: spend time in actual nature, not conceptual nature. Walk barefoot, tend living plants, notice seasonal changes. Your element renews through direct contact with growth cycles. Practice assertive communication daily—small boundary-setting builds your Wood's upward-pushing force. Create one non-negotiable morning routine that roots your day before emotional demands scatter you. Finish small projects completely before starting new ones; completion strengthens Wood's capacity to push through resistance rather than route around it.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-rabbit",
              "name": "Fire Rabbit",
              "reason": "Fire warms your Wood into confident growth while Rabbit's sensitivity matches your emotional depth without overwhelming it"
          },
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Water nourishes your Wood creativity; Pig's genuine kindness and sensuality create safe space for your vulnerability"
          },
          {
              "slug": "earth-rabbit",
              "name": "Earth Rabbit",
              "reason": "Earth provides the grounding container your Wood dreams need to manifest; shared Rabbit gentleness creates mutual understanding"
          }
      ],
      "worst": [
          {
              "slug": "metal-ox",
              "name": "Metal Ox",
              "reason": "Metal chops Wood; Ox's rigid structure and blunt criticism crush your sensitive creative process into anxious paralysis"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal restrains Wood harshly; Rooster's perfectionist criticism and scheduled demands violate your organic growth rhythm"
          },
          {
              "slug": "fire-dragon",
              "name": "Fire Dragon",
              "reason": "Excessive Fire scorches Wood; Dragon's dominating energy and need for control leave no space for your quiet, meandering creativity"
          }
      ]
  },
}

export default content
