// ============================================
// WOOD DOG (甲戌) — The Loyal Guardian
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'wood-dog',
  profile: getProfileBySlug('wood-dog')!,
  archetype: {
    name: "The Loyal Guardian",
    tagline: "The Loyal Guardian — Wood Dog",
  },
  atAGlance: {
      "element": "Wood (Growth, Flexibility)",
      "energy": "Yang",
      "archetype": "The Loyal Guardian",
      "coreStrength": "Principled devotion",
      "shadow": "Rigid righteousness",
      "bestMatch": "fire-horse",
      "worstMatch": "metal-dragon",
      "luckyColor": "Forest green"
  },
  personality: {
    body: "The Wood Dog stands guard at the intersection of conviction and compassion. Where other Dogs bark from fixed positions, Wood brings flexibility to their sense of justice—they can bend their approach without breaking their principles. They're the friend who remembers your birthday five years running, the colleague who notices when you're struggling before you say a word, the neighbor who checks in after hearing your door slam. Their loyalty isn't performative; it's woven into how they move through the world.\n\nWood's growth energy transforms the Dog's natural protectiveness into active advocacy. They don't just defend—they cultivate. They build community gardens, organize neighborhood watches that actually know their neighbors, create systems that support rather than surveil. Their yang energy pushes outward, seeking to expand circles of care and fairness. They're physically restless when injustice festers nearby, unable to sit still while wrong goes unaddressed.\n\nTheir flexibility manifests in problem-solving, not principles. They'll find seventeen different ways to help someone in need, adjust their schedule endlessly for those they love, shift tactics when one approach fails. But the core mission never wavers. This makes them exceptional crisis responders—calm enough to adapt, steady enough to anchor. They're the people others call at 3 AM because they know the Wood Dog will answer and actually show up.\n\nThe Wood element softens the Dog's tendency toward suspicion, replacing paranoia with discernment. They read people through patterns of behavior rather than snap judgments. They give second chances when growth is evident, cut ties decisively when patterns repeat. Their intuition about character is unusually accurate because they observe how people treat the vulnerable, the inconvenient, the invisible.",
  },
  shadow: {
    body: "Wood's expansive nature can turn the Dog's protective instinct into suffocating control. They overstep boundaries while insisting it's for your own good, monitor loved ones' choices under the guise of care, mistake surveillance for support. Their flexibility in method but rigidity in values creates a specific tyranny—they'll accommodate your schedule but not your different moral framework.\n\nWhen Wood energy becomes excessive, they grow judgmental vines that choke relationships. They catalogue others' ethical failings, hold grudges disguised as \"standards,\" withdraw warmth from anyone who disappoints their increasingly elaborate expectations. Their righteousness calcifies into self-righteousness. They lecture when they should listen, prescribe when they should presence.\n\nThe shadow emerges most clearly when they're anxious: they micromanage, create unnecessary rules, demand loyalty tests. Their yang energy, unbalanced, becomes aggressive activism that alienates potential allies. They make enemies of people who agree with them 90% because of the 10% divergence. They burn out repeatedly because they can't distinguish between their responsibility and everyone else's, then resent others for not matching their exhaustion.",
  },
  relationships: {
    body: "Wood Dogs bond through shared mission and mutual reliability. They need partners who show up consistently, friends who contribute to collective wellbeing, not just take from it. Grand gestures mean less than repeated small acts of consideration. They remember who brought soup during your flu, who bailed when things got inconvenient.\n\nThey struggle with people who operate from pure self-interest or those who mistake their warmth for weakness. Betrayal of their trust or their community doesn't get forgotten—Wood's growth cycle has a long memory. But they're surprisingly forgiving of mistakes made in good faith. Admit you screwed up, show genuine change, they'll rebuild the bridge.\n\nIn intimacy, they express love through acts of service and protective attention. They need partners secure enough not to interpret their community devotion as emotional unavailability, and strong enough to call them out when concern becomes control. Their ideal relationships involve shared values and independent execution—same destination, different paths respected. They thrive with people who are as loyal to principles as they are to persons.",
  },
  elementBalance: {
    body: "Feed your Wood through purposeful growth, not frantic expansion. Choose three causes, not thirty—depth over breadth. Let Fire companions inspire you without burning you out; their enthusiasm can kindle yours without consuming your reserves. Avoid excessive Earth energy that makes you stubbornly immovable; you're meant to bend, not break.\n\nPhysically move daily—walk, stretch, practice flexibility literally to maintain it metaphorically. Prune your commitments seasonally like actual trees need pruning. Not everything you start must continue forever. Create space for new growth by releasing what's dead.\n\nWhen righteousness rises, ask: \"Am I protecting or controlling?\" Check yourself against Metal energy—its cutting clarity can trim your excess judgment. Spend time with Water types who remind you that flow matters as much as direction, that nourishing is different than managing.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-horse",
              "name": "Fire Horse",
              "reason": "Wood feeds Fire—your steady growth fuels their blazing initiative; shared yang energy creates dynamic forward momentum without competition"
          },
          {
              "slug": "earth-rabbit",
              "name": "Earth Rabbit",
              "reason": "Wood controls Earth productively—you provide direction for their nurturing stability; their yin gentleness softens your rigid edges"
          },
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Water generates Wood—they nourish your growth with emotional depth and generosity; shared loyalty values create unshakeable bonds"
          }
      ],
      "worst": [
          {
              "slug": "metal-dragon",
              "name": "Metal Dragon",
              "reason": "Metal chops Wood—their cutting ambition and dominance clash with your principled structure; Dragon's ego conflicts with Dog's collective focus"
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Double Metal axis hacks at your Wood flexibility—their perfectionist criticism and your moral judgment create mutually exhausting conflict"
          },
          {
              "slug": "earth-goat",
              "name": "Earth Goat",
              "reason": "Wood depletes Earth—you drain their resources with demands; Goat's indecisiveness frustrates your action-oriented nature; values misalignment festers"
          }
      ]
  },
}

export default content
