// ============================================
// WOOD RABBIT (甲卯) — The Gentle Visionary
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'wood-rabbit',
  profile: getProfileBySlug('wood-rabbit')!,
  archetype: {
    name: "The Gentle Visionary",
    tagline: "The Gentle Visionary — Wood Rabbit",
  },
  atAGlance: {
      "element": "Wood (Growth, Compassion)",
      "energy": "Yin",
      "archetype": "The Gentle Visionary",
      "coreStrength": "Diplomatic idealism",
      "shadow": "Conflict-avoidant passivity",
      "bestMatch": "fire-pig",
      "worstMatch": "metal-rooster",
      "luckyColor": "Celadon green"
  },
  personality: {
    body: "The Wood Rabbit embodies double Yin energy — gentle, receptive, attuned to nuance. You don't bulldoze through life; you grow around obstacles like vines seeking sunlight. Your Wood element amplifies the Rabbit's natural diplomacy into genuine visionary thinking. You see futures others miss because you're patient enough to watch patterns emerge. Where Metal cuts and Fire explodes, you persuade through persistent, compassionate presence. People underestimate this as weakness until they realize you've shifted the entire landscape while they were busy posturing.\n\nYour strength lies in strategic softness. You understand that flexibility is durability — bamboo bends in storms that snap oak trees. This makes you exceptional at mediation, creative collaboration, and long-term relationship building. You instinctively know when to yield and when yielding is actually strategic repositioning. Your Wood nature craves growth and expansion, but your Rabbit temperament ensures you never trample others in pursuit of your vision. You build consensus not because you're weak-willed, but because you understand distributed power creates more resilient systems.\n\nThe double Yin creates extraordinary emotional intelligence. You read rooms like weather patterns, sensing tension before it surfaces. This makes you invaluable in complex social ecosystems — corporate environments, creative collaborations, community organizing. You generate Fire through inspiration; your ideas spark others into action. You control Earth through gentle persistence; your quiet consistency shapes institutions over time. But you need environments that value subtlety. In cultures that worship aggressive Yang energy, you'll be overlooked despite being the most strategically sophisticated person present. Your genius requires audiences wise enough to recognize that soft power is still power.",
  },
  shadow: {
    body: "Your conflict avoidance curdles into cowardice when unchecked. You'll sacrifice integrity to maintain surface harmony, agreeing to terrible compromises because confrontation feels unbearable. This isn't peacekeeping — it's complicity dressed as diplomacy. The same flexibility that helps you adapt can become spineless accommodation. You'll bend so far backward you forget you have a backbone at all.\n\nYour strategic patience becomes procrastination when you're anxious. You tell yourself you're waiting for the right moment, but you're actually paralyzed by fear of disruption. The Wood Rabbit's gift for seeing multiple perspectives turns pathological — you empathize yourself into total inaction, understanding everyone's position so thoroughly you can't commit to your own. You'll let toxic situations fester for years rather than risk the discomfort of direct intervention. Meanwhile, your unexpressed resentment leaks out as passive-aggression — subtle digs, strategic forgetting, convenient unavailability. You think you're keeping the peace. You're actually poisoning the well while smiling.",
  },
  relationships: {
    body: "You need partners who value emotional sophistication over dramatic intensity. You're not cold — you run deep and slow, not hot and fast. Relationships with you are long-growth investments; you reveal yourself in layers over years. You're drawn to people who make you feel safe enough to stop performing diplomacy and just exist. But you have a fatal attraction to partners who need fixing, mistaking their chaos for depth.\n\nYour ideal match appreciates your subtle influence without exploiting your non-confrontational nature. You need someone who'll handle the direct conflicts you find exhausting, but won't steamroll you in the process. Fire signs give you warmth and direction; Earth signs provide stability for your growth. But you'll suffocate with rigid Metal types who mistake your flexibility for lack of conviction, and you'll enable Water types into stagnant pools of mutual avoidance. You're capable of profound loyalty, but you need partners who understand that gentle doesn't mean weak — and who won't mistake your quietness for absence of needs.",
  },
  elementBalance: {
    body: "Your excess Wood needs Metal's pruning — set hard boundaries and actually enforce them. Practice small confrontations daily until directness feels less catastrophic. Your Yin nature requires Yang activation: intense exercise, spicy foods, competitive environments in controlled doses. Generate Fire by committing to bold visions even when consensus is impossible; sometimes leadership means moving forward alone. Control your tendency toward Earth stagnation by changing environments frequently — new coffee shops, different routes, varied social circles. Water feeds your Wood but can drown you in emotional overwhelm; limit time with energy vampires regardless of how much you understand their pain. Schedule non-negotiable solitude to prevent your empathy from becoming self-erasure.",
  },
  matches: {
      "best": [
          {
              "slug": "fire-pig",
              "name": "Fire Pig",
              "reason": "Your Wood feeds their Fire; they give you warmth and courage while respecting your gentle approach"
          },
          {
              "slug": "water-pig",
              "name": "Water Pig",
              "reason": "Water nourishes Wood; shared compassion and idealism create deeply supportive partnership"
          },
          {
              "slug": "fire-goat",
              "name": "Fire Goat",
              "reason": "Your vision meets their creative passion; mutual Yin understanding with enough Fire energy to manifest dreams"
          }
      ],
      "worst": [
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal chops Wood; their cutting precision and rigid standards devastate your need for gentle growth"
          },
          {
              "slug": "metal-rat",
              "name": "Metal Rat",
              "reason": "Their sharp ambition and controlling nature clash with your flexible diplomacy; mutual frustration inevitable"
          },
          {
              "slug": "earth-dragon",
              "name": "Earth Dragon",
              "reason": "Your Wood controls Earth but their dominance demands attention you won't give; they'll see you as weak"
          }
      ]
  },
}

export default content
