// ============================================
// WOOD RAT (甲子) — The Resourceful Pioneer
// ============================================
// Generated by scripts/generate-content-v2.ts

import { getProfileBySlug } from './profiles'
import type { SignContentV2 } from '@/types'

const content: SignContentV2 = {
  slug: 'wood-rat',
  profile: getProfileBySlug('wood-rat')!,
  archetype: {
    name: "The Resourceful Pioneer",
    tagline: "The Resourceful Pioneer — Wood Rat",
  },
  atAGlance: {
      "element": "Wood (Growth, Expansion)",
      "energy": "Yang",
      "archetype": "The Resourceful Pioneer",
      "coreStrength": "Adaptive innovation",
      "shadow": "Scattered overreach",
      "bestMatch": "earth-ox",
      "worstMatch": "metal-monkey",
      "luckyColor": "Forest green"
  },
  personality: {
    body: "Wood Rat combines the Rat's opportunistic intelligence with Wood's expansive drive, creating someone who doesn't just spot openings—they create entire ecosystems around them. You're the person who walks into a stagnant situation and immediately sees twelve different ways to inject growth and possibility. Where others see scarcity, you see networks waiting to be activated. Your Wood element gives the Rat's natural resourcefulness a directional purpose: upward, outward, multiplying.\n\nYour genius lies in adaptive expansion. You don't force growth through rigid plans; you grow like bamboo—flexible, persistent, finding the path of least resistance while maintaining relentless upward momentum. You're exceptionally good at connecting disparate people and ideas, weaving social and professional networks that benefit everyone involved. Unlike Metal Rat's precision or Water Rat's depth, you think in terms of ecosystems. One project branches into three; one connection spawns five collaborations.\n\nThe Yang energy in your chart intensifies Wood's expansive nature, making you restless with stagnation. You need movement, development, new territories to explore. This makes you an excellent entrepreneur, community builder, or catalyst in any organization that's stuck. You have genuine compassion—Wood's gift—but it's active compassion. You don't just sympathize; you mobilize resources, connect people to solutions, build structures that address root causes.\n\nYour flexibility is strategic, not weak. You bend around obstacles because you're focused on the growth outcome, not ego. You'll take the indirect route, partner with unlikely allies, pivot completely if the original plan isn't generating momentum. This makes you remarkably effective in complex social environments where rigid types fail.",
  },
  shadow: {
    body: "Your expansive nature becomes scattered overreach when unchecked. You start ten projects, connect fifty people, commit to seven collaborations—then wonder why nothing reaches full maturity. Wood wants to grow, Rat wants to explore every option, and together they create someone who spreads themselves into ineffectiveness. You mistake activity for progress, networking for depth.\n\nYou can be manipulative under the guise of helpfulness. Your gift for seeing connections means you know exactly which strings to pull, and Wood Rat sometimes treats people like pieces in a network rather than autonomous beings. You're so focused on the growth outcome that you justify using social capital in ways that serve your expansion more than genuine mutual benefit.\n\nWhen your Wood element becomes unbalanced, you display irritability and controlling behavior disguised as 'helping people grow.' You push your vision of what should expand onto others, unable to tolerate their slower pace or different direction. Your flexibility disappears, replaced by rigid insistence that everyone get on board with your expansion plans.",
  },
  relationships: {
    body: "You need partners who provide either grounding or clear direction for your expansive energy. You're attracted to people who can anchor your many ideas into practical reality without crushing your innovative spirit. In relationships, you're genuinely invested in your partner's growth—sometimes too invested, pushing them to expand before they're ready.\n\nYour compassionate Wood nature makes you caring, but you show love through opportunity and connection rather than emotional depth or stability. You introduce your partner to people, open doors, create possibilities. If they want quiet consistency, they'll be frustrated. You need someone who appreciates that your form of devotion is expansive rather than containing.\n\nYour biggest relationship challenge is staying present. You're mentally three projects ahead, seeing future possibilities while missing current emotional needs. You can network your way out of intimacy, filling relationship time with 'productive' social activities rather than direct connection. Partners who need focused attention will feel neglected, while those who value growth and freedom will thrive with you.",
  },
  elementBalance: {
    body: "Balance your Wood excess by introducing Metal structure—not to restrict growth, but to prune it strategically. Practice saying no to new projects until existing ones bear fruit. Create boundaries around your expansion: finish three things before starting three more.\n\nCultivate Earth element stability through physical routines. Regular meal times, consistent sleep, repetitive practices that ground your scattered energy. Earth absorbs Wood's excess without killing it—think gardening, pottery, cooking, anything that produces tangible results through patient process.\n\nSchedule rest as deliberately as you schedule networking. Wood needs dormancy periods to consolidate growth. Your winter isn't failure; it's root development.",
  },
  matches: {
      "best": [
          {
              "slug": "earth-ox",
              "name": "Earth Ox",
              "reason": "Earth stabilizes Wood's expansion while Ox provides the patient follow-through Rat lacks—complementary productivity cycle."
          },
          {
              "slug": "fire-tiger",
              "name": "Fire Tiger",
              "reason": "Wood feeds Fire naturally; both are Yang pioneers who amplify each other's bold vision and action."
          },
          {
              "slug": "earth-dragon",
              "name": "Earth Dragon",
              "reason": "Earth grounds both signs' expansive tendencies while Dragon matches Rat's ambition with grounded execution."
          }
      ],
      "worst": [
          {
              "slug": "metal-monkey",
              "name": "Metal Monkey",
              "reason": "Metal cuts Wood while both compete for cleverest-in-room status—destructive cycle plus ego clash."
          },
          {
              "slug": "metal-rooster",
              "name": "Metal Rooster",
              "reason": "Metal chops Wood's flexible growth into rigid standards; Rooster's criticism kills Rat's experimental spirit."
          },
          {
              "slug": "wood-horse",
              "name": "Wood Horse",
              "reason": "Excess Wood without grounding—both scatter in different directions, no stabilizing element to consolidate growth."
          }
      ]
  },
}

export default content
